### PR TITLE
implementation of magic gold converter

### PR DESCRIPTION
**Pull request by lBaah**
Add action to automatically check and convert stacks of 100 gold to 1 platinum and 100 platinum to 1 crystal.

Update items.xml to make sure we have item charges.
Update gamestore.lua to include magic gold converter
Update item capacity check on init.lua (again?)

### CODE REVIEW

**Review by cellss — APPROVED** [review]
Checked!
Item working fine!
I couldn't test item in the Store... I'll do it soon as possible

**Comment by lBaah** [comment]
should fix #553

**Review by cellss — CHANGES_REQUESTED** [review]
Please add a description on temporary gold converter Item

```
		<attribute key="description" value="That has 100 charges left and that will expire in 7 days.
You bought this item in the Store or gained it as a daily reward.
This item cannot be traded." />
```

and the correct weight value

`		<attribute key="weight" value="300" />`

As you can see on:

[https://www.tibiawiki.com.br/wiki/Temporary_Gold_Converter](url)

**Comment by cellss** [comment]
I've checked Magic Gold Converter on the Store!
Its works properly

Thank you @lBaah !

**Review by Raphaellb — CHANGES_REQUESTED** [review]
please change description 

                description = "Changes automatically either a stack of 100 gold pieces into 1 platinum coin, or a stack of 100 platinum coins into 1 crystal coin!\n\n\n- only usable by purchasing character\n- will be sent to your Store inbox and can only be stored there and in depot box\n- use it to activate or deactivate the automatic conversion\n- converts all stacks of 100 gold or platinum in the inventory whenever it is activated\n- deactivated upon purchase\n- usable for 500 conversions a piece"

**Comment by cellss** [comment]
> please change description
> 
> ```
>             description = "Changes automatically either a stack of 100 gold pieces into 1 platinum coin, or a stack of 100 platinum coins into 1 crystal coin!\n\n\n- only usable by purchasing character\n- will be sent to your Store inbox and can only be stored there and in depot box\n- use it to activate or deactivate the automatic conversion\n- converts all stacks of 100 gold or platinum in the inventory whenever it is activated\n- deactivated upon purchase\n- usable for 500 conversions a piece" 
> ```

@Raphaellb Where did you find it?

It's different on fandom page:

https://tibia.fandom.com/wiki/Magic_Gold_Converter

**Comment by Raphaellb** [comment]
I tested this, and it is working good. Thank you for this contribution.

**Pull request merged**
