### PR TITLE
Items Max Limit

### PR DESCRIPTION
**Pull request by heberholanda**

### CODE REVIEW

**Comment by dex-89** [comment]
Why exactly 80000?

**Comment by heberholanda** [comment]
Apparently items.otb has a limit of 40000 items, this change is to support more items from the new updates. We have already reached that limit.

**Comment by debone** [comment]
Now that I see this PR, I think we need to discuss more details about it and how the fix will look like.

**Comment by debone** [comment]
Let's try #1942, if it won't work, we can reopen this one and merge it.

**Pull request closed without merging**
