### PR TITLE
[WIP] Reorganization of Monsters Folder

### PR DESCRIPTION
**Pull request by civic23**
*Moved monsters from folders "new", "11.8, "winter_update" to their respective categories (Tibia Wiki)
*New folder for Lycanthropes category (Tibiawiki)
*New folder for Asuras category ("Asuri" according Tibia wiki)
*New folder for Amphibic category, Moved Frogs and Salamander to Amphibic (Tibia Wiki)
*New folder for Dreamelves category (Tibiawiki)
*New folder for Reptiles category (Tibiawiki)
*New folder for Bats category (Tibiawiki)
*New folder for Vampire category (Tibiawiki)
*Moved Dream Courts  Bosses and their summons to quest folder (Izcandar, Alptramun, Plagueroot, Malofur Mangrinder, Maxxenius,The Nightmare Beast)
*Moved monsters/bosses from  The Secret Library, First Dragon Quest, Halls of Hope, Cults of Tibia, The Perch Queen island, to quest folder
*Moved misplaced Bosses/Monsters from Cult of Tibia folder to their respective categories (Fix) https://github.com/opentibiabr/otservbr-global/issues/1417
*Moved misplaced Monsters from "Otherworld" folder to their respective categories
*Deleted duplicates from monsters.xml (Fix) https://github.com/opentibiabr/otservbr-global/issues/1417
*Deleted duplicated monsters

WIP
- [ ] Add Missing Monsters

- [ ] Add Feaster of Soul Quest Bosses

- [ ] Add Grave Danger Quest Bosses 

- [ ] Fix some bosses stats (in tibiawikia there' s not much information)

I hope this helps a little bit in sorting out the monster folder 👍

### CODE REVIEW

**Comment by dudantas** [comment]
Hi.
It was in my plans to organize in the order of the bestiary. What do you think?

**Comment by civic23** [comment]
like this? https://tibia.fandom.com/wiki/Bestiary/Classes, a folder for each class and inside the folder, the subclasses?

**Comment by civic23** [comment]
for example a folder for "Mammals class" and inside the folder the subclases,  ?https://tibia.fandom.com/wiki/Bestiary/Classes#Mammal

image

**Comment by civic23** [comment]
or like this, all the monsters from the same class in  the same folder ? like tibia wiki bestiary

image

**Comment by dudantas** [comment]
> or like this, all the monsters from the same class in the same folder ? like tibia wiki bestiary
> 
> image

This
Only the 

Amphibic
Aquatic 
Bird
Construct
Demon
Dragon 
Elemental
Extra Dimensional 
Fey
Giant
Human
Humanoid
Lycanthrope
Magical
Mammal
Plant
Reptile
Slime
Undead
Vermin

However, we must think about how to deal with the monsters that do not have in the bestiary.

**Comment by civic23** [comment]
separate non-bestiary monsters in the "quest" folder including bosses/summons like this 
image


and leave the bosses that have no quest inside the "bosses" folder

**Comment by dudantas** [comment]
> and leave the bosses that have no quest inside the "bosses" folder

It looks great, will be very welcome

**Comment by civic23** [comment]
@dudantas from lane 1030 to 1460 in monsters.xml are monsters without classes (Summons, Special monsters, Raids, Quests ,etc) need ideas to order these monsters

**Comment by oualid6496** [comment]
Some of the monsters of feaster of souls. Not sure if they are accurate tho.
https://otland.net/threads/monsters-feaster-of-souls.270942/
https://otland.net/threads/11x-the-nightmare-beast-room.271168/

**Pull request closed without merging**
