### PR TITLE
Update branch 10/12x from develop

### PR DESCRIPTION
**Pull request by dudantas**
- [x] update branch 10x with develop

- [x] debug on use potion (client 10)
image

- [x] error in distro before buying premium account (client 10)

- [x] boss reward loot message (client 10)
Before:
image
After:
image

- [x] fix bug in the loot channel (client 10)
Bofore: 
image
After:
image

- [x] debug at logout
- [x] subcategory useful things gamestore

### CODE REVIEW

**Comment by joao-blip** [comment]
Podium item debug

**Comment by methsoftgames** [comment]
há um bug na free bless (no sei se já foi resolvido, acho que nao)

https://cdn.discordapp.com/attachments/800530421024030801/800578602114613279/Screenshot_56.png

**Comment by dudantas** [comment]
> há um bug na free bless (no sei se já foi resolvido, acho que nao)
> 
> https://cdn.discordapp.com/attachments/800530421024030801/800578602114613279/Screenshot_56.png

como reproduzir? só dizer que tem um bug não resolve

**Comment by beats-dh** [comment]
In protocolgame.ccp you added 2 ```If (version <= 1099)``` that caused client 10 to debug when logging in and in OTC the view was all out of standard. Changing ```If (version <= 1099) to If (version <= 1199)``` everything was resolved

**Comment by Bipbop69** [comment]
image
market error
when selecting the item and putting for sale the item is deselected


--
Potions
when a player using client 12 uses potion next to a player with client 10 a debug occurs

**Comment by beats-dh** [comment]
> imagem
> erro de mercado
> ao selecionar o item e colocar à venda o item está desmarcado
> 
> -
> Poções
> quando um jogador usando o cliente 12 usa a poção ao lado de um jogador com o cliente 10, ocorre uma depuração

This potions error was supposed to be solved, are you using the PR base or did you commit by commit to your base?

**Comment by Bipbop69** [comment]
> > imagem
> > erro de mercado
> > ao selecionar o item e colocar à venda o item está desmarcado
> > 
> > 
> > 
> > Poções
> > quando um jogador usando o cliente 12 usa a poção ao lado de um jogador com o cliente 10, ocorre uma depuração
> 
> This potions error was supposed to be solved, are you using the PR base or did you commit by commit to your base?

yes, I am, he managed to use the potion in case the bug is occurring when another player uses the potion using client 12.
now the market problem i'm still looking for

**Comment by beats-dh** [comment]
> > > imagem
> > > erro de mercado
> > > ao selecionar o item e colocar à venda o item está desmarcado
> > > Poções
> > > quando um jogador usando o cliente 12 usa a poção ao lado de um jogador com o cliente 10, ocorre uma depuração
> > 
> > 
> > This potions error was supposed to be solved, are you using the PR base or did you commit by commit to your base?
> 
> yes, I am, he managed to use the potion in case the bug is occurring when another player uses the potion using client 12.
> now the market problem i'm still looking for

Screenshot_20210407-130032
I did the testI took the test now on the market and it is working normally! At least with the OTCV8 client

**Comment by Bipbop69** [comment]
> > > > imagem
> > > > erro de mercado
> > > > ao selecionar o item e colocar à venda o item está desmarcado
> > > > Poções
> > > > quando um jogador usando o cliente 12 usa a poção ao lado de um jogador com o cliente 10, ocorre uma depuração
> > > 
> > > 
> > > This potions error was supposed to be solved, are you using the PR base or did you commit by commit to your base?
> > 
> > 
> > yes, I am, he managed to use the potion in case the bug is occurring when another player uses the potion using client 12.
> > now the market problem i'm still looking for
> 
> Screenshot_20210407-130032
> I did the testI took the test now on the market and it is working normally! At least with the OTCV8 client

there is already a different customer is not it?
can you test with client 10 to confirm or not the error?

**Comment by beats-dh** [comment]
> > > > > imagem
> > > > > erro de mercado 
> > > > > ao selecionar o item e colocar à venda o item está desmarcado 
> > > > > Poções 
> > > > > quando um jogador usando o cliente 12 usa a poção ao lado de um jogador com o cliente 10, ocorre uma depuração
> > > > 
> > > > 
> > > > Esse erro de poções deveria ser resolvido, você está usando a base de PR ou se comprometeu por commit para sua base?
> > > 
> > > 
> > > sim, estou, ele conseguiu usar a poção caso o bug esteja ocorrendo quando outro jogador usar a poção usando o cliente 12. 
> > > agora o problema de mercado que ainda estou procurando
> > 
> > 
> > Screenshot_20210407-130032
> > Fiz o testeFiz o teste agora no mercado e está funcionando normalmente! Pelo menos com o cliente OTCV8
> 
> já existe um cliente diferente não é?
> você pode testar com o cliente 10 para confirmar ou não o erro?

My PC runs Linux, I'm going to ask someone to take the test for me.

**Comment by Bipbop69** [comment]
image
podium is no longer debugging on client 10 but not working on client 12

**Comment by Bipbop69** [comment]
1. when the vocation in dawnport changes is debugged or when talking to the oracle the client is debugged
I think it is related to the change of mana / life etc.
2. change of outfit / mount is opening normally more when the player chooses clothes etc and puts in ok not active
3. when the player enters the party is debugged (I am checking this) edit -- pt client 12 and client 10 = debug

**Comment by miah-sebastian** [comment]
I'm pretty sure the market bug is still relevant for 10 client, it looks like if there's a buy or sell offer for that item it allows you to focus, otherwise it doesn't.

**Comment by majestyotbr** [comment]
> 
> 
> I'm pretty sure the market bug is still relevant for 10 client, it looks like if there's a buy or sell offer for that item it allows you to focus, otherwise it doesn't.

**The branch client-10/12.x is being updated, there is a new PR for that:**
https://github.com/opentibiabr/otservbr-global/pull/2569

**Pull request merged**
