### PR TITLE
Set/get exhaustion correction

### PR DESCRIPTION
**Pull request by dudantas**
Fix on identation, bug with the message "sorry not possible" and storages os.time from actions.lua

Removed the os.time storage from the ferumbras ascendant quest levers. They already exist in the teleports that lead to the lever room.

Fixed other minor bugs in boss mechanics.

Removed the set/getExhaustion function.

Fixed bug on bosses teleports (#870) and levers (#821).

Removed get/setExhaustion functions from the bank npcs (it didn't work and the problem is in the modules and not in the scripts) and just put a script for all them.

Fixed the error that checks the storage of the player who pulls a lever, that is, it was just taking turns who pulled the lever and it was possible to repeat the boss several times. Now the time to try to kill the boss again is respected.

### CODE REVIEW

**Comment by dudantas** [comment]
@lycanzito da uma testada nesse PR aqui.

**Review by mattyx14 — APPROVED** [review]
Only require check names on bosses levers for example dragon king text are frozen horror 
And use ostime is more easy for a check time condition ❤️ like it

**Comment by mattyx14** [comment]
Check a bank only change name say for Tibian

On forgottenquest on movements check Challenger.lua and adapt new format here

Sorry I'm in the phone

**Comment by Lycanzito** [comment]
> @Lycanzito da uma testada nesse PR aqui.

Meu servidor é custom :/

**Comment by dudantas** [comment]
> Check a bank only change name say for Tibian
> 
> On forgottenquest on movements check Challenger.lua and adapt new format here
> 
> Sorry I'm in the phone

Fixed, thanks.

**Comment by majestyotbr** [comment]
Thanks.

**Pull request merged**
