### PR TITLE
feat: registering Zushuka, fix: Zulazza Raid Spawn Point

### PR DESCRIPTION
**Pull request by Raphaellb**
adding a couple of raid monsters in xml, and fixing spawn location for Zulazza and Chizzoron.

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/opentibiabr/OTServBR-Global/pull/408/

omrafir foi add já

**Review by ghost — APPROVED** [review]

**Comment by Raphaellb** [comment]
okay, tirei omrafir.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
avisa la no discord q os 4 ultimo PR podem ser merge ja kkk

**Comment by Raphaellb** [comment]
volta la pow. we miss you.

**Pull request merged**
