### PR TITLE
Fix First Dragon Quest

### PR DESCRIPTION
**Pull request by joseamaya1**
Bug fix: When a player enters the boss's room he cannot travel

### CODE REVIEW

**Comment by Raphaellb** [comment]
can you be more specific on this problem please? what boss room, and what teleport/tile/lever are you trying to use? what is the purpose of added ZorvoraxTimer = 10223, storage?

**Comment by MajestyOTBR** [comment]
@joseamaya1

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/movements/scripts/quests/first%20dragon/entranceTeleports.lua#L4

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Pull request merged**
