### PR TITLE
Some fixes events, configkey, optional stages, xp gain rate

### PR DESCRIPTION
**Pull request by APenDel**
### **Actual**
Issues opentibiabr/otservbr-global#2464

On login you have one "XP Gain Rate", when you get experience this value changed.
Event schedule only display info, but doesn't work.

### **Expected**
[Formulae Tibia Wiki](https://tibia.fandom.com/wiki/Formulae)
  - [x] Display correctely "XP Gain Rate".
  - [x] Event Schedule server-side.
  - [x] Exercise Training get bonus of events.

### global.lua & statup.lua
- moved form `global.lua -> globalevents\others\startup.lua` all events rates variables.
`getEventSSkill, getEventSExp and getEventSLoot` now load after events module.
- set `GlobalStorage.XpDisplayMode -> 1`

### player.lua
- Fixed `onGainExperience`; Added `preyBonus & staminaBoost` variable.
now use simple rule of 3...
Rat: if 5 exp --- 100% | ? exp --- 150% so... 5 / 100 * 150 = 7(BaseXpGain + etc) see [Rat](https://www.tibiawiki.com.br/wiki/Rat)

### lib\core\functions.lua
- `getLootRandom` approximate to real tibia.
- `getRateFromTable` when doesn't have stages, return default.

### exercise_training.lua
- deleted unnecessary variables; if not reused.
- added `SCHEDULE_SKILL_RATE` to calculate exp.

### configmanager.cpp & configmanager.h
- added `RATE_USE_STAGES` boolean config `rateUseStages = true`.
- fixed `RATE_EXPERIENCE`.
- set base rates to 1.

## creaturescript\others\login.lua
- fixed `setBaseXpGain`, now work with events too.

## spawn.cpp & spawn.h
- fixed interval spawn time.
- when the spawn time is less than `MINSPAWN_INTERVAL`, addMonster with min value.
- now `interval` to `30000`, less check time.

### game.cpp, scripts\luascript.cpp & protocolstatus.cpp
- some fixes

### src\otserv.cpp & config.lua.dist
- On/Off stagesExp(def: true).
- set rates to 1

### events.xml
- changed date for test.
- can use exprate="0", with any argument (this reduce the rate to 0, but not the exp).
NOTE: exprate, lootrate, spawnrate or skillrate in 100, it's default value.

## Type of change
  - [x] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested 
  - [x] [Rat](https://www.tibiawiki.com.br/wiki/Rat) Test 1: without event, rateExp x1 + stamina : 150% = 7.5
  - [x] [Rat](https://www.tibiawiki.com.br/wiki/Rat) Test 2: with event +100%, rateExp 100% + prey 40% + store 50% + stamina x1.5 : 435% = 21,75
  
**Test Configuration**:
  - Server Version: 8e85d5d95c4dd85fa9e04b385517f265465b559b
  - Client: Client 12.64
  - Operating System: Windows x64

## Checklist
  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings (i don't see)
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by mattyx14 — APPROVED** [review]

**Comment by mattyx14** [comment]
i check it work only have problems on stages on magic level rates

**Comment by APenDel** [comment]
> i check it work only have problems on stages on magic level rates

what kind of problem?...

**Comment by mattyx14** [comment]
no work
```LUA
-- Minlevel and multiplier are MANDATORY
-- Maxlevel is OPTIONAL, but is considered infinite by default
-- Create a stage with minlevel 1 and no maxlevel to disable stages
experienceStages = {
	{
		minlevel = 1,
		maxlevel = 50,
		multiplier = 15
	},
	{
		minlevel = 51,
		maxlevel = 100,
		multiplier = 13
	},
	{
		minlevel = 101,
		maxlevel = 200,
		multiplier = 10
	},
	{
		minlevel = 201,
		maxlevel = 400,
		multiplier = 8
	},
	{
		minlevel = 401,
		maxlevel = 600,
		multiplier = 6
	},
	{
		minlevel = 601,
		multiplier = 4
	}
}

skillsStages = {
	{
		minlevel = 1,
		multiplier = 50
	}
}

magicLevelStages = {
	{
		minlevel = 1,
		multiplier = 25
	}
}
```
Level and Skills work perfecly only magic only read from config.lua

**Comment by APenDel** [comment]
> no work
> Level and Skills work perfecly only magic only read from config.lua

It works perfectly for me...
Remember that the objects that give ML influence the stages..(use rateUseStages = true in config.lua).

Edit: tested in ML 123 to 124.

```lua
skillsStages = {
  {
    minlevel = 0,
    maxlevel = 1,
    multiplier = 700
  }, {
    minlevel = 2,
    multiplier = 1
  }
}

magicLevelStages = {
  {
    minlevel = 0,
    maxlevel = 123,
    multiplier = 700
  }, {
    minlevel = 124,
    multiplier = 1
  }
}
```

**Comment by mattyx14** [comment]
i test with 2 values and work ... 

image

**Comment by mattyx14** [comment]
i test and all ok only require remarge changes

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Tested and working.

**Comment by XmasGame** [comment]
_always it appears at half__
https://ibb.co/nkQ8D1y

**Comment by APenDel** [comment]
> _always it appears at half__
> https://ibb.co/nkQ8D1y

SEE THE EVENTS

%50.... exp.

**Comment by majestyotbr** [comment]
The repository that submitted this pull request has been deleted. This changes need to be submitted again in a new pull request.

**Comment by dudantas** [comment]
> The repository that submitted this pull request has been deleted. This changes need to be submitted again in a new pull request.

Ok I'll do it!

**Comment by beats-dh** [comment]
> > The repository that submitted this pull request has been deleted. This changes need to be submitted again in a new pull request.
> 
> Ok I'll do it!

Can I do it or leave it to you?

**Comment by dudantas** [comment]
> > > The repository that submitted this pull request has been deleted. This changes need to be submitted again in a new pull request.
> > 
> > 
> > Ok I'll do it!
> 
> Can I do it or leave it to you?

Yes you can. It makes it easier for me, as there are other things I need to do in the repository.

**Pull request closed without merging**
