### PR TITLE
Update damage

### PR DESCRIPTION
**Pull request by lBaah**
remove duplicated halved damage

### CODE REVIEW

**Comment by enzerah** [comment]
don't look good to me bruh

**Comment by lBaah** [comment]
Great review @EnzzoCaaue. Lot's of information and data provided as never seen before.
Certainly this is going to change everything.

**Comment by enzerah** [comment]
yeah but this is to set crit for non black skull players and black skull players, since theyr damage are different

**Comment by gerotib** [comment]
As I am testing it doesnt matter at all (if were talking about damage on players with mana shield). With or w/o this commit regular and critical damage on player with & without BS works correct. Looks like this critical applying only matter in CombatHealthFunc and are affecting mana the same way.
Note that I am not using 100% clear repo code now (and cant really do at the moment), but I dont think that I made any change that could affect this.

**Comment by lBaah** [comment]
You're totally correct @gerotib. The damage/critical is applied and calculated in health function.
This commit works properly for you?

**Comment by gerotib** [comment]
Yeah everything fine

**Pull request merged**
