### PR TITLE
Threatened Dreams Quest

### PR DESCRIPTION
**Pull request by heberholanda**
### Quest: Threatened Dreams Quest
**Link Ref:** [Wiki](https://www.tibiawiki.com.br/wiki/Threatened_Dreams_Quest#Troubled_Animals)
**Video Quest:** [Youtube](https://www.youtube.com/watch?v=9kinLOQV7ws)

**Configurations:**
- [x] NPC Alkestios
- [x] NPC Alkestios
- [x] NPC Ahmet
- [x] Reward Quest Book
- [x] NPC Ikassis
- [x] Quest Log Updates
- [x] NPC Ghostly Wolf
- [x] NPC Irmana
- [x] NPC A Swan
- [x] NPC Chief Grarkharok
- [x] NPC Tereban
- [x] Movements for Tattered Swan Feathers
- [x] Respaw NPC Ghostly Wolf, created only in night (tibia time)
- [x] Action - Fur of a Wolf Whelp
- [x] Reward - Notes of a Poacher

**Edit in Map:**
```
Box Quest Book (Add UID: 34123 Position: 32787, 31975, 11)
Edron AID 50301  -  {x = 33200, y = 31892, z = 7}
Darashia AID 50302 - {x = 33257, y = 32402, z = 7}
Darashia AID 50303 - {x = 33262, y = 32379, z = 7}
Darashia AID 50304 - {x = 33256, y = 32314, z = 7}
Darashia AID 50305 - {x = 33249, y = 32267, z = 6}
Skeleton AID 28600 - {x = 32949, y = 31810, z = 7}
```

**Storages Used:**
```
	ThreatenedDreams = {
		Start = 50270,
		TroubledMission01 = 50271,
		TatteredSwanFeathers = 50300,
		TatteredSwanFeathers01 = 50301,
		TatteredSwanFeathers02 = 50302,
		TatteredSwanFeathers03 = 50303,
		TatteredSwanFeathers04 = 50304,
		TatteredSwanFeathers05 = 50305
	},
```

**Quest finished, I am waiting for your help to test and give us feedback.**
;]

### CODE REVIEW

**Comment by dex-89** [comment]
I have a question about NPC Ghostly Wolf. It can only be found during the Tibian night. It works like that here too?

**Comment by heberholanda** [comment]
> I have a question about NPC Ghostly Wolf. It can only be found during the Tibian night. It works like that here too?

The NPC is always there.
aaa

**Comment by dex-89** [comment]
"Viaje até Cormaya e siga até para o sul até encontrar a NPC Ghostly Wolf, por se tratar de um fantasma só será possível encontrá-la à noite."

Source: https://www.tibiawiki.com.br/wiki/Threatened_Dreams_Quest#Troubled_Animals

Need add function to add/remove npc with Tibian time to be fully real :)

**Comment by heberholanda** [comment]
> "Viaje até Cormaya e siga até para o sul até encontrar a NPC Ghostly Wolf, por se tratar de um fantasma só será possível encontrá-la à noite."
> 
> Source: https://www.tibiawiki.com.br/wiki/Threatened_Dreams_Quest#Troubled_Animals
> 
> Need add function to add/remove npc with Tibian time to be fully real :)

maybe i maker after, you can feel free to do and share with us.

**Comment by Vitaapng** [comment]
image

I tested it and it is working.

thanks @HeberPcL

**Review by Piotr3k1447 — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
