### PR TITLE
Add Server Save configuration to the config.lua file

### PR DESCRIPTION
**Pull request by Costallat**
Add configuration to enable/disable server save notify

Signed-off-by: Renato Foot <rcostallat@daitangroup.com>

### CODE REVIEW

**Review by westwol — CHANGES_REQUESTED** [review]
addEvent(serverSave, 60000) should be out of the scope as server save will remain happening even if you don't want players to be notified.

**Comment by Costallat** [comment]
Fixed, tks!

**Comment by westwol** [comment]
LGTM

**Comment by Raphaellb** [comment]
@westwol Hello, The daily rewards fix works, but I am getting an error on the log when trying to get the prey wildcard reward, and it doesn't work. any idea?

Lua Script Error: [Modules Interface]
data/modules/scripts/dailyreward/dailyreward.lua:onRecvbyte
data/modules/scripts/dailyreward/dailyreward.lua:518: attempt to call method 'addBonusReroll' (a nil value)
stack traceback:
        [C]: in function 'addBonusReroll'
        data/modules/scripts/dailyreward/dailyreward.lua:518: in function 'selectDailyReward'
        data/modules/scripts/dailyreward/dailyreward.lua:210: in function <data/modules/scripts/dailyreward/dailyreward.lua:204>

**Comment by MajestyOTBR** [comment]
@Raphaellb Please, create a issue to fix the error in other pull request. Thanks.

**Comment by Costallat** [comment]
@Raphaellb I sent an update, check if it solves the problem otherwise, create an issue.

Tks

**Comment by majestyotbr** [comment]
@Costallat The fix for prey wildcard reward worked. Thanks.

**Comment by majestyotbr** [comment]
LGTM

**Pull request merged**
