### PR TITLE
Dryad Garden

### PR DESCRIPTION
**Pull request by joseamaya1**
Fix Issue  #1593
actions for entrance and exit of dryad garden

### CODE REVIEW

**Comment by gpedro** [comment]
can you tell us what change you did on the map?

**Comment by joseamaya1** [comment]
I have added the uniqueids from the dyard garden script in these fountains view image here: https://imgur.com/IhmqwLG

**Comment by dudantas** [comment]
Can you remove the change on the map? We can put it on the tables in Lua.

**Comment by MajestyOTBR** [comment]
It's dryad, fix the typo in script and file name.

**Comment by majestyotbr** [comment]
It's dryad, fix the typo in the script and in the file name.

**Comment by majestyotbr** [comment]
#1671

**Pull request closed without merging**
