### PR TITLE
-- loot correction

### PR DESCRIPTION
**Pull request by enzerah**

### CODE REVIEW

**Review by FakeShinoda — APPROVED** [review]

**Comment by FakeShinoda** [comment]
LGTM
thanks for the contribution.

**Comment by enzerah** [comment]
lgtm ? what does it means bro ?

**Comment by gerotib** [comment]
"looks good to me"

**Comment by enzerah** [comment]
thanks @gerotib  =D

**Review by lBaah — APPROVED** [review]

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Pull request merged**
