### PR TITLE
Item/loot colors from the market/npcs

### PR DESCRIPTION
**Pull request by dudantas**
This shows the colors of the items based on the market (or the price of the npcs)

Credits to: @luksrt (Lucas Prazeres)

Retired from: https://github.com/cacovi/OTG-Premium-Version/commit/27b8f022ef5699af8a9af944bae0c7e3c611e7c7

### CODE REVIEW

**Comment by worthdavi** [comment]
Credits to @LukSrT
A stolen system, noice!!!!!!

**Comment by edmararulez** [comment]
> Credits to @LukSrT
> A stolen system, noice!!!!!!

relax, at least 80% of the 'otg' commits are copies of this git and at least 50% have credits.

**Comment by worthdavi** [comment]
> > Credits to @LukSrT
> > A stolen system, noice!!!!!!
> 
> relax, at least 80% of the 'otg' commits are copies of this git and at least 50% have credits.

does not change anything, we don't contribute with both
keep doin the good job: scamming systems without aprove from its owner

**Comment by Costallat** [comment]
@worthdavi Now you see how nice is to copy things from here without giving credits, why you don't go on the other repositories that also copy and worst sell things that are free here and complain with them too?

It hurts when it is with you!

Thanks for your cooperation,
have a nice day!

**Comment by dudantas** [comment]
@worthdavi Set stolen?

**Comment by dudantas** [comment]
If anyone looks at the commits from your repository (and even the base) it is copied from here. Almost everything. Little is not. So it’s redundant for you to talk like that. In addition, the contribution is public.
What we ask for here is that you give due credit to the authors of the prs (something you don't do, for example bestiary and quicklooting) and several other things ...

Don't look like you're talking right, at least have decency.
I ask you not to say it like that again, we never went there to ask for credit despite the clear ripping ...

**Comment by worthdavi** [comment]
Guys, what the fuck are you talking about? We're not contributers of OTG. Stop talking bulshit. This system has been sold for days by its own owner. You're fucking with someone's 'job'. It's a stolen product and doenst matter if it has credits or not. Stop talking about another repository that we never even used in our projects. It's a stolen code, nothing  more. And even with his credits, you didn't even tagged him. Do you know why? Because you banned him from this repository. If you ban someone, why would you post his codes? Cadê a vergonha na cara? Kakakak

**Comment by FakeShinoda** [comment]
Ninguem liga, vai reclamar com a pessoa que comprou e liberou.. afinal se mata o mal pela raiz! : D

**Comment by worthdavi** [comment]
> Ninguem liga, vai reclamar com a pessoa que comprou e liberou.. afinal se mata o mal pela raiz! : D

ok boomer vou voltar a resolver minhas coisas aqui com meus próprios códigos hihi tenta fazer o mesmo. ♥️
bom dia gente, até a próxima 
aos que foram educados, parabéns e continuem assim. @Costallat

**Comment by dudantas** [comment]
@worthdavi tudo que eu tenho e faço tá nesse repositório e você vem chorar dizendo que não damos valor para o trampo dos outros? Cara, vai chorar em outro lugar. 

Não temos culpa se alguém liberou o código que vocês venderam. Reclame com o cliente de vocês, não com a gente.

https://github.com/cacovi/OTG-Premium-Version/commit/27b8f022ef5699af8a9af944bae0c7e3c611e7c7

Reclama lá, não aqui

**Comment by dudztroyer** [comment]
Isso aí eu já ia fazer logo mais independente se o cara vende caro 50 linhas de um código... 

Se vc tem um "produto" e vende ele como OPEN source, e alguém vai lá e coloca ele em OPEN source num git Sem QUALQUER tipo de licença definida, assume-se uma licença de creative commons. Então vc acaba de perder sua propriedade intelectual e liberou ela pra uso público. Quer vc goste ou não.

Pelo menos deram os créditos aqui invés de dizer que foi feito sozinho, como QUALQUER outro repositório faz.

Além disso tá mal e porcamente produzido, como vcs tem coragem de vender algo assim? Kkkk

**Comment by miezaF** [comment]
eu acho que é o momento ideal pra eu aparecer e falar:

- nossa.

**Comment by Flyckks** [comment]
bando de cuzão ,arregaram porque eu cheguei.

**Comment by dudantas** [comment]
> bando de cuzão ,arregaram porque eu cheguei.

que garoto afoito

**Pull request merged**
