### PR TITLE
Fix vocation display in client

### LINKED ISSUE #266: [Bug]: Vocation
### What happened?

https://www.youtube.com/watch?v=6Qn-DVRfdus

### How to Reproduce?

1. Log in
2. Press CTRL+G or log out

### Relevant log output

_No response_

### Attach any relevant file

_No response_

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #2696: [Bug]: Vocation
### What happened?

https://www.youtube.com/watch?v=6Qn-DVRfdus

### How to Reproduce?

1. Log in
2. Press CTRL+G or log out

### Relevant log output

_No response_

### Attach any relevant file

_No response_

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dex-89**
# Description

Fix #2696 

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

#2696 

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

https://user-images.githubusercontent.com/67392692/129054359-1ddbf602-2d9a-4e79-8ac9-7284710b822b.mp4

**Test Configuration**:

  - Server Version: Current develop
  - Client: 12.64 - 12.67
  - Operating System: Any

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] I have commented my code, particularly in hard-to-understand areas
  - [X] I have made corresponding changes to the documentation
  - [X] My changes generate no new warnings
  - [X] I have added tests that prove my fix is effective or that my feature works

Author: @SaiyansKing

### CODE REVIEW

**Review by mattyx14 — APPROVED** [review]

**Comment by andersonfaaria** [comment]
How this affects old 12.x versions? does all of them utilizes that same client id range?

**Comment by beats-dh** [comment]
You must also change in:
https://github.com/opentibiabr/otservbr-global/blob/10b05d0e9e88c681b21f32fc31603794e6293070/data/lib/tables/vocation.lua

**Comment by majestyotbr** [comment]
Add a title that describe the fix.

**Comment by SaiyansKing** [comment]
> How this affects old 12.x versions? does all of them utilizes that same client id range?

I don't have too much of collection of those old 12.x versions but I can guarantee that the promotion identifier was added somewhere around 12.20 version. On the older versions that didn't have such identifier the client will most likely crash.

**Comment by dex-89** [comment]
> You must also change in:
> https://github.com/opentibiabr/otservbr-global/blob/10b05d0e9e88c681b21f32fc31603794e6293070/data/lib/tables/vocation.lua

Why? If it only works with CTRL + G or log out in the client, not in lua?

**Comment by dex-89** [comment]
No time to fix

**Pull request closed without merging**
