### PR TITLE
fix: gerimor transcription, resolves #1441

### LINKED ISSUE #1441: Npc Gerimor not responding.
**Describe the bug**
The npc Gerimor doesn't respond to the words that should give you the quest storage. (see image)

**To Reproduce**
1. Go to Gerimor.
2. Say hi
3. Try any of the words that he should answer to (only the quest related ones)

**Expected behavior**
He should respond to those words and give you eventually the storage.

**Screenshots**
Naamloos

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Saw that the set/get storage values have been written without a capital V which doesn't fix him not responding but might fix problems with storages later.
setStorage**v**alue which should be setStorage**V**alue
getStorage**v**alue which should be getStorage**V**alue

### PR DESCRIPTION
**Pull request by coney4**
Possible fix for npc. It need test.

### CODE REVIEW

**Comment by coney4** [comment]
fix for #1441

**Comment by gpedro** [comment]
image

**Review by gpedro — APPROVED** [review]

**Comment by gpedro** [comment]
@oualid6496 can you test?

**Comment by oualid6496** [comment]
> @oualid6496 can you test?

Will test it when I get home, ty!

**Review by thatmichaelguy — APPROVED** [review]
confirmed working

**Review by gpedro — APPROVED** [review]

**Review by oualid6496 — COMMENTED** [review]
yea works fine, ty!

**Pull request merged**
