### PR TITLE
Hirelings By Leu (jlcvp)

### PR DESCRIPTION
**Pull request by jlcvp**
Hirelings implementation (Private house NPCs)
https://www.tibiawiki.com.br/wiki/Hirelings

### CODE REVIEW

**Review by YohanAugusto — APPROVED** [review]

**Comment by Bipbop69** [comment]
debug in client 12+
has anyone else had this problem?

**Comment by jlcvp** [comment]
> debug in client 12+
> has anyone else had this problem?

2 questions:
- which specific version of client?
- describe the scenario to reproduce the debug.

**Comment by jlcvp** [comment]
changing the status to WIP until further investigation

**Comment by Bipbop69** [comment]
> changing the status to WIP until further investigation

this git uses the 12.00 ~~ 12.15 protocol when the character logs in he is debugged.
-edite-
tested without changes in SRC and had no debugs
client 12.00

**Comment by jlcvp** [comment]
image

@joao-blip I've did a clean install and logged in using the client on readme. 

Worked like a charm

**Comment by Bipbop69** [comment]
> image
> 
> @joao-blip I've did a clean install and logged in using the client on readme.
> 
> Worked like a charm

used which base?
I'm using otbr

**Comment by jlcvp** [comment]
this repo is for otbr, there's no reason I would be using other than that.

**Comment by Bipbop69** [comment]
> this repo is for otbr, there's no reason I would be using other than that.

I asked why you posted on another git.
wait for other people's feedback ..
-edit-
it's working I made some adaptations

**Comment by jlcvp** [comment]
> > this repo is for otbr, there's no reason I would be using other than that.
> 
> I asked why you posted on another git.
> wait for other people's feedback ..
> -edit-
> it's working I made some adaptations

But was it your fault it wasn't working on your setup or is there something on this PR code that needs to be fixed?

**Comment by htc16** [comment]
Testado no game, sistema muito top!
OBS: consegui por mais de 10 npc dentro da house; e o preço dos coins está diferente.

De resto, só da merge.

**Comment by jlcvp** [comment]
@Heitortadeu I've done the price adjustments and the hireling limit per player

**Comment by htc16** [comment]
Testei no game, ficou show!

**Comment by jlcvp** [comment]
adicionado inicialização de uma table de itens no npc

**Comment by Tazer89** [comment]
Works fine with tibia client but not working as it should in otclientv8 but dunno if its the goal to make it work with otclient. (Store module) when try buy hireling npc the name window does not popup and thefore cancels in otclientv8

**Comment by dudantas** [comment]
Thank you for your contribution, great work!
I intend to merge soon, however, I received some bug reports, I will test and return if it really is a bug.

**Review by dudantas — APPROVED** [review]
LGTM! 
Thanks for your contribution!

**Comment by rusaskii** [comment]
I can't buy them on store, "The product is currently not available for this character. See the Buy button tooltip for details."  Anyone else have this issue?

**Comment by lurkgabriel** [comment]
Just tested, same thing. Tested both as a god and player. /hireling Name, Sex works tho, you can summon him in your house buy his stuff (didn't try the cooking skill because I can't use the store to buy) 

Even if you, as a god, give yourself a hireling and summon him in your house you still won't be able to buy custom stuff at the store

**Comment by rusaskii** [comment]
Same happens to me. No answers if you say trade, or service.

I have just tryied it with full clean installation. Same issue. Cant buy in store (GOD, normal players).
When y summon it he dont answer.

**Comment by lurkgabriel** [comment]
he answers service for me as well as trade

**Pull request merged**
