### PR TITLE
Fix migration from older db

### PR DESCRIPTION
**Pull request by Costallat**

### CODE REVIEW

**Comment by gerotib** [comment]
For test I used schema from before #1259 ([this version](https://github.com/opentibiabr/otservbr-global/blob/11260e6f9de7928c57117e05142427a0052fc929/schema.sql)) and got error like this:

key2

**Comment by Costallat** [comment]
> For test I used schema from before #1259 ([this version](https://github.com/opentibiabr/otservbr-global/blob/11260e6f9de7928c57117e05142427a0052fc929/schema.sql)) and got error like this:
> 
> key2

I will check here

**Comment by Costallat** [comment]
@gerotib update, try again

**Review by gerotib — APPROVED** [review]

**Comment by gerotib** [comment]
@Costallat Yeah it went fine now :+1:

**Comment by Costallat** [comment]
Tks for the help!

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
