### PR TITLE
Feat: Supply Stash

### PR DESCRIPTION
**Pull request by marcosvf132**
> Same PR as before, I just couldn't fix the last one. (Yes, I screw the last one, sorry ;C)

Some parts I got from **vinioliveirasilva** and **SaiyansKings** script, **special thanks to them!**
- **ATM this is working with otservbr client 12.40+, on custom clients you MAYBE can have bugs and/or crashes, if this happens to you, tell me! maybe some changes might need to be done to support custom/old clients.**
- [x] Stow specific item by menu.
- [x] Stow all player items of same type.
- [x] Stow containers.
- [x] Drag and drop to stow.
- [x] Market integration.
- [x] Hireling NPC integration.
- [x] Quickloot retrieve backpack.

I need you to test it right now!!

- On default, all stackable items can be stowed, but there is a black list items that cannot be stowed. Add this line on items.xml to include a stackable item on the blacklist:
### If you find a item that should not be stowed into the supply stash, please leave a comment here.
``` xml
<attribute key="notstowable" value="1" />
```

### CODE REVIEW

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Tested, working. Thanks for your contribution.

**Comment by majestyotbr** [comment]
The pull request will remain open for a while for more people to test.

**Comment by enzerah** [comment]
I will test asap

**Comment by majestyotbr** [comment]
Time is running out, soon i will merge the pull request.

**Review by dudantas — APPROVED** [review]

**Comment by attack787** [comment]
Tested and its working. Thanks!

**Comment by enzerah** [comment]
Couldn't test yesterday, just tested rn.. lgtm.

**Pull request merged**
