### PR TITLE
Add summer update 

### PR DESCRIPTION
**Pull request by ifwednesday**
# Description

Está branch terá o intuito de construir os itens da atualização 12.70.
Pode ser um processo longo e necessita de testes.
Também haverá constantes mudanças e toda ajuda é bem vinda.

This branch will be intended to build the items from update 12.70.
It can be a long process and requires testing.
There will also be constant changes and all help is welcome.

## How Has This Been Tested

I need test

**Test Configuration**:

  - Server Version: Last
  - Client: 10 and 12
  - Operating System: All

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ifwednesday** [comment]
??? = não sei devida informação / não encontrei a mesma
??? = do not know due information / did not find the same

**Comment by majestyotbr** [comment]
Draft.

**Comment by ghost** [comment]
I tested and i found bug when you open market and select whatever item crash Tibia Client.

**Comment by dudantas** [comment]
Por favor, reabra o pull request neste repositório: https://github.com/opentibiabr/otservbr-global-datapack/

**Pull request closed without merging**
