### PR TITLE
Vocation Adjustments 12.6

### LINKED ISSUE #2083: Vocation Adjustments
Foram feitos ajustes significativos nas vocações e com objetivo de orientar o processo de implantação destas mudanças no projeto deixo aqui registrado:

Anúncio detalhado das mudanças:
+ [Vocation Adjustments Release](https://www.tibia.com/news/?subtopic=newsarchive&id=5846&fbegind=17&fbeginm=11&fbeginy=2020&fendd=17&fendm=12&fendy=2020&flist=11111111)

Alguns pequenos ajustes feitos após o anúncio:

+ [Fixes and Changes 1](https://www.tibia.com/news/?subtopic=newsarchive&id=5899&fbegind=17&fbeginm=11&fbeginy=2020&fendd=17&fendm=12&fendy=2020&flist=11111111)

+ [Fixes and Changes 2](https://www.tibia.com/news/?subtopic=newsarchive&id=5883&fbegind=17&fbeginm=11&fbeginy=2020&fendd=17&fendm=12&fendy=2020&flist=11111111)

+ [Fixes and Changes 3](https://www.tibia.com/news/?subtopic=newsarchive&id=5872&fbegind=17&fbeginm=11&fbeginy=2020&fendd=17&fendm=12&fendy=2020&flist=11111111)

### LINKED ISSUE #2185: BUG: New Magic Shield
Testing the new vocations ajusts, I found that when I spell utamo vita, I can only regenerate the purple bar with another utamo vita spell, not with the corresponding potions.
And when when I put utamo vita with the new potions, that's when the potions work and it regenerates the entire purple bar

### PR DESCRIPTION
**Pull request by hyresu**
Features:
https://www.tibia.com/news/?subtopic=newsarchive&id=5836&fbegind=23&fbeginm=11&fbeginy=2020&fendd=23&fendm=12&fendy=2020&flist=11111111
TODO:
- [x] Add to cledwyn magic shield potion (Added in #2130)
- [x] Fix quivers not updating their ammo quantity
- [x] Remove equipable ammo
- [x] Remove conjure diamond & spectral
- [x] Add new ammo
- [x] Add spectral bolt & diamond arrrow to npc
- [x] New Knight Spells
- [x] New Druid Spells
- [x] New Paladin Spells
- [x] New Sorcerer Spells
- [x] New Druid & Sorcerer Spells
- [x] Knight & Paladin allow mana potions
- [x] Change on existing spells
- [x] Change wand of darkness
- [x] Bows & XBows can be imbued with elemental dmg (not for diamond arrows)
- [ ] Use REAL Formulas
- [x] On change target distance show monster icon
- [x] Show icon on crippling (exori moe & exori kor)
- [x] Create new spell groups (ultimate, crippling etc)
- [x] Add new secondary groups to spells
- [x] Equip ammo on quiver via hotkey
- [x] Allow strong mana kegs & great mana kegs for new vocs
- [x] Added new icons (from id 16 to 26)
- [x] Added support for uint32_t range of icons

### CODE REVIEW

**Comment by dex-89** [comment]
cledwyn full trade list:

2020-12-22_202539538_Josephine de Lacuvier_Hotkey

**Comment by daanyx** [comment]
#2083

**Comment by daanyx** [comment]
Ajustes de vocação #2083 
Gostaria de vincular

**Comment by dex-89** [comment]
**Cledwyn is added, it was tested by me and working. (#2130)**

**Comment by daanyx** [comment]
Diamond Arrows and Spectral Bolts are already contained in the item.xml is there a need for additional com again? just to change the id?
It is not enough to just change the characteristics?

**Comment by hyresu** [comment]
@daanyx they use a different client id, that's why they are different items, I think it has a purpose, in rl when the change was made, all old diamond arrows were removed from players depot and inventory, so I mean, yeah, we could delete the first id, but they use different client id

**Comment by luucassoares** [comment]
Altought formulas aren't the real ones, everything is working fine here =)

**Comment by yatozin** [comment]
Haven't had any problems in past couple of day, working well

**Review by majestyotbr — APPROVED** [review]

**Review by dex-89 — APPROVED** [review]

**Pull request merged**
