### PR TITLE
Fury gates fix, rework and more

### PR DESCRIPTION
**Pull request by ElTeixe**
Reworked fury gates as mini world change.

- Added a map file for each city gate.
- Random gate loading at server startup, removing items like 'plants' that match firefields/ashes coordinates.
- Corrected ashes over firefields, now below them.
- Added missing Port Hope gate.
- Corrected some wrong gates, firefields, ashes coodinates.

NPCs

- Added Falonzo transcripts.
- Added Towncryer ability to inform about active mini world changes.

NOTE:

- Before this PR be merged, the main global map file ''otservbr.otbm' should be modified to remove the gates related items.

- To be removed from map:
-- Gate items:  [7851, 7852, 7853 - archway] [5064, 5066 - burning wall] [6116, 6117 - electric sparks]
-- Firefield items: [1492, 1493, 1494 - fire field]
-- Ash items:  [2249 - ashes]
-- Action Ids: Usually on the floor tile below the gate.

- The Fury Dungeon gate exit and its action id: 9715 must remain (the action id may be removed on the map and assigned in script data/startup/tables/item.lua ItemAction).

- About action ids, before was using 10 + 1 actions ids. 10 for each city gate entrance and 1 for the Fury Dungeon gate exit. Now it only needs 2, 1 for the active city gate entrance (due only one present at same time) and another for the Fury Dungeon gate exit. It may be adjusted to: 9710, 9711 for example or whatever if desired to win some free action ids.

- Test main global map file, with all gates related items removed for testing purposes: https://mega.nz/file/EVBAFRqA#NkG3Krb7ST_H_sCyFcuUm4lwvnfaG1gRVUm14rN1K0Q

Special thanks to @dex-89 for guide and support x)

### CODE REVIEW

**Comment by dudantas** [comment]
Progress finished? @ElTeixe

**Comment by dex-89** [comment]
> Progress finished? @ElTeixe

No. I need rework global map to remove fury gates

**Comment by dudantas** [comment]
> > Progress finished? @ElTeixe
> 
> No. I need rework global map to remove fury gates

Give me the positions so I can remove

**Comment by ElTeixe** [comment]
> > > Progress finished? @ElTeixe
> > 
> > 
> > No. I need rework global map to remove fury gates
> 
> Give me the positions so I can remove

You can check the positions at: https://github.com/opentibiabr/otservbr-global/blob/9a4242d4697e05e6bf3c171a7e722e4419b0114c/data/scripts/globalevents/worldchanges/fury_gates.lua, the exit ones and the items to be removed at first post

**Comment by dex-89** [comment]
> > > Progress finished? @ElTeixe
> > 
> > 
> > No. I need rework global map to remove fury gates
> 
> Give me the positions so I can remove

https://tibia.fandom.com/wiki/Fury_Gate

**Comment by ElTeixe** [comment]
@dudantas I forgot mention about: The Fury Dungeon gate exit and its action id: 9715 must remain (the action id may be removed on the map and assigned in script data/startup/tables/item.lua ItemAction).

**Comment by dudantas** [comment]
> @dudantas I forgot mention about: The Fury Dungeon gate exit and its action id: 9715 must remain (the action id may be removed on the map and assigned in script data/startup/tables/item.lua ItemAction).

Now I totally bugged ahaha

image
I realized that, in the global, it looks like this (with nothing)

**Comment by dudantas** [comment]
I updated your branch with develop from the repository, as it was out of date in more than 60 commits, I did it to be able to upload the updated map.
I removed the mentioned areas from the map, I went to the global and saw that there is nothing at the fury gates entrances, neither the portal nor the fires, I left it that way (I sent a print in the comment above).
If that's just what is needed to merge, let me know that I approve the pull.

**Comment by ElTeixe** [comment]
> I updated your branch with develop from the repository, as it was out of date in more than 60 commits, I did it to be able to upload the updated map.
> I removed the mentioned areas from the map, I went to the global and saw that there is nothing at the fury gates entrances, neither the portal nor the fires, I left it that way (I sent a print in the comment above).
> If that's just what is needed to merge, let me know that I approve the pull.

I gonna try check it now, one by one forcing every city gate to check all is working as intented before confirm.

About the update the branch with develop, yeah... Im a bit back on the develop branch, I started to work in some stuffs many days ago (on 12.51) and was lazy to update it (12.60) before finish them.

Give me some time, to check and more if I have to move to 12.60 and I'll confirm to you or not in another comment.

**Comment by ElTeixe** [comment]
> I updated your branch with develop from the repository, as it was out of date in more than 60 commits, I did it to be able to upload the updated map.
> I removed the mentioned areas from the map, I went to the global and saw that there is nothing at the fury gates entrances, neither the portal nor the fires, I left it that way (I sent a print in the comment above).
> If that's just what is needed to merge, let me know that I approve the pull.

Well, took me a while move to 12.60 and test it all.

There are some issues with the map modification:

- Ab'dendriel gate actionid: 9711 wasnt removed.
- Carlin gate actionid: 9713 wasnt removed.
- Edron gate actionid: 9714 wasnt removed.
- Kazordoon gate actionid: 9716 wasnt removed.
- Thais gate items, firefields, ashes wasnt removed and its gate actionid: 9712 wasnt removed.
- Venore gate actionid: 9710 wasnt removed.

Altough the actionids: 9711, 9712, 9713, 9714, 9716 werent removed, they arent really a problem due they are not used by the script (but may lead a issue if they are assigned to another script stuff).

BUT the actionid: 9710 the Venore one its really a problem, due its the actionid that use for all gates when are active, which means that Venore one, on that floor tile is always activated.

Screenshot proofs:

- Ab'dendriel
2021-01-08_062655575_GOD_Hotkey
`>> Fury Gate will be active in Ab'dendriel today`
2021-01-08_062951625_GOD_Hotkey


- Ankrahmun
2021-01-08_063231878_GOD_Hotkey
`>> Fury Gate will be active in Ankrahmun today`
2021-01-08_063407972_GOD_Hotkey

- Carlin
2021-01-08_063555173_GOD_Hotkey
`>> Fury Gate will be active in Carlin today`
2021-01-08_063841566_GOD_Hotkey

- Darashia
2021-01-08_064015520_GOD_Hotkey
`>> Fury Gate will be active in Darashia today`
2021-01-08_064236705_GOD_Hotkey

- Edron
2021-01-08_064634291_GOD_Hotkey
`>> Fury Gate will be active in Edron today`
2021-01-08_064852927_GOD_Hotkey

- Kazordoon
2021-01-08_065411357_GOD_Hotkey
`>> Fury Gate will be active in Kazordoon today`
2021-01-08_065609713_GOD_Hotkey

- Liberty Bay
2021-01-08_065843615_GOD_Hotkey
`>> Fury Gate will be active in Liberty Bay today`
2021-01-08_070133975_GOD_Hotkey

- Port Hope
2021-01-08_070358399_GOD_Hotkey
`>> Fury Gate will be active in Port Hope today`
2021-01-08_070531424_GOD_Hotkey

- Thais
2021-01-08_070853713_GOD_Hotkey
2021-01-08_071036821_GOD_Hotkey

- Venore
2021-01-08_071639251_GOD_Hotkey
`>> Fury Gate will be active in Venore today`
2021-01-08_071922250_GOD_Hotkey

**Comment by dudantas** [comment]
In fact, the actions were on the floor, I didn't notice that. Thank you, I will remove.
The rest, everything ok?

#Edit
Fixed, thanks!!! If that's all there, let me know, I'll give you an approve!

**Comment by ElTeixe** [comment]
> In fact, the actions were on the floor, I didn't notice that. Thank you, I will remove.
> The rest, everything ok?
> 
> #Edit
> Fixed, thanks!!! If that's all there, let me know, I'll give you an approve!

Hello! I've checked and tested everything again, and now everything is correct and working as intended!

**Review by dex-89 — APPROVED** [review]

**Review by dudantas — APPROVED** [review]

**Pull request merged**
