### PR TITLE
Making item name singular, so that when looked

### PR DESCRIPTION
**Pull request by rafael-adcp**
Making item name singular, so that when looked it doesnt end with "coinss", also addingscript to handle click on tibia coin, so that it can be added into players account'

### CODE REVIEW

**Comment by majestyotbr** [comment]
Custom action.

**Comment by lBaah** [comment]
It is "coins" because you can only trade stacks of 25 of them in the market.

**Comment by rafael-adcp** [comment]
hmm ok fair, agree with custom action, so 2 questions then, how are coins supposed to get to a player?
also if you use a gm and do /i tibia coin, 25 and look it will show as "tibia coinss" which is wrong imo

**Comment by majestyotbr** [comment]
Don't worry, will be fixed.

**Comment by lBaah** [comment]
This is not an obtainable item. Coins should be sent through AAC.
That item is necessary only to be displayed on market and Cyclopedia Items.

**Pull request closed without merging**
