### PR TITLE
fix: vocations mana/skills

### PR DESCRIPTION
**Pull request by gpedro**
suggested by: DkO

### CODE REVIEW

**Comment by ElTeixe** [comment]
From what I been checking last days, playing/testing on Official and fixing dawnport stuffs and implementing magic level and skills conversion for vocations, some of that changes are wrong.

- The change of match dawnport vocations with the main vocations is correct, but they should keep the same hp/mana/capacity gain than none vocation 5/5/10.

- The change on the melee skills (0, 1, 2, 3) multipliers on paladin, royal paladin, dawnport paladin, knight, elite knight and dawnport knight is wrong. They must remain as it they before.

- The multipliers that really changed was the manamultipliers. I still working on figure out the new ones, but at least for sure knight vocations should be 4.0 instead of 3.0.

I still working to verify them all, but may take a while. If you want fix it here good, anyway I'll continue to work on my fix.

**Comment by gpedro** [comment]
just in case, maybe we need to test this fix with PR #2186.

**Comment by DeCarvalhoJr** [comment]
> From what I been checking last days, playing/testing on Official and fixing dawnport stuffs and implementing magic level and skills conversion for vocations, some of that changes are wrong.
> 
> * The change of match dawnport vocations with the main vocations is correct, but they should keep the same hp/mana/capacity gain than none vocation 5/5/10.
> * The change on the melee skills (0, 1, 2, 3) multipliers on paladin, royal paladin, dawnport paladin, knight, elite knight and dawnport knight is wrong. They must remain as it they before.
> * The multipliers that really changed was the manamultipliers. I still working on figure out the new ones, but at least for sure knight vocations should be 4.0 instead of 3.0.
> 
> I still working to verify them all, but may take a while. If you want fix it here good, anyway I'll continue to work on my fix.

Based on Wiki and by going to official tibia you'll see Paladin skill distance faster than Knight level up melee, so making both equal is incorrect..
Ofc it needs more testing but assuming they are equal is wrong.. 
paladin distance 1.1 
knight melee 1.2
isnt the correct due test but it fits to what official test results delivered and even what wiki/fandom says
Paladin level up distance faster than knight level up melee

`Avança sua habilidade de combate à distância mais rapidamente do que qualquer outra vocação. (Mais rápido que um Knight avança em combate corpo-a-corpo);`
[Tibiakiwi about paladin](https://www.tibiawiki.com.br/wiki/Paladin)

And since paladin skill melee slower than knight it has 1.3 for melee skills.. as said, wasnt made any test on it to have the correct values yet they fit with official 

```
None
ML 2 - 76.81%
Melee/Distance 12 - 22.50%```
```
Druid
ML 4 - 1.20%
Melee 13 - 98.97%
Distance 13 - 98.86%```
```
Sorcerer
ML 4 - 1.20
Melee/Distance 12 - 22.50% (same as none)```
```
Knight
ML 2 - 76.81% (same as none)
Melee 15 - 100%
Distance 13 - 36.15```
```
Paladin
ML 3 - 37.04%
Melee 14 - 64.43%
Distance 15 - 100%```

This result was made w/o any leveling skill just base one, as said reading wiki/fandom talls one thing, tests need to be done.. skill changes were made based on what was gotten from what was supposed to be

**Comment by ElTeixe** [comment]
> just in case, maybe we need to test this fix with PR #2186.

Thats what Im doing, due that I suggested that change.

**Comment by ElTeixe** [comment]
@TheAncientDragon 

You are confusing the stuffs...

On official results:
None vocation club, axe, sword 12 - 77.50% -> knight 15 00%
None vocation distance 12 - 77.50% -> paladin 15 00%

So the skill multipliers for club, axe, sword on knights and distance on paladins must be the same: 1.1

Paladin:
`
<skill id="4" multiplier="1.1" />
`

Knight:
`
<skill id="1" multiplier="1.1" />
<skill id="2" multiplier="1.1" />
<skill id="3" multiplier="1.1" />
`

And it was right before.


The only true fact about, is that paladins skill faster club, axe, sword than knights skill distance. 

On Official results:
None vocation distance 12 - 77.50% -> knight 13 - 63.85%
None vocation club, axe, sword 12 - 77.50% -> paladin 14 - 35.57%

Paladin:
`
<skill id="1" multiplier="1.2" />
<skill id="2" multiplier="1.2" />
<skill id="3" multiplier="1.2" />
`

Knight:
`
<skill id="4" multiplier="1.4" />
`

And it was right before too.

**Comment by mrhultin** [comment]
> Based on Wiki and by going to official tibia you'll see Paladin skill distance faster than Knight level up melee, so making both equal is incorrect..

The reason for this, is that Blood hits/sparks (attacks where damage is fully absorbed by the monsters armor) are counted twice, not because their base multiplier is higher. I don't know why this is, but this is how it is. This used to be common knowledge before Telas training dummies were added (which you practically always did blood hits on, as they couldn't poof)

**Comment by mrhultin** [comment]
> Based on Wiki and by going to official tibia you'll see Paladin skill distance faster than Knight level up melee, so making both equal is incorrect..
The reason for this, is that Blood hits/sparks (attacks where damage is fully absorbed by the monsters armor) are counted twice, not because their base multiplier is higher. I don't know why this is, but this is how it is. This used to be common knowledge before Telas training dummies were added (which you practically always did blood hits on, as they couldn't poof)

**Pull request closed without merging**
