### PR TITLE
Fix #309

### LINKED ISSUE #309: Exercising Training on Store
The exercise weapons are working normally, with 500 cartoons as stipulated. When creating items using the / i command the items work perfectly. However, when placing the Exercises Weapons in the Store, after purchase the item receives only 1 charge.

- gamestore.lua
image

- items.xml
image
- In game

image

### PR DESCRIPTION
**Pull request by oualid6496**
I used the exercise weapons ids
((itemId >= ITEM_KEG_START and itemId <= ITEM_KEG_END) or (itemId >= 32384 and itemId <= 32389))
because im not sure where KEG_START is defined if someobody knows tell me and I will change the ids the same like the kegs to EXERCISE_START and EXERCISE_END

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/opentibiabr/OTServBR-Global/blob/a5ce7262428c464132693d2b7d985dc4b742f833/src/const.h#L560

**Comment by oualid6496** [comment]
Moved the ids to const.h and added to luascript.cpp it can be merged now

**Comment by ghost** [comment]
btw you could have defined it on https://github.com/opentibiabr/OTServBR-Global/blob/a5ce7262428c464132693d2b7d985dc4b742f833/data/global.lua#L11 but seeing how things are going to be in the future it should not matter :(

**Comment by oualid6496** [comment]
I thought it was better to just go further where people started but what do you mean with how thing are going to be in the future?

**Pull request merged**
