### PR TITLE
Remake of wrap/unwrap system

### PR DESCRIPTION
**Pull request by Costallat**
Need testing.

### CODE REVIEW

**Comment by MajestyOTBR** [comment]
Tested, it works.

**Comment by majestyotbr** [comment]
Tested, it works. But the wrap function stops working.

**Comment by Lycanzito** [comment]
Wrap function stops working.

**Comment by Costallat** [comment]
Test again

**Comment by Lycanzito** [comment]
Any idea why this is still not added?

**Comment by gpedro** [comment]
@MajestyOTBR can you test again?

**Comment by majestyotbr** [comment]
@gpedro Yes. With the latest changes, the function Use and Wrap works, Unwrap stops working.

**Comment by Lycanzito** [comment]
> Any idea why this is still not added?

my bad, didnt test the unwrap;
also the "use" shoulnt work, and it is working.

**Pull request closed without merging**
