### PR TITLE
create: function moveDownstairs

### PR DESCRIPTION
**Pull request by dudantas**
by: @Flyckks 
Thanks

### CODE REVIEW

**Review by mattyx14 — APPROVED** [review]

**Comment by Sargitarium** [comment]
Thx man.... love S2

**Comment by gpedro** [comment]
that's for...? where this function is used?

**Comment by Sargitarium** [comment]
move down without specifying a fixed position in the script, same as in
ASURA PLACE, where you step on a specific SQM and fall to a different
location

Em sáb, 17 de ago de 2019 às 11:41, Gabriel Pedro <notifications@github.com>
escreveu:

**Comment by gpedro** [comment]
LGTM

**Review by mattyx14 — APPROVED** [review]

**Pull request merged**
