### PR TITLE
Full review of the bless system

### PR DESCRIPTION
**Pull request by dudztroyer**

### CODE REVIEW

**Comment by Sargitarium** [comment]
error when compiling on linux ubuntu 16

**Comment by Lycanzito** [comment]
ward

**Comment by dudztroyer** [comment]
@Lycanzito salve, cheguei de viagem hj de madrugada, resolvendo umas paradas e dai dou atenção aqui

**Comment by dudztroyer** [comment]
Reworked whole blessings functions server wide, added support for both twist of fate and regular bless when losing items, fixed couple of minor bugs all though the server... Moved out some informations from source to lua (sendBlessStatus)...

(I assume) Fixed the bug that where even with bless it would drop items randomly

Modified !bless command to reflect ToF changes and prices according to level.

TODO is in blessings.lua, but should be this:
		"Insert & Select query in blessings_history",
		"Add unfair fight reduction",
		"Gamestore buy blessing",
		"Test ank print text",
		"Test all functions",
		"Test henricus prices/blessings",
		"Add data \\movements\\scripts\\quests\\cults of tibia\\icedeath.lua blessing information",
		"WotE data\\movements\\scripts\\quests\\wrath of the emperor\\realmTeleport.lua has line checking if player has bless 1??? wtf",
		"add blessings module support npc\\lib\\npcsystem\\modules.lua",
		"Fix store buying bless",
		"Check if store is inside lua or source...",
		"Find better way to sendBlessStatus"

thx

**Comment by dudantas** [comment]
Merged, thanks @dudztroyer

**Pull request merged**
