### PR TITLE
Prevent removing items from house if player is not invited

### PR DESCRIPTION
**Pull request by dex-89**
You shouldn't be able to remove items from house if you are not invited (open door scenario).

**Source:** https://github.com/otland/forgottenserver/pull/3159

**Owner:** @nekiro

### CODE REVIEW

**Review by dex-89 — COMMENTED** [review]
Compilation: no error

image

**Review by heberholanda — APPROVED** [review]
Tested, working well. Good job!

**Comment by JoaoCRDias** [comment]
has this been tested? I implemented in the sources returned the following warning when recompiling and it didn’t work, I can remove items that are on the doors of other houses not being invited

warnings:
1>C:\Users\Joao\Desktop\KingsmanOT\src\housetile.h(52,1): warning C4266: 'void Tile::internalAddThing(Thing *)': nenhuma substituição disponível para função membro virtual da base 'Tile'; função é ocultada (compilando arquivo de origem ..\src\protocollogin.cpp)
1>C:\Users\Joao\Desktop\KingsmanOT\src\tile.h(270): message : consulte a declaração de 'Tile::internalAddThing' (compilando arquivo de origem ..\src\protocollogin.cpp)
1>C:\Users\Joao\Desktop\KingsmanOT\src\tile.h(153): message : consulte a declaração de 'Tile' (compilando arquivo de origem ..\src\protocollogin.cpp)

**Comment by dex-89** [comment]
@Kolisium it was tested. In my screen you can see compilation without any errors

**Comment by dudantas** [comment]
> has this been tested? I implemented in the sources returned the following warning when recompiling and it didn’t work, I can remove items that are on the doors of other houses not being invited
> 
> warnings:
> 1>C:\Users\Joao\Desktop\KingsmanOT\src\housetile.h(52,1): warning C4266: 'void Tile::internalAddThing(Thing *)': nenhuma substituição disponível para função membro virtual da base 'Tile'; função é ocultada (compilando arquivo de origem ..\src\protocollogin.cpp)
> 1>C:\Users\Joao\Desktop\KingsmanOT\src\tile.h(270): message : consulte a declaração de 'Tile::internalAddThing' (compilando arquivo de origem ..\src\protocollogin.cpp)
> 1>C:\Users\Joao\Desktop\KingsmanOT\src\tile.h(153): message : consulte a declaração de 'Tile' (compilando arquivo de origem ..\src\protocollogin.cpp)

These are not compilation errors, they are warnings. And they are not related to PR. I said that in the commit comment.

**Pull request merged**
