### PR TITLE
Some updates in prey system.

### LINKED ISSUE #245: BUG: Prey bonus
#### Screenshots
Untitled

### LINKED ISSUE #2246: BUG: Prey bonus
#### Screenshots
Untitled

### PR DESCRIPTION
**Pull request by henriquesameshima**
1. Updated monster list and removed tier list. Thx @RodrigoSilva93
2. Fixed issue with prey slot not being inactive when time expires, causing it to continue receiving the bonus.
3. Fix #2246 - When the bonus is "damage boost" and when choosing a new monster with the active bonus (money or wild cards), the bonus was rolled.
4. Fix some typo.
5. Added Terrified Elephant to prey list.
6. Removed 0exp monster from list

### CODE REVIEW

**Comment by hyresu** [comment]
Thank you so much for these fixes, but I think in global it works like this:

(These 9 creatures are randomly selected from a large pool of creatures, but there will always be some low-level creatures, some mid-level creatures and some high-level creatures.)

**Comment by dex-89** [comment]
> Thank you so much for these fixes, but I think in global it works like this:
> 
> (These 9 creatures are randomly selected from a large pool of creatures, but there will always be some low-level creatures, some mid-level creatures and some high-level creatures.)

exactly. Sometimes at level 30 you can have demons on pray, similar to 200 - rats or cave rats

**Comment by henriquesameshima** [comment]
@dex-89 @hyresu I made some changes considering your observations.

Anyway, the old script defined the monsters according to lvl of the char and if it was for exemple >= 160, only monsters considered hard appeared.

1. Now I choose 3 monsters of each difficulty, according to the bestiary (star difficulty).

- 1 or 2 stars are monsters considered easy.
- 3 or 4 stars are monsters considered mid.
- 5 stars are monsters considered hard.

2. Removed some creatures that the server doesn't have yet and fixed some misspelled names.

**Comment by dex-89** [comment]
We need check player level:

too hard monsters for player 8 level

image

image

**Comment by henriquesameshima** [comment]
@dex-89 added level check and used the rules below:

1. Level 8~100 = 6 Low, 2 Mid, 1 Hard
2. Level 101~250 = 3 Low, 4 Mid, 2 Hard
3. Level 250+ = 2 Low, 4 Mid, 3 Hard

**Level 10**


**Level 160**


**Level 260**

**Review by dex-89 — APPROVED** [review]

**Review by Bipbop69 — APPROVED** [review]

**Comment by ElTeixe** [comment]
About difficulty tiers:

- 0* are considered harmless.
- 1* are considered trivial.
- 2* are considered easy.
- 3* are considered medium.
- 4* are considered hard.
- 5* are considered challenging.

Im not pretty sure about group <=2* on easy, <=4* on medium and 5* on hard.

About select the creatures based on level, Im not sure about the max amount of creatures for each tier like 8~100 = 6 Low, 2 Mid, 1 Hard.

I show you some data gathered on Official with my noob characters:

Level 10:
image
2* (Valkyrie, Mad Scientist, Bear)
3* (Werehyaena Shaman, Wyvern, Spectre, Massive Earth Elemental)
4* (Crazed Summer Vanguard)
5* (Cloak of Terror)

Level 10:
image
1* (Bat)
2* (Gnarlhound, Frost Giant)
3* (Brimstone Bug, Pirat Bombardier, Ogre Shaman)
4* (True Frost Flower Asura, Crypt Warden, Armadile)

Level 17:
image
2* (Salamander, Barbarian Headsplitter)
3* (Lizard Snakecharmer, Killer Caiman, Necromancer, Execowtioner)
4* (Hellflayer, Cave Devourer, Frazzlemaw)

Level 17:
image
2* (Minotaur, Minotaur Mage)
3* (Hellspawn, Enlightened of the Cult, Werewolf, Massive Water Elemental, Wilting Leaf Golem)
4* (Usurper Warlock, Cobra Assassin)

Level 17:
image
2* (Tortoise, Cobra)
3* (Minotaur Cult Zealot, Crystalcrusher, Green Djinn, Stampor)
4* (Infernalist, Hellhound)
5* (Infernal Demon)

Level 19:
image
2* (Pirate Ghost, Hunter, Rotworm)
3* (Glooth Bandit, Clay Guardian, Gravedigger)
4* (Juggernaut, Chasm Spawn, Ogre Ruffian)

Level 19:
image
1* (Troll)
2* (Orc Rider, Gargoyle)
3* (Bonebeast, Lost Husher, Blood Beast)
4* (Deepworm, Feral Sphinx, Deathling Spellsinger)

Following the same tier grouping and from (few) previous gathered data, the max amount for each tier seems be more like: 8~100 = 3 Easy, 7 Medium, 1 Hard.

Just trying give a bit feedback. Anyway thanks for the fixes and the improvements.

**Review by Bipbop69 — APPROVED** [review]

**Comment by dex-89** [comment]
We can add too:
- [ ] `Creatures which give no XP can no longer be selected as prey.`
- [x] `The creature "terrified elephant" has been added to the bestiary and can now be selected as prey.`

https://www.tibia.com/news/?subtopic=newsarchive&id=5970&fbegind=12&fbeginm=1&fbeginy=2021&fendd=11&fendm=2&fendy=2021&flist=11111111

**Comment by henriquesameshima** [comment]
@dex-89 thank's for your suggestions.

1. This line below checks if the monster is considered harmless and does not pass through the list, that is, a monster that does not give XP (correct me if I'm wrong).
https://github.com/opentibiabr/otservbr-global/pull/2360/files#diff-230b1cf9cc292b7336439ff77bf06bf19d1227c29031be52ad7fdc3b6c28a38cR694

2. Added Terrified Elephant to prey list.

**Comment by dex-89** [comment]
> @dex-89 thank's for your suggestions.
> 
> 1. This line below checks if the monster is considered harmless and does not pass through the list, that is, a monster that does not give XP (correct me if I'm wrong).
>    https://github.com/opentibiabr/otservbr-global/pull/2360/files#diff-230b1cf9cc292b7336439ff77bf06bf19d1227c29031be52ad7fdc3b6c28a38cR694
> 2. Added Terrified Elephant to prey list.

Honestly, I don't really know. @marcosvf132, @hyresu what do you think?

**Comment by hyresu** [comment]
I think the check should be at experience, as for example Wisp is considered Trivial and gives 0 exp, and ALL harmless creatures give 0 exp, so they would be unlisted too.

https://tibia.fandom.com/wiki/Wisp

So, atleast for me, the solution is just checking 0 exp

**Comment by henriquesameshima** [comment]
Thanks for the comment @hyresu, I made the suggested changes.

**Review by majestyotbr — APPROVED** [review]

**Review by ElTeixe — APPROVED** [review]

**Pull request merged**
