### PR TITLE
Fix connection lost info after offline training logout 

### LINKED ISSUE #2492: BUG: Offline Training cause connection lost
image

image

#### Environment
- OS: Windows 10
- OTServ Version: 19/03/2021
- Tibia Version: 12.64

### PR DESCRIPTION
**Pull request by ArturKnopik**
#2492 - possible fix

### CODE REVIEW

**Review by dex-89 — APPROVED** [review]
Works perfect. No errors :) Amazing work!

**Review by ghost — APPROVED** [review]
Nice work! Thanks

**Review by Bipbop69 — APPROVED** [review]

**Comment by methsoftgames** [comment]
Thanks! great job!

**Review by majestyotbr — APPROVED** [review]

**Comment by Juanzin420** [comment]
please revise, the change caused reconnecting throw character list (Ctrl+G) to bug and never reconnect to game
steps:
1- login on char,
2- ctrol+G to another char
3- ctrol+G to the char u first login
4- see error(never connecting)
_---
tested again, and it happens if you reconnect twice with ctrol+G

**Pull request merged**
