### PR TITLE
Prey Slots #696

### LINKED ISSUE #696: Terceira Prey
Alguem sabe como desativa a terceira prey ou botar apenas pra comprar na loja? os chares criados estão já logando com a terceira prey liberada

### PR DESCRIPTION
**Pull request by FakeShinoda**
- **Slots changes:**
Prey slot 1 for free
Prey slot 2 for premium
Prey slot 3 only via store

- Realocated sendPreyTime function
- Removed old prey functions on source

**WARNING**:
- Reload on "/lib" makes preyTimeLeft stops working
- To use this slot configuration make sure to truncate the table "prey_slots" in your DB, otherwise you'll have troubles.

**Credits**: Rick

### CODE REVIEW

**Comment by cys9211** [comment]
Good job

**Comment by majestyotbr** [comment]
Tested, working. Thanks for your contribution!

**Comment by VitorNM** [comment]
Nice job! Thanks

**Comment by mattyx14** [comment]
only remove line on creatureeevents loot

**Comment by FakeShinoda** [comment]
> 
> 
> only remove line on creatureeevents loot

unused declaration

**Pull request merged**
