### PR TITLE
[TFS] Add shopping bag

### PR DESCRIPTION
**Pull request by Costallat**
Added shopping bag to NPC "buy with backpacks".

### CODE REVIEW

**Comment by Lycanzito** [comment]
> Added shopping bag to NPC "buy with backpacks".

Im pretty new, but the shopping bag is already fine, when you buy with backpack.
What is this PR for?

**Comment by Costallat** [comment]
Change from a number that doesn't mean anything for who doesn't know what it is to a more readable think that is 'ITEM_SHOPPING_BAG'

**Comment by majestyotbr** [comment]
Anyone to test this?

**Review by mattyx14 — APPROVED** [review]

**Comment by MajestyOTBR** [comment]
Tested, working. Thanks for the contribution.

**Comment by majestyotbr** [comment]
Tested, working. Thanks for the contribution.

**Pull request merged**
