### PR TITLE
Optimized Clean with optional Protection Zone Clean

### PR DESCRIPTION
**Pull request by heberholanda**
### Optimized Clean with optional Protection Zone Clean

**config.lua**
`cleanProtectionZones = false`

/clean command:
Screenshot_65

/clean command updated:
Screenshot_65OPT

**Code From TFS**
Link: https://github.com/otland/forgottenserver/pull/2647

### CODE REVIEW

**Comment by joao-blip** [comment]
`-  #0  0x000055555579cef0 in Tile::onRemoveTileItem (this=this@entry=0x7ffee7136120, spectators=std::unordered_set with 0 elements, oldStackPosVector=std::vector of length 0, capacity 0, item=item@entry=0x7ffee71360e0) at /home/otbr/ot/src/tile.cpp:466
-          it = 0x0
-          iType = @0x7fffea898740: {group = ITEM_GROUP_GROUND, type = ITEM_TYPE_TRASHHOLDER, id = 4613, clientId = 4602, stackable = false, isAnimation = true, name = "shallow water", article = "", pluralName = "", description = "You see the silvery movement of fish.", runeSpellName = "", vocationString = "", abilities = std::unique_ptr<Abilities> containing 0x0, conditionDamage = std::unique_ptr<ConditionDamage> containing 0x0, weight = 0, levelDoor = 0, decayTime = 0, wieldInfo = 0, minReqLevel = 0, minReqMagicLevel = 0, charges = 0, maxHitChance = -1, decayTo = -1, attack = 0, defense = 0, extraDefense = 0, armor = 0, imbuingSlots = 0, rotateTo = 0, runeMagLevel = 0, runeLevel = 0, wrapableTo = 0, combatType = COMBAT_NONE, transformToOnUse = {0, 0}, transformToFree = 0, destroyTo = 0, maxTextLen = 0, writeOnceItemId = 0, transformEquipTo = 0, transformDeEquipTo = 0, maxItems = 8, slotPosition = 48, speed = 0, wareId = 0, magicEffect = CONST_ME_LOSEENERGY, bedPartnerDir = DIRECTION_NONE, weaponType = WEAPON_NONE, ammoType = AMMO_NONE, shootType = CONST_ANI_NONE, corpseType = RACE_NONE, fluidSource = FLUID_WATER, floorChange = 0 '\000', alwaysOnTopOrder = 0 '\000', lightLevel = 0 '\000', lightColor = 0 '\000', shootRange = 1 '\001', hitChance = 0 '\000', forceUse = false, hasHeight = false, walkStack = true, blockSolid = true, blockPickupable = false, blockProjectile = false, blockPathFind = false, allowPickupable = true, showDuration = false, showCharges = false, showAttributes = false, replaceable = true, pickupable = false, rotatable = false, wrapable = false, wrapContainer = false, useable = false, moveable = false, notstowable = false, alwaysOnTop = false, canReadText = false, canWriteText = false, isVertical = false, isHorizontal = false, isHangable = false, allowDistRead = false, lookThrough = false, stopTime = false, showCount = true}
-          i = <optimized out>
-  #1  0x000055555579d7e3 in Tile::removeThing (this=0x7ffee7136120, thing=<optimized out>, count=1) at /home/otbr/ot/src/tile.cpp:1075
-          spectators = std::unordered_set with 0 elements
-          creature = <optimized out>`

I had this error when starting with the server I was not calling I noticed that when I removed the 'yasir' it worked



` -  0x000055555579cef0 in Tile::onRemoveTileItem (this=this@entry=0x7ffee7136120, spectators=std::unordered_set with 0 elements, oldStackPosVector=std::vector of length 0, capacity 0, item=item@entry=0x7ffee71360e0) at /home/otbr/ot/src/tile.cpp:466
 -  466			auto it = getItemList();`

**Comment by HeberPcL** [comment]
1 - Did you just open the server and get this error?
2 - Did you remove NPC Yasir and did it work?

**Comment by joao-blip** [comment]
> 1 - Did you just open the server and get this error?
yes
> 2 - Did you remove NPC Yasir and did it work?
when I turn off the yasir script.

**Comment by HeberPcL** [comment]
Work fine for me

**Comment by joao-blip** [comment]
> Work fine for me, download branche and compile again
testing with yasir activated 100% chance?

**Comment by HeberPcL** [comment]
Use this branche man: 

https://github.com/HeberPcL/otservbr-global/tree/optimizeded_clean

The last branche using client 12.50

**Comment by joao-blip** [comment]
> Use this branche man:
> 
> https://github.com/HeberPcL/otservbr-global/tree/optimizeded_clean
> 
> The last branche using client 12.50
> 
> image

question is not in '/ clean' is in starting the server .. when it is 'creating yasir's ship map'

the 'branche' you cited is the same.
I will check the forgottenserver commit

**Comment by HeberPcL** [comment]
This pr is about Clean, ok? Erase your useless messages.

**Comment by joao-blip** [comment]
> This pr is about Clean, ok? Erase your useless messages.

yes, i know it's about cleaning.
if you read the error I posted you will notice it is in the edited files .. but I think you just got the tfs commit ...

already found the error I will test some more and report the discord or here.

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
