### PR TITLE
 Update branch 10/12x from develop

### PR DESCRIPTION
**Pull request by ghost**
Update branch 10x with develop and some bugs fixes

Fixed:
- [X] Change Outfit
- [X] Market
- [X] Party

### CODE REVIEW

**Comment by michu940107** [comment]
what is this? multiclient login?

**Comment by miah-sebastian** [comment]
i usually used visual studio, and vc14/otservbr-global.sln to compile, how do I compile otherwise?

**Comment by majestyotbr** [comment]
> 
> 
> i usually used visual studio, and vc14/otservbr-global.sln to compile, how do I compile otherwise?

https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Windows-(vcpkg)

**Comment by Beatss-Dh** [comment]
> Is there a way to enable debug? For me it's crashing at "Initializing Gamestate" with no errors, and no debug symbols.

In the client 10 gamestore has a sampling limit of 50 items per tab, you have to break it into several tabs respecting the 50 limit.

**Pull request closed without merging**
