### PR TITLE
Gamestore update

### PR DESCRIPTION
**Pull request by Geekbuddy**
Change offertype training to charges instead because that's basically is what it is.
Fixed magic gold converter with the charges change.
Added maximum check for prey wild cards, reward tokens in purchase process.

### CODE REVIEW

**Comment by majestyotbr** [comment]
And the Gold Converter?

**Comment by Geekbuddy** [comment]
> And the Gold Converter?

Fixed 👍

**Comment by MajestyOTBR** [comment]
The exercise weapons, gold converter and magic gold converted stopped working with the changes, you will need to revert.
Can you revert the code about guild system? So i can accept the other PR created after, it's not necessary to do this.

**Comment by Geekbuddy** [comment]
> The exercise weapons, gold converter and magic gold converted stopped working with the changes, you will need to revert.
> Can you revert the code about guild system? So i can accept the other PR created after, it's not necessary to do this.

Its working becouse its tested before posting, needs to add both init, and gamestore.

**Comment by MajestyOTBR** [comment]
It's working, probably i forgot something.

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
