### PR TITLE
Fix npc not removing money

### PR DESCRIPTION
**Pull request by Costallat**
Signed-off-by: Renato Foot Guimarães Costallat <costallat@hotmail.com>

### CODE REVIEW

**Comment by Costallat** [comment]
Can someone test this?

Tks

**Comment by lBaah** [comment]
With money on backpack:
All gold are removed from backpack, no matter how much gold/platinum/crystal you have.

With bank money only:
Correctly removes money from bank.

With money on backpack and bank:
Remove all money from backpack no matter how much gold/platinum/crystal you have + the total value from bank.

**Comment by gerotib** [comment]
Checked after new commit and everything seems to work fine.

**Review by FakeShinoda — APPROVED** [review]

**Comment by FakeShinoda** [comment]
Tested and works fine.
LGTM

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Comment by EleanorRigby1** [comment]
I was checking, the NPC Pompan and Esrik do not take your money from the bank but they still give you the item, if you resell you get money, that is, you start cloning. Could it be that Pompan and Esrik are only written in lua? Pay attention to this.

**Comment by lBaah** [comment]
@EleanorRigby1 thank you for the report. I have fixed this bug. You can check latest commits and change accordingly.

**Pull request merged**
