### PR TITLE
Some fixes events, configkey, optional stages, xp gain rate

### PR DESCRIPTION
**Pull request by beats-dh**
PR #2692

### **_Fixes:_**
- [x] #2464

### CODE REVIEW

**Review by majestyotbr — APPROVED** [review]

**Review by mattyx14 — APPROVED** [review]

**Review by Bipbop69 — COMMENTED** [review]
player.lua:Player@onGainExperience
data/events/scripts/player.lua:744: attempt to perform arithmetic on global 'baseExp' (a nil value)
stack traceback:
        [C]: in function '__mul'
        data/events/scripts/player.lua:744: in function <data/events/scripts/player.lua:702>
not doing the calculation when player has exp play + xp store + green stamina

**Comment by beats-dh** [comment]
> player.lua:Player@onGainExperience
> data/events/scripts/player.lua:744: attempt to perform arithmetic on global 'baseExp' (a nil value)
> stack traceback:
> [C]: in function '__mul'
> data/events/scripts/player.lua:744: in function <data/events/scripts/player.lua:702>
> not doing the calculation when player has exp play + xp store + green stamina

It's accusing error on line 744 I checked and didn't make changes to it, you have the PR Branch without changes?

**Comment by Bipbop69** [comment]
> It's accusing error on line 744 I checked and didn't make changes to it, you have the PR Branch without changes?

I'm using the current version with this commit.
putting it uses the exp of the stage in place of the base is ok.

but you will have the problems I said

exp prey is not being and store is not pulling correctly
in this case it would have to be applied in the stage the player is in but it is always being applied in the mob's exp

**Review by dudantas — APPROVED** [review]

**Comment by dudantas** [comment]
It will be fixed in the repository: https://github.com/opentibiabr/otservbr-global-datapack

**Pull request closed without merging**
