### PR TITLE
Website events.xml update

### PR DESCRIPTION
**Pull request by dex-89**
**How it works?**

1. Move `events.xml` file from `data/XML/events.xml` to website directory
2. Set `eventsUpdate` in `config.lua` as `true`
3. Set corrected path to file from point 1 in `eventsUpdatePath` in `config.lua`
4. Restart your server
5. If all works ok:
image
6. Older `events.xml` in `data/XML` will be overwritten!
7. **If you have multiple servers - all servers will be updated with one file!**
8. Edit only one file (from point 1) to edit events on all servers!
9. If you want disable system - set `eventsUpdate` in `config.lua` as `false`

### CODE REVIEW

**Comment by dudantas** [comment]
I don't understand, what is the use of this pull request?

**Comment by dex-89** [comment]
In my spare time I work on the event management system from the website level

**Comment by dudantas** [comment]
> In my spare time I work on the event management system from the website level

That's not what I meant.
It's just that I don't understand exactly what the use of this is. What is the gain in using events on the website instead of the server?

**Comment by dex-89** [comment]
> > In my spare time I work on the event management system from the website level
> 
> That's not what I meant.
> It's just that I don't understand exactly what the use of this is. What is the gain in using events on the website instead of the server?

It's just my idea. It does not need to be implemented

**Comment by dudantas** [comment]
Ok. Thanks for the contribution, but it doesn't interest us because it's bad to create dependency with the site.

**Pull request closed without merging**
