### PR TITLE
Add exotic spider cave

### PR DESCRIPTION
**Pull request by dudantas**
Add Exotic Spider Cave map
Entrance for exotic spider cave {x = 33918, y = 31471, z = 7}
Missing the cave top of the pirats in position {x = 33872, y = 31376, z = 8}
Co-authored by: @GodMapper

Added Pirat Scoundrel and Pirat Cutthroad
Added Exotic Cave Spider and Exotic Bat
Registered corpses in items.xml
Co-authored by: @marcosvf132

### CODE REVIEW

**Comment by dex-89** [comment]
Add #2133 to it, please

**Comment by dudantas** [comment]
> Add #2133 to it, please

Ok

**Review by dex-89 — APPROVED** [review]

**Comment by MajestyOTBR** [comment]
```
[Warning - Loot:setId] Unknown loot item "pirate coin".
[Warning - Loot:setId] Unknown loot item "pirat's tail".
[Warning - Loot:setId] Unknown loot item "shark fins".
[Warning - end] Monster: "Pirat Cutthroat" loot could not correctly be load.
[Warning - Loot:setId] Unknown loot item "pirate coin".
[Warning - Loot:setId] Unknown loot item "pirat's tail".
[Warning - end] Monster: "Pirat Scoundrel" loot could not correctly be load.
```
```
	<item id="40407" article="a" name="pirate coin">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="40" />
	</item>
	<item id="40408" article="a" name="pirat's tail">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="190" />
	</item>
	<item id="40409" article="a" name="shark fins">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="620" />
	</item>
```

**Comment by majestyotbr** [comment]
```
[Warning - Loot:setId] Unknown loot item "pirate coin".
[Warning - Loot:setId] Unknown loot item "pirat's tail".
[Warning - Loot:setId] Unknown loot item "shark fins".
[Warning - end] Monster: "Pirat Cutthroat" loot could not correctly be load.
[Warning - Loot:setId] Unknown loot item "pirate coin".
[Warning - Loot:setId] Unknown loot item "pirat's tail".
[Warning - end] Monster: "Pirat Scoundrel" loot could not correctly be load.
```
```
	<item id="40407" article="a" name="pirate coin">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="40" />
	</item>
	<item id="40408" article="a" name="pirat's tail">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="190" />
	</item>
	<item id="40409" name="shark fins">
		<attribute key="loottype" value="creatureproduct" />
		<attribute key="weight" value="620" />
	</item>
```

**Comment by dudantas** [comment]
> ```
> [Warning - Loot:setId] Unknown loot item "pirate coin".
> [Warning - Loot:setId] Unknown loot item "pirat's tail".
> [Warning - Loot:setId] Unknown loot item "shark fins".
> [Warning - end] Monster: "Pirat Cutthroat" loot could not correctly be load.
> [Warning - Loot:setId] Unknown loot item "pirate coin".
> [Warning - Loot:setId] Unknown loot item "pirat's tail".
> [Warning - end] Monster: "Pirat Scoundrel" loot could not correctly be load.
> ```
> 
> ```
> 	<item id="40407" article="a" name="pirate coin">
> 		<attribute key="loottype" value="creatureproduct" />
> 		<attribute key="weight" value="40" />
> 	</item>
> 	<item id="40408" article="a" name="pirat's tail">
> 		<attribute key="loottype" value="creatureproduct" />
> 		<attribute key="weight" value="190" />
> 	</item>
> 	<item id="40409" name="shark fins">
> 		<attribute key="loottype" value="creatureproduct" />
> 		<attribute key="weight" value="620" />
> 	</item>
> ```

Thanks

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
