### PR TITLE
[TFS] fix blessing/promotion lost percent on death

### PR DESCRIPTION
**Pull request by Costallat**
This pull request implements the formula as it is described on wiki.

Signed-off-by: Renato Foot <costallat@hotmail.com>

### CODE REVIEW

**Comment by Costallat** [comment]
Need in-game test

**Comment by cellss** [comment]
I found problems testing these changes...

- If I have all the blessings I lose nothing, 0 %

**Comment by majestyotbr** [comment]
Thanks for your contribution!

**Comment by cellss** [comment]
This is not a fix, it is a bug thing ... I commented this, this "fix" is not true and it has bugged the promotion system and these changes have been merged, I can't understand that ...

**Pull request merged**
