### PR TITLE
Protocol 12.60

### PR DESCRIPTION
**Pull request by dex-89**
Moved to #2084

### CODE REVIEW

**Comment by Alissonfgp** [comment]
- [x] Daily reward crash client - New Struct
	```
	msg.addByte(0xE2);
	msg.addByte(0); // bool near shrine
	msg.add<uint32_t>(0); //startup time
	msg.addByte(0); //day reward

	bool takenReward = true;
	msg.addByte(takenReward); // bool has taken reward
	if (takenReward) {
		msg.addString("You already take your reward.");
	}

	bool hasExpired = false;
	if (codeTimeExpired) {
		hasExpired = true;
	}

	msg.addByte(hasExpired);
	if (hasExpired) {
		msg.add<uint16_t>(8); //total jokers to recovery days
		msg.add<uint16_t>(0); //streak level
	} else {
		msg.add<uint16_t>(0); //streak level
	}

- [x] GOD (as invisible) will use command (/t, /a 2) or go up/down - client crash
Missing bytes: [https://github.com/SaiyansKing/optimized_forgottenserver/blob/19071768e1e65b9fa048350a7ab4a022498b45b8/src/protocolgame.cpp#L5022](url)

same as:
 `if (outfit.lookMount != 0) {
			playermsg.addByte(outfit.lookMountHead);
			playermsg.addByte(outfit.lookMountBody);
			playermsg.addByte(outfit.lookMountLegs);
			playermsg.addByte(outfit.lookMountFeet);
		}`

- [x] Player (normal and GOD) attack crature (spell or normal attack) (without summon)
Changed Impact Analyser: [https://github.com/SaiyansKing/optimized_forgottenserver/blob/master/src/protocolgame.cpp#L3807](url)
[](url)

**Comment by SaiyansKing** [comment]
> * [x]  Daily reward crash client - New Struct
>   ```
>    msg.addByte(0xE2);
>    msg.addByte(0); // bool near shrine
>    msg.add<uint32_t>(0); //startup time
>    msg.addByte(0); //day reward
>   
>    bool takenReward = true;
>    msg.addByte(takenReward); // bool has taken reward
>    if (takenReward) {
>    	msg.addString("You already take your reward.");
>    }
>   
>    bool hasExpired = false;
>    if (codeTimeExpired) {
>    	hasExpired = true;
>    }
>   
>    msg.addByte(hasExpired);
>    if (hasExpired) {
>    	msg.add<uint16_t>(8); //total jokers to recovery days
>    	msg.add<uint16_t>(0); //streak level
>    } else {
>    	msg.add<uint16_t>(0); //streak level
>    }

Actually it isn't bool and the correct struct is:
```
void ProtocolGame::parseOpenRewardWall(InputMessage& msg)
{
	bool shrine = msg.getBool();
	Uint32 startUpTime = msg.getU32();
	Uint8 dayStreakReward = msg.getU8();

	std::string rewardMessage;
	bool rewardTaken = msg.getBool();
	if(rewardTaken)
		rewardMessage = std::move(msg.getString());

	Uint32 haveVars = 0;
	Uint32 timeLeft = 0;
	Uint16 streakLevel = 0;
	Uint16 totalJokers = 0;
	Uint16 effectiveStreakLevel = 0;
	if(g_clientVersion >= 1260)
	{
		Uint8 identifier = msg.getU8();
		switch(identifier)
		{
			case 2:
			{
				timeLeft = msg.getU32();
				haveVars |= (1 << 0);
			}
			case 1:
			{
				totalJokers = msg.getU16();
				haveVars |= (1 << 1);
			}
			default:
			{
				streakLevel = msg.getU16();
				haveVars |= (1 << 2);
			}
		}
	}
	else
	{
		haveVars = (1 << 0) | (1 << 1) | (1 << 3);
		timeLeft = msg.getU32();
		streakLevel = msg.getU16();
		effectiveStreakLevel = msg.getU16();
	}
	g_game.processOpenRewardWall(shrine, startUpTime, dayStreakReward, rewardTaken, rewardMessage, haveVars, timeLeft, streakLevel, totalJokers, effectiveStreakLevel);
}
```

**Comment by dex-89** [comment]
> > * [x]   Daily reward crash client - New Struct
> >   ```
> >    msg.addByte(0xE2);
> >    msg.addByte(0); // bool near shrine
> >    msg.add<uint32_t>(0); //startup time
> >    msg.addByte(0); //day reward
> >   
> >    bool takenReward = true;
> >    msg.addByte(takenReward); // bool has taken reward
> >    if (takenReward) {
> >    	msg.addString("You already take your reward.");
> >    }
> >   
> >    bool hasExpired = false;
> >    if (codeTimeExpired) {
> >    	hasExpired = true;
> >    }
> >   
> >    msg.addByte(hasExpired);
> >    if (hasExpired) {
> >    	msg.add<uint16_t>(8); //total jokers to recovery days
> >    	msg.add<uint16_t>(0); //streak level
> >    } else {
> >    	msg.add<uint16_t>(0); //streak level
> >    }
> >   ```
> 
> Actually it isn't bool and the correct struct is:
> 
> ```
> void ProtocolGame::parseOpenRewardWall(InputMessage& msg)
> {
> 	bool shrine = msg.getBool();
> 	Uint32 startUpTime = msg.getU32();
> 	Uint8 dayStreakReward = msg.getU8();
> 
> 	std::string rewardMessage;
> 	bool rewardTaken = msg.getBool();
> 	if(rewardTaken)
> 		rewardMessage = std::move(msg.getString());
> 
> 	Uint32 haveVars = 0;
> 	Uint32 timeLeft = 0;
> 	Uint16 streakLevel = 0;
> 	Uint16 totalJokers = 0;
> 	Uint16 effectiveStreakLevel = 0;
> 	if(g_clientVersion >= 1260)
> 	{
> 		Uint8 identifier = msg.getU8();
> 		switch(identifier)
> 		{
> 			case 2:
> 			{
> 				timeLeft = msg.getU32();
> 				haveVars |= (1 << 0);
> 			}
> 			case 1:
> 			{
> 				totalJokers = msg.getU16();
> 				haveVars |= (1 << 1);
> 			}
> 			default:
> 			{
> 				streakLevel = msg.getU16();
> 				haveVars |= (1 << 2);
> 			}
> 		}
> 	}
> 	else
> 	{
> 		haveVars = (1 << 0) | (1 << 1) | (1 << 3);
> 		timeLeft = msg.getU32();
> 		streakLevel = msg.getU16();
> 		effectiveStreakLevel = msg.getU16();
> 	}
> 	g_game.processOpenRewardWall(shrine, startUpTime, dayStreakReward, rewardTaken, rewardMessage, haveVars, timeLeft, streakLevel, totalJokers, effectiveStreakLevel);
> }
> ```

@SaiyansKing Why don't you use it in your sources?

**Comment by dex-89** [comment]
>   ```
> * [x]  GOD (as invisible) will use command (/t, /a 2) or go up/down - client crash
>   Missing bytes: [https://github.com/SaiyansKing/optimized_forgottenserver/blob/19071768e1e65b9fa048350a7ab4a022498b45b8/src/protocolgame.cpp#L5022](url)
> 
> same as:
> `if (outfit.lookMount != 0) { playermsg.addByte(outfit.lookMountHead); playermsg.addByte(outfit.lookMountBody); playermsg.addByte(outfit.lookMountLegs); playermsg.addByte(outfit.lookMountFeet); }`
> 

@Alissonfgp I fixed impact and probably works

**Comment by SaiyansKing** [comment]
> > > * [x]    Daily reward crash client - New Struct
> > >   ```
> > >    msg.addByte(0xE2);
> > >    msg.addByte(0); // bool near shrine
> > >    msg.add<uint32_t>(0); //startup time
> > >    msg.addByte(0); //day reward
> > >   
> > >    bool takenReward = true;
> > >    msg.addByte(takenReward); // bool has taken reward
> > >    if (takenReward) {
> > >    	msg.addString("You already take your reward.");
> > >    }
> > >   
> > >    bool hasExpired = false;
> > >    if (codeTimeExpired) {
> > >    	hasExpired = true;
> > >    }
> > >   
> > >    msg.addByte(hasExpired);
> > >    if (hasExpired) {
> > >    	msg.add<uint16_t>(8); //total jokers to recovery days
> > >    	msg.add<uint16_t>(0); //streak level
> > >    } else {
> > >    	msg.add<uint16_t>(0); //streak level
> > >    }
> > >   ```
> > 
> > 
> > Actually it isn't bool and the correct struct is:
> > ```
> > void ProtocolGame::parseOpenRewardWall(InputMessage& msg)
> > {
> > 	bool shrine = msg.getBool();
> > 	Uint32 startUpTime = msg.getU32();
> > 	Uint8 dayStreakReward = msg.getU8();
> > 
> > 	std::string rewardMessage;
> > 	bool rewardTaken = msg.getBool();
> > 	if(rewardTaken)
> > 		rewardMessage = std::move(msg.getString());
> > 
> > 	Uint32 haveVars = 0;
> > 	Uint32 timeLeft = 0;
> > 	Uint16 streakLevel = 0;
> > 	Uint16 totalJokers = 0;
> > 	Uint16 effectiveStreakLevel = 0;
> > 	if(g_clientVersion >= 1260)
> > 	{
> > 		Uint8 identifier = msg.getU8();
> > 		switch(identifier)
> > 		{
> > 			case 2:
> > 			{
> > 				timeLeft = msg.getU32();
> > 				haveVars |= (1 << 0);
> > 			}
> > 			case 1:
> > 			{
> > 				totalJokers = msg.getU16();
> > 				haveVars |= (1 << 1);
> > 			}
> > 			default:
> > 			{
> > 				streakLevel = msg.getU16();
> > 				haveVars |= (1 << 2);
> > 			}
> > 		}
> > 	}
> > 	else
> > 	{
> > 		haveVars = (1 << 0) | (1 << 1) | (1 << 3);
> > 		timeLeft = msg.getU32();
> > 		streakLevel = msg.getU16();
> > 		effectiveStreakLevel = msg.getU16();
> > 	}
> > 	g_game.processOpenRewardWall(shrine, startUpTime, dayStreakReward, rewardTaken, rewardMessage, haveVars, timeLeft, streakLevel, totalJokers, effectiveStreakLevel);
> > }
> > ```
> 
> @SaiyansKing Why don't you use it in your sources?

What do you mean?
It is fragment from source code of my client and it gets updates differently from the server fork so the code will be on github when I'll make new update.
As for server it isn't there simply because I still haven't wrote daily rewards feature(if you ask me why I don't take code from this repository the answer is that I prefer to write it by myself and need to make it as feature that might have different code-path depending on version).

**Pull request closed without merging**
