### PR TITLE
Possible fix for the bug in the imbuement (#1281)

### PR DESCRIPTION
**Pull request by dudantas**
It needs to be tested, but the logic applies. If you move an item with the imbuement window open, it will be closed 

As it is already here (for do not crashes on the trade): https://github.com/opentibiabr/otservbr-global/blob/3fdc41f2e24ae3b0fa8505bff078aba0d7b87332/data/events/scripts/player.lua#L614

### CODE REVIEW

**Comment by dudantas** [comment]
Closing, we will correct it so that it is possible to imbue the equipped item without generating problems

**Comment by lurkgabriel** [comment]
da uma olhada aqui https://otland.net/threads/otx-imbuements-bug.271041/ parece que corrigiram

**Comment by dudantas** [comment]
Sim. Aí bloqueia o imbuement no equip.

Vamos tentar colocar para o imbuement funcionar no equip, como é no global, se não conseguirmos eu subo essa correção aí.

**Comment by perron5306987** [comment]
it didn't work for me
add the lines as it says here but it didn't work

[https://tamera-global.com/images/neutro.mp4](url)

**Comment by YohanAugusto** [comment]
@perron5306987 update your source and compile it again.

**Comment by perron5306987** [comment]
> @perron5306987 update your source and compile it again.

thank a lot, now work

**Pull request closed without merging**
