### PR TITLE
Rooted Condition

### PR DESCRIPTION
**Pull request by phacUFPE**
Condition to root creatures. Feature of rotten wasteland creatures (Rotten Golem and Branchy Crawler)

### CODE REVIEW

**Review by dex-89 — CHANGES_REQUESTED** [review]
- [x] fix indentations

Its element: Soul war quest

**Comment by dex-89** [comment]
https://tibia.fandom.com/wiki/Rooted

it add condition for 3 seconds?

**Comment by phacUFPE** [comment]
> * [x]  fix indentations
> 
> Its element: Soul war quest

i was using 4 spaces for indentation :|

**Comment by phacUFPE** [comment]
> https://tibia.fandom.com/wiki/Rooted
> 
> it add condition for 3 seconds?

You need to set the ticks in the add condition in the monster spell for example

condition = Condition(CONDITION_ROOTED)
condition:setParameter(CONDITION_PARAM_TICKS, 3000)

**Comment by dex-89** [comment]
> > https://tibia.fandom.com/wiki/Rooted
> > it add condition for 3 seconds?
> 
> You need to set the ticks in the add condition in the monster spell for example

Can you add spells and monster function?

 `Rotten Golem` and `Branchy Crawler`

**Comment by phacUFPE** [comment]
> > > https://tibia.fandom.com/wiki/Rooted
> > > it add condition for 3 seconds?
> > 
> > 
> > You need to set the ticks in the add condition in the monster spell for example
> 
> Can you add spells and monster function?
> 
> `Rotten Golem` and `Branchy Crawler`

SURE

**Comment by phacUFPE** [comment]
> > > > https://tibia.fandom.com/wiki/Rooted
> > > > it add condition for 3 seconds?
> > > 
> > > 
> > > You need to set the ticks in the add condition in the monster spell for example
> > 
> > 
> > Can you add spells and monster function?
> > `Rotten Golem` and `Branchy Crawler`
> 
> SURE

https://www.youtube.com/watch?v=L3tUwkr2jBE (1:38) <- JUST A REFERENCE FOR ME (I WILL MAKE THE SPELL LATER)

**Review by dex-89 — APPROVED** [review]
Tested & confirmed. Works. OK

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
