### PR TITLE
Protocol 12.64

### PR DESCRIPTION
**Pull request by dex-89**
**Protocol support: 12.64**
image
**Outfit: Rune Master (added in 12.62)**
image
**Podium of renown (added in 12.63)**
image
**3 new mounts (added in 12.64)**
**Void Watcher**
image
**Rune Watcher**
image
**Rift Watcher**
image

Credits: @SaiyansKing

### CODE REVIEW

**Comment by UReddington** [comment]
New mounts are called Void Watcher, Rune Watcher and Rift Watcher, you can check more about it on tibia.com

**Comment by methsoftgames** [comment]
thanks! 
it works perfectly, I added the code to client 10 branch and it does not allow me to change outfit / mount in client 10 and OTC

**Comment by majestyotbr** [comment]
Thanks for your contribution!

**Comment by majestyotbr** [comment]
Client 12.64 available for download in:
https://forums.otserv.com.br/index.php?/forums/topic/167933-otservbr-global-cliente-tibia-12/

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
