### PR TITLE
Update map soul war 2021 

### PR DESCRIPTION
**Pull request by 1dougweb**
The map has undergone some improvements and new hunting areas have also been added.
Check it out below:

- [x] Ebb and Flow
- [x] Furious Crater
- [x] Zarganash
- [x] Rotten Wasteland
- [x] Barren Drift
- [x] Rascacoon Island
- [x] The Wreckoning
- [x] Claustrophobic Inferno
- [x] Mirrored Nightmare (by @UReddington)
- [x] Supreme Cube Maze (by @eratsu)

Some corrections were also made on the island of Bounac and Dawnport .

### CODE REVIEW

**Comment by adrianomengue** [comment]
Holy moly! Thanks @xsparkx ASAP I will test everything.

> We need to #2334 finished so we can use your monsters without any problem and it may conflict with your PR because there are the same monsters on both PRS.

**Comment by 1dougweb** [comment]
@adrianomengue the changes to a mentioned PR #2334 were made to move forward.

**Comment by adrianomengue** [comment]
> @adrianomengue the changes to a mentioned PR #2334 were made to move forward.

That sounds good! Great job dude.

**Comment by Bipbop69** [comment]
I didn't find the part  The Wreckoning

**Review by patrickjmeurer — APPROVED** [review]
everything is ok

**Review by Pexeiroo — APPROVED** [review]

**Comment by oualid6496** [comment]
Nice checked the maps out seems to be alright except for The Wreckoning doesn't seem to be included or the 2 unique monsters that are supposed to be there Pirat Bombardier & Pirat Mate

**Review by dudantas — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Review by Costallat — APPROVED** [review]

**Pull request merged**
