### PR TITLE
Add wrap to house items

### PR DESCRIPTION
**Pull request by hyresu**
Please test it and give your feedback!

TODO:
- [ ] Add wrapable items to npcs instead of kit

### CODE REVIEW

**Review by dex-89 — APPROVED** [review]

**Comment by Tazer89** [comment]
Tested and works great.

**Comment by phacUFPE** [comment]
Tested and works!

**Review by dex-89 — APPROVED** [review]

**Comment by phacUFPE** [comment]
> Please test it and give your feedback!
> 
> TODO:
> 
> * [ ]  Add wrapable items to npcs instead of kit

Im working in this system to allow the npc to sell the new wrapable items

**Review by adrianomengue — APPROVED** [review]
Tested and works fine.

**Review by adrianomengue — APPROVED** [review]

**Comment by Bipbop69** [comment]
@hyresu 
ave any idea how we can do this 'Add wrapable items to npcs instead of kit'


was trying to do using the kits that exist but it doesn't work

**Comment by majestyotbr** [comment]
PR closed due to inactivity.

**Pull request closed without merging**
