### PR TITLE
fix: a lot of map issues

### LINKED ISSUE #1465: Access to Misguided (Cults of Tibia) - Water vortex without teleport coordinates
**Describe the bug**

Water vortex without teleport coordinates that takes access to Misguided (Cults of Tibia).

**To Reproduce**
to go:
water vortex Position: 32629, 32264, 8    ---> **teleport to**: 32499, 32331, 8.
to back:
water vortex Position:  Position: 32499, 32330, 8   --->  **teleport to**: 32630, 32264, 8.

**Expected behavior**
Access to Misguided (Cults of Tibia)

### PR DESCRIPTION
**Pull request by gpedro**
resolves hellgrip stone
resolves issavi bridge #1394 
resolves darashia depot #1287 
resolves deepling shortcut teleport #1156
resolves kazordoon river fish spawns #1339 
resolves kazordoon entrance skeleton spawn #1338 
resolves kazordoon missing daily spawn floor #1337 
resolves the frontier quest stairs #1393
resolves water vortex, access to misguided #1465 
fixed PZ in cobra bastion boat
fixed Rope Spots
fixed locked doors: library quest, yalahar necromancer, thais (alai flats, library), 
fixed demon respawn in ferumbras ascending

### CODE REVIEW

**Comment by nickolasdeluca** [comment]
There is an issue on the darashia house depot, inside the Eastern Darashia Guildhall there is an sqm that belongs to the Western Darashia Guildhall. The problematic sqm is at {x = 33235 y = 32473 z = 8}

The issavi map bug is almost fixed, but when you walk up on the bridge there is no way to get down. Also, if you're looking from the ground, the bridge still appears to have no walkable path.

**Comment by gpedro** [comment]
@nickolasdeluca can you check again? <3

**Comment by nickolasdeluca** [comment]
> @nickolasdeluca can you check again? <3

both issues appear to be fixed, grats.

**Review by dudantas — APPROVED** [review]
lgtm

**Pull request merged**
