### PR TITLE
[feat] colored loot message

### PR DESCRIPTION
**Pull request by vagnerkuntz**

### CODE REVIEW

**Comment by gpedro** [comment]
i know the implementation is correct, but which version does it work from?

**Comment by vagnerkuntz** [comment]
@gpedro Tested only in version 12

**Comment by gpedro** [comment]
@vagnerkuntz `12.??` which minor version?

**Comment by vagnerkuntz** [comment]
To be more specific, it is the same as there are repository tools: 
https://github.com/opentibiabr/tools/blob/master/Tibia%20Client%2012.rar

it is possible that it works with some previous versions / minor versions.
I can't confirm it, I'm still at work.

**Comment by gpedro** [comment]
image
image

**Comment by aurelion5670** [comment]
Version 12.007695, it isn't working either here, also it needs to have a check on the clientversion to avoid the issue that gpedro is having now

**Comment by FakeShinoda** [comment]
This feature has been implemented in version "12.00.7695", the problem is the conflict within these 2 contenctDescriptions functions lua/src.

Otherwise if you close this PR, i can make a another with this function working (only for 12+)

**Pull request closed without merging**
