### PR TITLE
Protocol 12.60

### PR DESCRIPTION
**Pull request by dex-89**
**Known bugs:**
= **empty list** =

image
image
image
image
image

**Thanks for:** @SaiyansKing, @dudantas, @marcosvf132, @FakeShinoda

### CODE REVIEW

**Comment by bosmak** [comment]
Hi, @dex-89. I have been interested in running a tibia on protocol 12.6 locally.
Given that I saw your earlier Pull Request #2038 and went to test it, I bought everything up (using docker for simplicity), made some fixes to the login.py, and was able to log in and get the character list but every single time that I try to log into one of the characters my game closes.

I later saw this new pull request and did the same with this code and had the same issue.

I had tested with the latest 10.6 (10.60.10503) clients on both Linux and Windows and got the same behavior.
Then I tried on the Windows 10.5 client provided on the README of this project and still got the same behavior.

On the server-side, I couldn't find anything wrong with the logs.
```
A server developed by OTServBR, Mark Samman and The Forgotten Server Developers
Visit our forum for updates, support, and resources: https://otserv.com.br/ and https://forums.otserv.com.br

>> Client Version: 12.60
>> Loading config
>> Establishing database connection... MySQL 5.7.32
>> Running database manager
> Updating database to version 1 (sample players)
> Database has been updated to version 1.
> Updating database to version 2 (hireling)
> Database has been updated to version 2.
> Updating database to version 3 (account refactor)
> Database has been updated to version 3.
> Updating database to version 4 (prey tick)
> Database has been updated to version 4.
> Updating database to version 5 (boosted creature)
> Database has been updated to version 5.
> Updating database to version 6 (quickloot)
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD `quickloot_fallback` TINYINT DEFAULT 0
Message: Duplicate column name 'quickloot_fallback'
> Database has been updated to version 6.
> Updating database to version 7 (Stash supply)
> Database has been updated to version 7.
> Updating database to version 8 (recruiter system)
> Database has been updated to version 8.
> Updating database to version 9 (Bestiary cpp)
> Database has been updated to version 9.
> Updating database to version 10 (Mount Colors and familiars)
> Database has been updated to version 10.
> No tables were optimized
>> Loading vocations
>> Loading items
>> Loading event scheduler
>> Loading script systems
>> Using LuaJIT 2.1.0-beta3
>> Loading lua libs
>> Loading lua scripts
>> Loading lua monsters
>> Loading outfits
>> Loading familiars
>> Boosted creature: Crazed Winter Rearguard
>> Checking world type... PVP
>> Loading map
> Map size: 34143x33812
> Map loading time: 9.819 seconds
> Loaded spawns in: 10.258 seconds
>> Initializing gamestate
>> Fury Gate will be active in edron today
>> Loading map attributes
> Loaded 954 npcs and spawned 73166 monsters
> Loaded 23 towns with 985 houses in total
> Loaded 9 signs in the map
> Loaded 60 books in the map
> Loaded 2 documents in the map
> Loaded all actions in the map
> Loaded all uniques in the map
>> Loading custom maps
> Loaded otservbr-custom map
>> Yasir: libertybay. 
>> Loaded all modules, server starting up...
> Warning: OTServBR - Global has been executed as root user, please consider running it as a normal user.
>> OTServBR-Global Server Online!

> Map size: 34143x33812
> Map loading time: 0.102 seconds
> Map size: 32319x32904
> Map loading time: 0.001 seconds
GOD has logged in.
> Loaded otservbr-custom spawn
GOD has logged out.
GOD has logged in.
GOD has logged out.
GOD has logged in.
GOD has logged out.
>> Starting Sunset... Current light is 243 and it's 17:24 Tibian Time.
> NPC Ghostly Wolf added!
> NPC Talila added!
> NPC Valindara removed!
>> Starting Night... Current light is 40 and it's 19:20 Tibian Time.
Druid Sample has logged in.
Druid Sample has logged out.
Druid Sample has logged in.
GOD has logged in.
Druid Sample has logged out.
GOD has logged out.
Druid Sample has logged in.
GOD has logged in.
Druid Sample has logged out.
> Broadcasted message: "The dragons of the Dragonblaze Mountains have descended to Zao to protect the lizardkin!".
GOD has logged out.
```

I'm not sure how to fetch some logs on the Windows client, but I usually get this error when I try on Linux.
``` 
[ 2020-12-17 21:20:08,357 ] Asset loading complete
[ 2020-12-17 21:20:19,398 ] BattlEye: "Initialized (v1.246)"
[ 2020-12-17 21:20:19,432 ] Request connection to gameserver  "tcp://172.30.0.10:7172"  (unprotected:  "tcp://172.30.0.10:7172" )  requested (Charakter "Sorcerer Sample" )
[ 2020-12-17 21:20:19,437 ] Request connection to gameserver  "tcp://172.30.0.10:7172" "OTServBR-Global"
[ 2020-12-17 21:20:19,437 ] Connected to gameserver  "tcp://172.30.0.10:7172" "OTServBR-Global"
terminate called after throwing an instance of 'tibia::protocol::TUnknownGameserverException'
  what():  Unknown Gameserver Message: 0
Aborted (core dumped)
``` 

Let me know If I can help you with anything to get this forward!

---

Sorry forgot to add this, I know this PR is a draft, but I'm keen to help you test it out if needed :)

**Comment by majestyotbr** [comment]
@bosmak You need the client 12.60 to log in, it's not ready for download yet. I will update the topic later.

**Comment by bosmak** [comment]
> @bosmak You need the client 12.60 to log in, it's not ready for download yet. I will update the topic later.

As I'm running Linux as my OS, I patched my own 12.60 client (I also patched and executed the 12.6 client on Windows as well, thinking it could be some issue with the Linux client). Is the procedure to patch different on the 12.60?

I used the 10.60.10503 version on both.

Anyway, Thanks I will wait for you to update the client.

**Comment by dex-89** [comment]
> > @bosmak You need the client 12.60 to log in, it's not ready for download yet. I will update the topic later.
> 
> As I'm running Linux as my OS, I patched my own 12.60 client (I also patched and executed the 12.6 client on Windows as well, thinking it could be some issue with the Linux client). Is the procedure to patch different on the 12.60?
> 
> I used the 10.60.10503 version on both.
> 
> Anyway, Thanks I will wait for you to update the client.

Currently, my PR does not support the Linux version of the client. I have some idea how to fix it, but I need to check it to make sure everything is working properly. Details soon

**Comment by dex-89** [comment]
@bosmak are you in Discord? Can you write to me privately?

I think, that at Linux we can't disable battleye

**Comment by majestyotbr** [comment]
Thanks for your contribution!

**Comment by majestyotbr** [comment]
Client 12.60.10503 available for download in:
https://forums.otserv.com.br/index.php?/forums/topic/167933-otservbr-global-cliente-tibia-12/

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
