### PR TITLE
minor changes to default values and settings

### PR DESCRIPTION
**Pull request by thatmichaelguy**
Personal opinion of how the base distribution should be.
- Lowered skill & magic rate in config.lua
- Disabled skill stages in skillstages.xml

### CODE REVIEW

**Comment by oualid6496** [comment]
Why should this be merged this differs from person to person if this gets merged maybe tomorrow someone that prefers 100x will make a new pr for that. Won't that just go on and on?

**Comment by thatmichaelguy** [comment]
I understand that rates are subjective, I do suggest we establish a default configuration that would play well "straight out of the box". 1x exp, 50x skills & 25x magic will not.

As for disabling skill stages - keeping it disabled by default seems logical to me. It'll just confuse new users if it is enabled by default.

**Comment by Raphaellb** [comment]
I think we should leave it the way it is. this is trivial, and each person can modify to their liking.

**Comment by majestyotbr** [comment]
I think this is a personal thing and each person can modify the options to their liking.
Anyway, thanks for the suggestion.

**Pull request closed without merging**
