### PR TITLE
fix: resolves #1422

### LINKED ISSUE #1422: Summons and monsters can move "immovable" items
monsters and summons  can move immovable items with actionid:100

1) Create a movable item, chest, parcel, plant , etc
2) Set actionid:100 (makes the item immovable)
3) create a monster or summon with /s command or utevo res spell
4) make the summon walk on top of the items
5) this happens with monsters  who have flag canpushitems="1" in xml)

[click to see the gif ](https://gyazo.com/3c5e292489c70394756724e7766594a2)

Expected behavior
the summon or monsters  should walk over the item without moving it, in the case of the plant that can' t be walked on,  the summon or monster should dodge it without moving the plant.

quest chest (or item with uniqueid) summons walk over the item without moving it
[click to see the gif](https://gyazo.com/fe372aa63d61e5964c39c2fee1d42329)

### PR DESCRIPTION
**Pull request by gpedro**

### CODE REVIEW

**Comment by civic23** [comment]
worked well with "walkable items", but with items that can't be walked on the summon passes over them. 
the summon should dodge them instead of walking over them.
[click to see the gif](https://gyazo.com/bb72b4bea0ead7537e0d4c2471fc3643)

**Comment by civic23** [comment]
I think it's another bug, if you set a uniqueid to an item that's "not walkable", the item becomes "walkable" for summons and monsters 

[click to see the gif](https://gyazo.com/a714ed24dbb293be9e3451f49da7af02)

**Comment by gpedro** [comment]
@keloke1 this looks like a bug from item otb definition
can you create a new issue for that?

**Comment by civic23** [comment]
@gpedro https://github.com/opentibiabr/otservbr-global/issues/1453

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
