### PR TITLE
Some Fix

### PR DESCRIPTION
**Pull request by Sargitarium**
*Fix soil guardian/crystal warlord/makeshift warrior debug when using

When use addon item debug client
*New doors added

Missing doors
*Fix Oberon Lever bug

Script dont work fine, time, check, kick
*Fix Ferumbras Ascendant lever bug

Script dont work fine, time, check, kick
*Fix error on imbuing equiped item

If you imbui critical with equiped item, you got 65k% critical
*Fix some monsters loots, xp, etc...

### CODE REVIEW

**Comment by Sargitarium** [comment]
*Fix soil guardian/crystal warlord/makeshift warrior debug when using
- When use addon item debug client

*New doors added
- Missing doors

*Fix Oberon Lever bug
- Script dont work fine, time, check, kick

*Fix Ferumbras Ascendant lever bug
- Script dont work fine, time, check, kick

*Fix error on imbuing equiped item
- If you imbui critical with equiped item, you got 65k% critical

*Fix some monsters loots, xp, etc...

**Comment by Lycanzito** [comment]
> *Fix error on imbuing equiped item
> 
> * If you imbui critical with equiped item, you got 65k% critical

I dindt test it, but 
*Fix error on imbuing equiped item

If you imbui critical with equiped item, you got 65k% critical

so, it is working all the others imbuements? such has leechs, etc? the time of the itens are decaying?

**Comment by Sargitarium** [comment]
> > *Fix error on imbuing equiped item
> > 
> > * If you imbui critical with equiped item, you got 65k% critical
> 
> I dindt test it, but
> *Fix error on imbuing equiped item
> 
> If you imbui critical with equiped item, you got 65k% critical
> 
> so, it is working all the others imbuements? such has leechs, etc? the time of the itens are decaying?

All imbui time normal... 
See player.....

14:12 Batmanzin [384]: 14:11 You see a Test Druid Cape (Arm:20, magic level +5, protection physical +5%, energy +5%, earth +5%, fire +5%, ice +5%, holy +5%, death +5%). It can only be wielded properly by druids. Imbuements: (Powerful Vampirism 11:11h, Powerful Hide Dragon 14:05h). It weighs 31.00 oz.

14:12 Batmanzin [384]: 14:11 You see an Test Rod (critical hit chance +5%, magic level +5). It can only be wielded properly by druids. Imbuements: (Powerful Strike 17:36h, Powerful Void 17:36h, Powerful Epiphany 17:36h). It weighs 29.00 oz.

**Comment by majestyotbr** [comment]
Anyone to test?

**Comment by Lycanzito** [comment]
Então.. Pelo que eu entendi, a correção proposta, seria voltar ao que era antes, não podendo imbuir um item que estivesse equipado ao jogador,

se for isso, de fato vai funcionar.

Eu pensei que a correção era para que USANDO um item, o jogador poderia fazer o imbui nele, e isso não ocasionaria os erros citados a cima ^.-
igual é no global;

**Comment by dudantas** [comment]
Resolvemos voltar ao que era. Para fazer como é no global tem que refazer o imbuement.

**Review by eltonbrayner — APPROVED** [review]

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Pull request merged**
