### PR TITLE
Enhancement: Supply stash update and fixes.

### LINKED ISSUE #2346: BUG: Stash
` -  Thread 1 (Thread 0x7ffff7fd82c0 (LWP 30648)):
 -  #0  0x00007f0a7f807d05 in ?? ()
 -  No symbol table info available.
 -  #1  0x0000555555756717 in Player::postRemoveNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
 -  No symbol table info available.
 -  #2  0x00005555555d3887 in Game::internalRemoveItem(Item*, int, bool, unsigned int) ()
 -  No symbol table info available.
 -  #3  0x00005555555d4c59 in Game::internalRemoveItems(std::vector<Item*, std::allocator<Item*> >, unsigned int, bool) ()
 -  No symbol table info available.
 -  #4  0x0000555555755e99 in Player::removeItemOfType(unsigned short, unsigned int, int, bool) const ()
 -  No symbol table info available.
 -  #5  0x000055555575ac6a in Player::stowContainer(Item*, unsigned int, bool) ()
 -  No symbol table info available.
 -  #6  0x000055555577d65e in ProtocolGame::parseStashWithdraw(NetworkMessage&) ()
 -  No symbol table info available.
 -  #7  0x000055555577db14 in ProtocolGame::parsePacket(NetworkMessage&) ()
 -  No symbol table info available.
 -  #8  0x0000555555821e57 in Connection::parsePacket(boost::system::error_code const&) ()
 -  No symbol table info available.
 -  #9  0x0000555555823a1e in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >::operator()(boost::system::error_code const&, unsigned long, int) ()
 -  No symbol table info available.
 -  #10 0x0000555555823e73 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
 -  No symbol table info available.
 -  #11 0x00005555557a5281 in ServiceManager::run() ()
 -  No symbol table info available.
 -  #12 0x000055555558d12b in main ()
 -  No symbol table info available.
 -  Saving server...
 -  > Saved house items in: 1.296 seconds
 -  $1 = 1`

### PR DESCRIPTION
**Pull request by marcosvf132**
Optimizing the supply stash:
- Faster stash loading.
- Improving item saving system.
- Add missing `feature` that give oportunitty to use the imbue shrine and link it to the stash supply.

Resolves #2346
```
The Supply Stash is directly connected to all imbuing shrines. This means that you no longer have to carry around the
materials you need for your imbuements. They will be taken directly from your Supply Stash if you want to imbue your 
equipment at one of the shrines.
```
[Info](https://www.tibia.com/news/?subtopic=newsarchive&id=4637)

### CODE REVIEW

**Review by Bipbop69 — APPROVED** [review]

**Review by gerotib — APPROVED** [review]
I see no issues after some tests

**Review by dex-89 — APPROVED** [review]

**Comment by methx** [comment]
I have this error in console

2021-02-05 21:47:06 -  [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)
2021-02-05 21:47:06 -  Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1
2021-02-05 21:47:06 -  [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 678, 9)
2021-02-05 21:47:06 -  Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1
2021-02-05 21:47:06 -  [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 678, 9)INSE
2021-02-05 21:47:06 -  Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1t

**Comment by marcosvf132** [comment]
> I have this error in console
> 
> 2021-02-05 21:47:06 - [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)
> 2021-02-05 21:47:06 - Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1
> 2021-02-05 21:47:06 - [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 678, 9)
> 2021-02-05 21:47:06 - Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1
> 2021-02-05 21:47:06 - [Error - mysql_real_query] Query: INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 239, 1)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281, 3)INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 678, 9)INSE
> 2021-02-05 21:47:06 - Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `player_stash` (`player_id`,`item_id`,`item_count`) VALUES (410, 281' at line 1t

This PR is just a update to the OTBR supply stash, are you using the updated repository? this PR is not the entire supply stash, but just a complement. I'm running some tests and this error is not happening here. I will run more tests and wait for more people so i can have more feedback about it.

**Comment by dex-89** [comment]
Works ok

**Comment by gerotib** [comment]
@marcosvf132 Mysql error is an actual issue, if you have more than 1 item in your stash and then logout it won't save correctly.

**Comment by marcosvf132** [comment]
> @marcosvf132 Mysql error is an actual issue, if you have more than 1 item in your stash and then logout it won't save correctly.

Can you test it again? fixed the sql error.

**Comment by gerotib** [comment]
@marcosvf132 Yeah its fine now

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
