### PR TITLE
Improving destroy

### PR DESCRIPTION
**Pull request by andersonfaaria**
With this PR:
- Fixed bug for target nil untreated
- Destroy chance based on weapon attack
- Fixed bug with destroyable items with fluids not leaking (cipsoft haven't fixed this one yet xD)

### CODE REVIEW

**Comment by gerotib** [comment]
Tested, everything seems fine.

**Comment by andersonfaaria** [comment]
A few unit tests that I would recommend for the destroy:

1. Right click weapon and click it again (destroy the weapon)
2. Right click and selecting floor
3. Right click and destroying furniture
4. Right click and destroying container furnitures with items inside
5. Right click and destroying spider nets
6. Right click and destroying a casket (furniture) with any fluid and see if the fluid leaks.

Attention to the correct order of items, the destroyed furniture needs to be in a position that makes logical sense.

If all the unit tests pass, please let me know so I can merge

**Comment by gerotib** [comment]
Heres a list with answers:
1. "sorry, not possible"
2. "you cannot use this object"
3. destroyed correctly
4. inside items getting "thrown" on ground after destroying
5. nets getting destroyed correctly
6. large amphora filled with water/blood leaks correct fluid and decay as it should

No errors in logs.

**Comment by andersonfaaria** [comment]
@gerotib thank you, it seems that is working as intended. I'll merge and so we can continue testing in regression

**Pull request merged**
