### PR TITLE
Daily Reward Support for login.php

### PR DESCRIPTION
**Pull request by dex-89**
For website [login.php]
['dailyrewardstate'] support -> database players -> isreward

is set to 1
after collecting the daily reward set to 0

### CODE REVIEW

**Review by majestyotbr — APPROVED** [review]

**Comment by CarlosAlexanderGonzalez** [comment]
> 
> 
> For website [login.php]
> ['dailyrewardstate'] support -> database players -> isreward
> 
> is set to 1
> after collecting the daily reward set to 0

bro, I have to add that line in my login.php?

**Comment by CarlosAlexanderGonzalez** [comment]
Hello bro,
i have this warning on compiling is normal?

1>D:\otservbr-global-develop\src\housetile.h(52,1): warning C4266: 'void Tile::internalAddThing(Thing *)': no override available for virtual member function from base 'Tile'; function is hidden (compiling source file ..\src\protocollogin.cpp)
1>D:\otservbr-global-develop\src\tile.h(271): message : see declaration of 'Tile::internalAddThing' (compiling source file ..\src\protocollogin.cpp)
1>D:\otservbr-global-develop\src\tile.h(154): message : see declaration of 'Tile' (compiling source file ..\src\protocollogin.cpp)

u have an idea of how fix this warning?

**Comment by CarlosAlexanderGonzalez** [comment]
> 
> 
> For website [login.php]
> ['dailyrewardstate'] support -> database players -> isreward
> 
> is set to 1
> after collecting the daily reward set to 0

my login.php is for the version 12.51 of tibia, u have one login for 12.60?

**Comment by Costallat** [comment]
@CarlosAlexanderGonzalez stop asking things on this PR, here is not the place to ask for support, use discord for that
https://discord.gg/3NxYnyV

**Comment by CarlosAlexanderGonzalez** [comment]
> 
> 
> @CarlosAlexanderGonzalez stop asking things on this PR, here is not the place to ask for support, use discord for that
> https://discord.gg/3NxYnyV

I'm sorry I had no idea, in discord can I ask for chat support? I speak Spanish

**Pull request merged**
