### PR TITLE
Fix familiar blocking login #2550

### PR DESCRIPTION
**Pull request by lgrossi**
Patch fix to do not block your login when you try to login and there is no room to summon the familiar.
https://github.com/opentibiabr/otservbr-global/issues/2550

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by michu940107** [comment]
now console didnt see an error, but still cants login

**Review by mattyx14 — APPROVED** [review]

**Comment by UReddington** [comment]
The login lines that you added need to be returned to true

**Comment by lgrossi** [comment]
> now console didnt see an error, but still cants login

Can you please test again?

**Review by majestyotbr — APPROVED** [review]

**Comment by michu940107** [comment]
> > now console didnt see an error, but still cants login
> 
> Can you please test again?

Now it works, i can relog with familiar!! :) Thanks, but console see an error in file, even when its working good.
**data/scripts/creaturescripts/others/familiars.lua:116: 'end' expected (to close 'function' at line 35) near '<eof>'**

**Comment by majestyotbr** [comment]
@michu940107 You probably didn't copied the code correctly. I tested and does not have error on distro.

**Comment by michu940107** [comment]
> @michu940107 You probably didn't copied the code correctly. I tested and does not have error on distro.

forgot about one 'end' now it works correctly thanks! :) But meybe u know why my familiar isnt walking in PZ? Hes standing... not moving

**Comment by majestyotbr** [comment]
> > @michu940107 You probably didn't copied the code correctly. I tested and does not have error on distro.
> 
> forgot about one 'end' now it works correctly thanks! :) But meybe u know why my familiar isnt walking in PZ? Hes standing... not moving

It's working fine here.

**Comment by michu940107** [comment]
> > > @michu940107 You probably didn't copied the code correctly. I tested and does not have error on distro.
> > 
> > 
> > forgot about one 'end' now it works correctly thanks! :) But meybe u know why my familiar isnt walking in PZ? Hes standing... not moving
> 
> It's working fine here.

mine not, it can be beazocuse i change summonable familiar to false? // edit : yes, changed to oryginal and it works, but magic prof can summon it

**Comment by majestyotbr** [comment]
> 
> 
> > > > @michu940107 You probably didn't copied the code correctly. I tested and does not have error on distro.
> > > 
> > > 
> > > forgot about one 'end' now it works correctly thanks! :) But meybe u know why my familiar isnt walking in PZ? Hes standing... not moving
> > 
> > 
> > It's working fine here.
> 
> mine not, it can be beazocuse i change summonable familiar to false? // edit : yes, changed to oryginal and it works, but magic prof can summon it

Mages can not summon familiar with "summon creature" spell. 
The familiars have your own spells to summon:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/spells/spells.xml#L4-#L19

**Pull request merged**
