### PR TITLE
Fix Teleport Trashing

### LINKED ISSUE #2637: BUG: Teleport Trashing

### PR DESCRIPTION
**Pull request by travisani**
Ref: Issue #2637

### CODE REVIEW

**Comment by majestyotbr** [comment]
And this?
https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L44-#L45

**Comment by travisani** [comment]
> And this?
> https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L44-#L45

its ok here.

**Comment by majestyotbr** [comment]
Tested and does not work. If you find the solution, you can reopen this pull request and modify the code.

**Comment by travisani** [comment]
okay, não encontro a solução nem no otland.

**Pull request closed without merging**
