### PR TITLE
tfs: apply patch that fixes the reload problem on Linux

### PR DESCRIPTION
**Pull request by Costallat**
Issue: #244 

- this fixes the crash bug with /reload creaturescripts on Linux

### CODE REVIEW

**Comment by Znote** [comment]
Only on Linux? Is there any errors in Windows?

**Comment by Costallat** [comment]
On Windows it works, but the patch should not affect that, it should work on both OS

**Comment by Raphaellb** [comment]
tested using linux mint 18 with no problems.

**Comment by miezaF** [comment]
relaod em linux 16.04 18.04 14.04 funcionando perfeitamente

**Pull request merged**
