### PR TITLE
Fix Letters

### LINKED ISSUE #2263: BUG: the writing is erased on letters
the players receive the empty  letters

### PR DESCRIPTION
**Pull request by hyresu**
Fix for #2263

### CODE REVIEW

**Review by dex-89 — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
Hello
When letters are sent they arrive empty, what is written is erased.

It is solved by adding a few lines in game.cpp.

could you check this pull request #2266

**Comment by hyresu** [comment]
@CarlosAlexanderGonzalez try with a fresh mailbox.cpp, as I made more changes

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
> 
> 
> @CarlosAlexanderGonzalez try with a fresh mailbox.cpp, as I made more changes

I already did it and it didn't work, everything remains the same.
I just added those lines in game.cpp and it solved. but they deleted my pull request

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@hyresu 
I already did it and it didn't work, everything remains the same.
I just added those lines in game.cpp and it solved.

**Comment by hyresu** [comment]
@CarlosAlexanderGonzalez it is working for me, could you remove the changes on game.cpp and use a fresh mailbox.cpp from this branch?

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@hyresu I removed the changes in game.cpp and add all this full mailbox.cpp but it doesn't work

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@hyresu ahora agregare denuevo las lineas en game.cpp y vere si funciona dame 2 min

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@hyresu Now add the lines in game.cpp again and I'll see if it works, give me 2 min

**Comment by hyresu** [comment]
@CarlosAlexanderGonzalez no uses las lineas del game.cpp, usa el mailbox que esta en este pull request, porque hice 2 cambios, el primero (el que paso) tu dijiste que no funcionaba, y es cierto, pero este pr tiene un cambio adicional para hacer que los cambios de mailbox.cpp funcionen

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@hyresu el cambio de newitem?
eso es lo que estoy usando.
mira asi me sale con este pr y sin las lineas de game.cpp
imagen

y ahora mira con este pr y los cambios de game.cpp ahora sale haci
imagen

**Comment by hyresu** [comment]
@CarlosAlexanderGonzalez entra un poco a discord  y lo resolvemos allá

**Pull request merged**
