### PR TITLE
[TFS]: Fix getLootRandom, fix use of randomseed

### PR DESCRIPTION
**Pull request by Costallat**
Solution provided by iryont

- Removed randomseed from startup.lua
- Removed randomseed from getLootRandom function of global.lua
- Added randomseed to line 1 of global.lua

Signed-off-by: Renato Foot Guimarães Costallat <costallat@hotmail.com>

### CODE REVIEW

**Comment by Costallat** [comment]
Need someone to test, a good example of how to test:

https://github.com/otland/forgottenserver/issues/2632

**Comment by Costallat** [comment]
Need someone to test, tks!

**Comment by Costallat** [comment]
Anyone to test this? 

If needed I can start a server for that!

Tks!

**Comment by gerotib** [comment]
I killed 1000 rotworms and 500 heros = loot count and spread seems to work fine. Heres rots image:
rots

**Pull request merged**
