### PR TITLE
Fixed house prices (missing in #2108)

### PR DESCRIPTION
**Pull request by dex-89**

### CODE REVIEW

**Comment by dudantas** [comment]
You need to change the houses directly in the otbm file, only XML is useless (it only serves to store information.)

**Comment by dex-89** [comment]
@dudantas you finished edit map?

**Comment by dudantas** [comment]
> @dudantas you finished edit map?

Yes Sir

**Comment by dudantas** [comment]
Added to https://github.com/opentibiabr/otservbr-global/pull/2261

**Pull request closed without merging**
