### PR TITLE
Summon corrections

### PR DESCRIPTION
**Pull request by gerotib**
Some fixes for 200+ summons:
- correct names of spells (used in spellbook lists)
- cooldowns corrected according to tibiawiki "Group CD 2 seconds"
- fixed pet summon spells (based on wikis + videos)
- added summon challenge spell with greater radius than regualr challenge
- setting correct speed of summon after relog

I tested everything myself, but would be cool if someone else does too.

I dont know if thats the best approach to fix that, but ive also added check for pet summons in haste spells, so theyre also affected with speed condition. I tested that with command that prints player and pet current speed, and it stayed the same.

### CODE REVIEW

**Review by dudantas — APPROVED** [review]

**Comment by dudantas** [comment]
Greetings! 

Don't you want to take advantage of this pull to correct the summons' life regeneration (spells)?

**Comment by gerotib** [comment]
@dudantas well ill make some more fixes on them later (fix exeta res and correct rest of spells)

**Comment by andersonfaaria** [comment]
@gerotib 

Please redo the haste spells like this:

```lua
local summons = creature:getSummons()
if summons and type(summons) == 'table' and #summons > 0 then
	for i = 1, #summons do
		local summon = summons[i]
		local summon_t = summon:getType()
		if summon_t and summon_t:isPet() then
			local deltaSpeed = math.max(creature:getBaseSpeed() - summon:getBaseSpeed(), 0)
			local PetSpeed = ((summon:getBaseSpeed() + deltaSpeed) * 0.9) - 72
			local PetHaste = createConditionObject(CONDITION_HASTE)
			setConditionParam(PetHaste, CONDITION_PARAM_TICKS, 5000)
			setConditionParam(PetHaste, CONDITION_PARAM_SPEED, PetSpeed)
			summon:addCondition(PetHaste)
		end
	end
end
```

**Review by dudantas — APPROVED** [review]

**Comment by dudantas** [comment]
Thanks for your contribution!

**Pull request merged**
