### PR TITLE
Definitive fix for the bugs on the keys doors.

### PR DESCRIPTION
**Pull request by dudantas**
Definitive fix for the bugs on the doors.
Changed the ids on the map to the correct ones.

It's revert the pr #909

Thanks for the @empireot.

### CODE REVIEW

**Comment by miguelstrungs** [comment]
the doors are still buggy.

**Comment by miguelstrungs** [comment]
issavi's doors are buggy, I tested it now!

**Comment by dudantas** [comment]
> the doors are still buggy.

No, I tested it and it's ok.

**Comment by dudantas** [comment]
> issavi's doors are buggy, I tested it now!

Issavi's doors are not of key.
The pull request is for key doors, those for issavi need to be cataloged and corrected.

**Comment by miguelstrungs** [comment]
I understand, I am placing level actions for each issuing port, that is, lvl 1, for non-standard ports!

**Comment by dudantas** [comment]
> I understand, I am placing level actions for each issuing port, that is, lvl 1, for non-standard ports!

Test this: https://github.com/opentibiabr/otservbr-global/commit/ea37140a16daeb519cff6b876f22ae624f2541dc

**Comment by miguelstrungs** [comment]
thanks! it was much better

**Pull request merged**
