### PR TITLE
Cyclopedia -> Houses

### PR DESCRIPTION
**Pull request by dex-89**
**Need reviews, checks, tests**

**Who can help me?**

**Author:** @SaiyansKing

### CODE REVIEW

**Comment by aurelion5670** [comment]
This is the base code for houses of saiayans, it's pretty incomplete and i wouldn't recommend it to merge until it's done (As isn't done at all)

**Comment by dex-89** [comment]
> This is the base code for houses of saiayans, it's pretty incomplete and i wouldn't recommend it to merge until it's done (As isn't done at all)

I know that, I'm trying to finish it.

**Comment by SaiyansKing** [comment]
It isn't even code for houses, I only tested the cyclopedia houses structure. The reason because I didn't even touched it after so much time is because I don't create another real map server so I need to code program(add it to rme?) that will create client map files with house details.

**Comment by FakeShinoda** [comment]
I started this system with a modification in RME to include the house details and parse to server.
If you can wait a little bit i can help you to finished that... But like they say its just the houses structure.

**Pull request closed without merging**
