### PR TITLE
Oberon Mechanics

### PR DESCRIPTION
**Pull request by Glatharth**
This is just Oberon's mechanics, you need to remake Oberon on the Lua, if anyone volunteers to do it, I'll be grateful.

- [x] Mechanic
- [x] Need to add Oberon information as looktype, attacks, loot, health, etc.

-- Credits to Attack787 for Oberon information

### CODE REVIEW

**Comment by MajestyOTBR** [comment]
@dudantas PR waiting for your review.

**Comment by attack787** [comment]
The boss is doing summons under his body, this affects when he is traped

**Comment by Glatharth** [comment]
> The boss is doing summons under his body, this affects when he is traped

is to avoid some bugs when summing up

**Comment by majestyotbr** [comment]
Just missing to remove the .xml of the monster.

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
