### PR TITLE
Try to fix decay bug

### PR DESCRIPTION
**Pull request by dudantas**
# Description

This is a possible solution for the decay crash. Must be tested.

## Type of change
  - [x] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SaiyansKing** [comment]
It'll not fix anything because:
1. Objects added to decayItems can't be null pointers so it doesn't crash because of nullptr dereferences.
2. You wrote that check incorrectly it should be:
`if (!item) {
	it = decayItems[bucket].erase(it);
	continue;
}`
after: `Item* item = *it;`
3. Those crashes are mostly due to incorrect usage of: `incrementReferenceCounter` and `decrementReferenceCounter`
simplest fix for it would be to write some wrapper class over those functions that automatically manage reference counter using RAII or using std::shared_ptr and accept the fact that it might consume some performance and more RAM.

**Comment by dudantas** [comment]
> It'll not fix anything because:
> 
> 1. Objects added to decayItems can't be null pointers so it doesn't crash because of nullptr dereferences.
> 2. You wrote that check incorrectly it should be:
>    `if (!item) { it = decayItems[bucket].erase(it); continue; }`
>    after: `Item* item = *it;`
> 3. Those crashes are mostly due to incorrect usage of: `incrementReferenceCounter` and `decrementReferenceCounter`
>    simplest fix for it would be to write some wrapper class over those functions that automatically manage reference counter using RAII or using std::shared_ptr and accept the fact that it might consume some performance and more RAM.

Greetings!
Thank you very much for the feedback. I saw that in your source, you rewrote the decay. Would you have availability to bring the changes? Or, if there isn't, I can bring it to a branch and you could revise it (if you want, you can even open the pull after I bring in the changes). What do you think?

**Comment by SaiyansKing** [comment]
> Greetings!
> Thank you very much for the feedback. I saw that in your source, you rewrote the decay. Would you have availability to bring the changes? Or, if there isn't, I can bring it to a branch and you could revise it (if you want, you can even open the pull after I bring in the changes). What do you think?

If you want you can make it compatible with otservbr, I don't have time for it(and if you want to give me credits you can mark me as co-author xD).

If someone is curious I've decided to hide the repository as I didn't have time to work on it and grow tired of working on it because of the current Open Tibia Community toxicity(I've decided that it's better than to explain in every issue that I'll fix something sometime in the future due to lack of time).

**Comment by gerotib** [comment]
I got no time to add it here but I have done it compatible with otservbr on my project and had no issues whatsoever. These commits were added for sure, dont remember if anything is missing: [1](https://github.com/Erza/optimized_forgottenserver/commit/0e011ff00783abc1d19bcdfdba3aae3c2d90105b), [2](https://github.com/Erza/optimized_forgottenserver/commit/16a43ffc039f20e26acaad726ebc5f44c75ebe9b), [3](https://github.com/Erza/optimized_forgottenserver/commit/299ced707ad05c7b0042ccb3fd061a08f9c50213), [4](https://github.com/Erza/optimized_forgottenserver/commit/b7231767c16c2b43f655eadea577045e8d253836)

**Comment by beats-dh** [comment]
> I got no time to add it here but I have done it compatible with otservbr on my project and had no issues whatsoever. These commits were added for sure, dont remember if anything is missing: [1](https://github.com/Erza/optimized_forgottenserver/commit/0e011ff00783abc1d19bcdfdba3aae3c2d90105b), [2](https://github.com/Erza/optimized_forgottenserver/commit/16a43ffc039f20e26acaad726ebc5f44c75ebe9b), [3](https://github.com/Erza/optimized_forgottenserver/commit/299ced707ad05c7b0042ccb3fd061a08f9c50213), [4](https://github.com/Erza/optimized_forgottenserver/commit/b7231767c16c2b43f655eadea577045e8d253836)

I can try to do this but I need someone to test it, tonight I can open RP.

**Comment by dudantas** [comment]
> > Greetings!
> > Thank you very much for the feedback. I saw that in your source, you rewrote the decay. Would you have availability to bring the changes? Or, if there isn't, I can bring it to a branch and you could revise it (if you want, you can even open the pull after I bring in the changes). What do you think?
> 
> If you want you can make it compatible with otservbr, I don't have time for it(and if you want to give me credits you can mark me as co-author xD).
> 
> If someone is curious I've decided to hide the repository as I didn't have time to work on it and grow tired of working on it because of the current Open Tibia Community toxicity(I've decided that it's better than to explain in every issue that I'll fix something sometime in the future due to lack of time).

Believe me when I say that if there's anyone in open tibia who can understand you, it's us. The toxicity is too great... We can still take it, because we are a team very close together. But, if, for example, it was just me, I would have already given up. It even affects the psychological.

**Comment by gesior** [comment]
@dudantas Do you still have decay crashes after this https://github.com/opentibiabr/otservbr-global/pull/2710 ? Did you copy these changes to your engine?
Would be nice to run your server in debug mode and get nice **gdb** with item information.

**Comment by dudantas** [comment]
It will be fixed in pr: https://github.com/opentibiabr/canary/pull/38

**Comment by dudantas** [comment]
> @dudantas Do you still have decay crashes after this #2710 ? Did you copy these changes to your engine?
> Would be nice to run your server in debug mode and get nice **gdb** with item information.

It has been reported that even with the fix, the server uses a very high amount of CPU and sometimes crashes (with too many players online.)

**Comment by dudantas** [comment]
Will be fixed in: https://github.com/opentibiabr/canary/pull/38

**Pull request closed without merging**
