### PR TITLE
Fix: #781 and #830

### PR DESCRIPTION
**Pull request by dudantas**
Fixed problems mentioned in issue #781 and #830.
Now the door script will check if there is a place to push, when using the door with a player inside, if there is no free SQM, it returns the message "Sorry, not possible."

Thanks for @lBaah for developing the function of checking tiles.

### CODE REVIEW

**Comment by dudantas** [comment]
@manifex30890 and @Lycanzito test this PR.

**Comment by Lycanzito** [comment]
> @manifex30890 and @Lycanzito test this PR.

thanks !
I've fixed it doing other things, will make these changes, seens better! =)
then my solution xD

**Comment by dudantas** [comment]
When you test it, return it so we can pass it.

**Comment by dudantas** [comment]
When you test it, return it so we can merge.

**Comment by majestyotbr** [comment]
Thanks.

**Pull request merged**
