### PR TITLE
feat: add webhook notifications for server start, shutdown, server save and raids

### PR DESCRIPTION
**Pull request by wizardlink**
This PR adds webhook notifications to Discord.

The URL can be configured through the config: discordWebhookURL

This also adds the libraries libcurl and libjsoncpp as dependencies.

### CODE REVIEW

**Review by Costallat — APPROVED** [review]

**Comment by wizardlink** [comment]
Since @Costallat has approved, I suppose we can move on even though we have a check failing? Will wait for your input @MajestyOTBR.

**Comment by dex-89** [comment]
> Since @Costallat has approved, I suppose we can move on even though we have a check failing? Will wait for your input @MajestyOTBR.

discordWebhookURL = invite discord url?

**Comment by wizardlink** [comment]
> > Since @Costallat has approved, I suppose we can move on even though we have a check failing? Will wait for your input @MajestyOTBR.
> 
> discordWebhookURL = invite discord url?

_Responding here too for the sake of keeping a record in the repository._

That configuration is to use a webhook from a Discord server, you can find that here:

image
image

**Review by dex-89 — APPROVED** [review]

**Comment by Tazer89** [comment]
Tested and works like charm. Should have luascript to it so it easy to add custom notifications :) Anyway awesome work!

**Comment by wizardlink** [comment]
> Tested and works like charm. Should have luascript to it so it easy to add custom notifications :) Anyway awesome work!

Haven't thought about that but it sounds like a nice idea. Since then you can add things like login messages more easily and whatnot. I might consider adding that once I am satisfied with my spell system.

**Review by dex-89 — APPROVED** [review]

**Comment by wizardlink** [comment]
@dex-89, @MajestyOTBR. That's my last commit for this pull-request, whether it moves forward is up to you guys.

For the issue we encountered for the custom maps not loading: Something has fixed it recently, both locally and on my server, everything is being loaded correctly.

**Review by majestyotbr — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Thanks for your contribution!

**Comment by wizardlink** [comment]
> @wizardlink there is a **memory leak** and **crash**, just test it with some talkactions (do it 10x per example and check you ram)
> @MajestyOTBR
> 
> PS. you can use /teste 10x (fast) with Webhook.send("Teste", "testing", WEBHOOK_COLOR_WARNING)

This is a _limitation_ in a sense with the curl library, the fix as of now would be to do global cleanups instead of cleaning after every request but it doesn't makes sense to have that if, for example, there are multiple requests on-going. I'd say that you can use a global clean if you'd like, but I'd recommend just avoiding making unnecessary requests, at least for now.

In the long run, it would be beneficial to create a file for suppressions and check for curl.

**Comment by wizardlink** [comment]
> You mean curl_global_cleanup() ? I was tested and same problem =/
> 
> Edit: 
> Each /test
> appear on my screen:
> [New Thread 0x7ffff0a20700 (LWP 23741)]
> [Thread 0x7ffff0a20700 (LWP 23741) exited]

Interesting, mind giving me the basic specs of the machine (including OS)?

Also in regards to what your friend said, there is no such thing. It is just sending a HTTP request to Discord.

**Comment by wizardlink** [comment]
> Distributor ID: Ubuntu
> Description: Ubuntu 16.04.7 LTS
> Release: 16.04
> Codename: xenial
> Processor: AMD Ryzen 5 3600X - 6 c / 12 t - 3.8 GHz / 4.4 GHz
> Memory: 32GB
> 
> One question, is possible send image to discord?
> Thanks!

Sorry for the delay, had a full day. Yes, you can send an image to Discord, just not through this implementation. You can check out this for more info: https://discord.com/developers/docs/resources/channel#embed-object

In regards to the overall problem, I should come up with a solution until Wednesday. I already found the issue, just figuring out the best way to tackle it. :)

-Edit-

FYI: A segment fault is occurring because the project compiles to 32bit, so, it only uses a maximum of 4GB. Which brings me to mention... @MajestyOTBR, you should talk with your development team about it. I don't think it's beneficial to maintain it at this day and age at 32 bits.

-Edit 2-

I was way too abroad with my earlier statement, specifically, this error is occurring when the `write_data` function is being called. You can do a quick fix by just removing it's reference and the method itself. However, I am looking into how that function is using so much memory that the application can't allocate more.

**Pull request merged**
