### PR TITLE
Update schema.sql

### PR DESCRIPTION
**Pull request by ghost**
`isreward` varchar(255) DEFAULT NULL  added to the line 163

### CODE REVIEW

**Comment by dudantas** [comment]
You need to explain ... What does this solve? Is it a bug? Is it an improvement? How do we test?

**Comment by ghost** [comment]
Without this snippet, nothing is saved in the database

**Comment by dudantas** [comment]
What do you mean, nothing is saved?
Isn't the database saving things?

**Comment by Costallat** [comment]
@Madrugrelo I think that it's something that you customized on your server, there is no place on the code that saves that field 'isreward', that's why it doesn't exists on the schema.

**Pull request closed without merging**
