### PR TITLE
Fix delay in the onUse of runes/potions

### LINKED ISSUE #1153: POT with higher delay every 3rd while walking
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
se correr e se potar a pot tem 1 delay imenso, qnd testei potava 2x normal e a terceira saia dps de 1 tempao, o erro nao ocorre qnd o char esta parado

**To Reproduce**
1. run and pot yourself
2. See error

**Expected behavior**
pot running without any higher delay issues (i believe its something on source)

**Desktop (please complete the following information):**
 - OS: Windows 10 / Ubuntu 18.04

### PR DESCRIPTION
**Pull request by dudantas**
Resolves #1153

### CODE REVIEW

**Comment by Geekbuddy** [comment]
ITEM_TYPE_POTION is missing.

**Comment by dudantas** [comment]
> ITEM_TYPE_POTION is missing.

Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.

**Comment by Geekbuddy** [comment]
> > ITEM_TYPE_POTION is missing.
> 
> Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.

Its not you code missing it. Its the source don't have ITEM_TYPE_POTION.

**Comment by Geekbuddy** [comment]
> > ITEM_TYPE_POTION is missing.
> 
> Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.

game.cpp:2255:33: error: ‘ITEM_TYPE_POTION’ was not declared in this scope
   if (it.isRune() || it.type == ITEM_TYPE_POTION) {

Its ITEM_TYPE_POTION is missing in the source i guess not in your code.

**Comment by dudantas** [comment]
> > > ITEM_TYPE_POTION is missing.
> > 
> > 
> > Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.
> 
> game.cpp:2255:33: error: ‘ITEM_TYPE_POTION’ was not declared in this scope
> if (it.isRune() || it.type == ITEM_TYPE_POTION) {
> 
> Its ITEM_TYPE_POTION is missing in the source i guess not in your code.

image

I told you, it's declared. Even the check finish and generated the executable.

**Comment by dudantas** [comment]
I will try to compile again. I'll get back to you with an answer.

**Comment by Geekbuddy** [comment]
> > > > ITEM_TYPE_POTION is missing.
> > > 
> > > 
> > > Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.
> > 
> > 
> > game.cpp:2255:33: error: ‘ITEM_TYPE_POTION’ was not declared in this scope
> > if (it.isRune() || it.type == ITEM_TYPE_POTION) {
> > Its ITEM_TYPE_POTION is missing in the source i guess not in your code.
> 
> image
> 
> I told you, it's declared. Even the check finish and generated the executable.

Yeah i see... but where is ITEM_TYPE_POTION taken from can't find it anywhere.

**Comment by dudantas** [comment]
> > > > > ITEM_TYPE_POTION is missing.
> > > > 
> > > > 
> > > > Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.
> > > 
> > > 
> > > game.cpp:2255:33: error: ‘ITEM_TYPE_POTION’ was not declared in this scope
> > > if (it.isRune() || it.type == ITEM_TYPE_POTION) {
> > > Its ITEM_TYPE_POTION is missing in the source i guess not in your code.
> > 
> > 
> > image
> > I told you, it's declared. Even the check finish and generated the executable.
> 
> Yeah i see... but where is ITEM_TYPE_POTION taken from can't find it anywhere.

```cpp

	registerEnum(ITEM_TYPE_RUNE)
	registerEnum(ITEM_TYPE_ARMOR)
	registerEnum(ITEM_TYPE_AMULET)
	registerEnum(ITEM_TYPE_BOOTS)
	registerEnum(ITEM_TYPE_DECORATION)
	registerEnum(ITEM_TYPE_FOOD)
	registerEnum(ITEM_TYPE_HELMET)
	registerEnum(ITEM_TYPE_LEGS)
	registerEnum(ITEM_TYPE_OTHER)
	registerEnum(ITEM_TYPE_POTION)
	registerEnum(ITEM_TYPE_RING)
	registerEnum(ITEM_TYPE_RUNE)
	registerEnum(ITEM_TYPE_SHIELD)
	registerEnum(ITEM_TYPE_TOOLS)
	registerEnum(ITEM_TYPE_VALUABLE)
	registerEnum(ITEM_TYPE_AMMO)
	registerEnum(ITEM_TYPE_AXE)
	registerEnum(ITEM_TYPE_CLUB)
	registerEnum(ITEM_TYPE_DISTANCE)
	registerEnum(ITEM_TYPE_SWORD)
	registerEnum(ITEM_TYPE_WAND)
	registerEnum(ITEM_TYPE_CREATUREPRODUCT)
	registerEnum(ITEM_TYPE_RETRIEVE)
	registerEnum(ITEM_TYPE_GOLD)
	registerEnum(ITEM_TYPE_UNASSIGNED)

```
Maybe this is missing from luascript.cpp?

**Comment by Geekbuddy** [comment]
> > > > > > ITEM_TYPE_POTION is missing.
> > > > > 
> > > > > 
> > > > > Look again. You must have pulled something wrong, because the compilation occurred normally in the checks, I also tested it on localhost and compiled it.
> > > > 
> > > > 
> > > > game.cpp:2255:33: error: ‘ITEM_TYPE_POTION’ was not declared in this scope
> > > > if (it.isRune() || it.type == ITEM_TYPE_POTION) {
> > > > Its ITEM_TYPE_POTION is missing in the source i guess not in your code.
> > > 
> > > 
> > > image
> > > I told you, it's declared. Even the check finish and generated the executable.
> > 
> > 
> > Yeah i see... but where is ITEM_TYPE_POTION taken from can't find it anywhere.
> 
> ```c++
> 	registerEnum(ITEM_TYPE_RUNE)
> 	registerEnum(ITEM_TYPE_ARMOR)
> 	registerEnum(ITEM_TYPE_AMULET)
> 	registerEnum(ITEM_TYPE_BOOTS)
> 	registerEnum(ITEM_TYPE_DECORATION)
> 	registerEnum(ITEM_TYPE_FOOD)
> 	registerEnum(ITEM_TYPE_HELMET)
> 	registerEnum(ITEM_TYPE_LEGS)
> 	registerEnum(ITEM_TYPE_OTHER)
> 	registerEnum(ITEM_TYPE_POTION)
> 	registerEnum(ITEM_TYPE_RING)
> 	registerEnum(ITEM_TYPE_RUNE)
> 	registerEnum(ITEM_TYPE_SHIELD)
> 	registerEnum(ITEM_TYPE_TOOLS)
> 	registerEnum(ITEM_TYPE_VALUABLE)
> 	registerEnum(ITEM_TYPE_AMMO)
> 	registerEnum(ITEM_TYPE_AXE)
> 	registerEnum(ITEM_TYPE_CLUB)
> 	registerEnum(ITEM_TYPE_DISTANCE)
> 	registerEnum(ITEM_TYPE_SWORD)
> 	registerEnum(ITEM_TYPE_WAND)
> 	registerEnum(ITEM_TYPE_CREATUREPRODUCT)
> 	registerEnum(ITEM_TYPE_RETRIEVE)
> 	registerEnum(ITEM_TYPE_GOLD)
> 	registerEnum(ITEM_TYPE_UNASSIGNED)
> ```
> 
> Maybe this is missing from luascript.cpp?

Yes it is missing in the source this source thats why so need to make a pull request on that here aswell.

**Comment by dudantas** [comment]
I'm checking here and I'm going to upload the code
Thank you

**Comment by Geekbuddy** [comment]
> I'm checking here and I'm going to upload the code
> Thank you

Missing ITEM_TYPE_POTION in items.h aswell.

**Comment by dudantas** [comment]
> > I'm checking here and I'm going to upload the code
> > Thank you
> 
> Missing ITEM_TYPE_POTION in items.h aswell.

It's have: https://github.com/dudantas/otservbr-global/blob/29c01447c81c842dbaa53f21340fcbc286d70574/src/items.h#L63

**Comment by dudantas** [comment]
There are some more codes regarding potion missing, I will go up

**Comment by Geekbuddy** [comment]
> There are some more codes regarding potion missing, I will go up

Yeah its your source but in opentibiabr/otservbr-global those is not added here. 👍

**Comment by dudantas** [comment]
> > There are some more codes regarding potion missing, I will go up
> 
> Yeah its your source but in opentibiabr/otservbr-global those is not added here. 👍

Ah ... Understand, this pull request (potion) is directed to the quickloot branch (not to develop), because the potion uses things that were added to the quickloot.
image

So, these "item_type" things you will have to get from the quickloot pull request here: https://github.com/opentibiabr/otservbr-global/pull/1400

**Comment by dudantas** [comment]
I created two pull requests to not merge two codes of different things in only one pull request, but in the end the code for quickloot and this pr "complement each other". Because the potions pr uses things that were added to the quickloot pull request

**Comment by dudantas** [comment]
Understood?

**Comment by Geekbuddy** [comment]
> Understood?

Ah i see! ill will add that and try that aswell.

**Comment by dudantas** [comment]
The easiest is for you to download the entire branch (from my fork) and compile it, it will come with all the modifications (both in the quickloot and in the potions). Then do the tests and report what you found.

**Comment by Geekbuddy** [comment]
> The easiest is for you to download the entire branch (from my fork) and compile it, it will come with all the modifications (both in the quickloot and in the potions). Then do the tests and report what you found.

Ok i do that. 👍

**Comment by dudantas** [comment]
> > The easiest is for you to download the entire branch (from my fork) and compile it, it will come with all the modifications (both in the quickloot and in the potions). Then do the tests and report what you found.
> 
> Ok i do that. 👍

Ok, thanks for the reports.

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation

**Comment by dudantas** [comment]
Sent some codes that were missing.

**Comment by gabz182** [comment]
Tested..
Working, thanks!

**Comment by dudantas** [comment]
> Tested..
> Working, thanks!

@gabz182 you can test again, please?

**Pull request merged**
