### PR TITLE
Feat: Event Schedule

### LINKED ISSUE #951: Question about schedule.
Question, is possible in client 12 in event schedule show when i want make a double exp in server?

### PR DESCRIPTION
**Pull request by marcosvf132**
Resolves #951
This feat include:

1. Client changes to display events with color markers and description. (check login.php changes)

   image

2. XML file that the user can create events with exp bonus, loot chance bonus, spawn rate and skill bonus.
On `data/XML/events.xml`
```XML 
<event name="Otservbr event" startdate="MM/DD/YYYY" enddate="MM/DD/YYYY" >
	<ingame exprate="100" lootrate="100" spawnrate="100" skillrate="100" />
	<description description="Event description" />
	<colors colordark="#235c00" colorlight="#2d7400" />
	<details displaypriority="6" isseasonal="0" specialevent="0" />
</event>
```

**- myacc Login.php:**
(if you want you can see the entire file https://pastebin.pl/view/aeaf0774 but i advise you to use the OTBR login.php !!)
**1- Add function (on login.php or functions.php):** (MyAcc)
```PHP
function parseEvent($table1, $date, $table2)
{
if ($table1) {
	if ($date) {
		if ($table2) {
			$date = $table1->getAttribute('startdate');
			return date_create("{$date}")->format('U');
		} else {
			$date = $table1->getAttribute('enddate');
			return date_create("{$date}")->format('U');
		}
	} else {
		foreach($table1 as $attr) {
			if ($attr) {
				return $attr->getAttribute($table2);
			}
		}
	}
}
	return;
}
```
2- On login.php case:  (MyAcc)
```PHP
case 'eventschedule':
	$eventlist = [];
	$file_path = config('server_path') . 'data/XML/events.xml';
	if (!file_exists($file_path)) {
		die(json_encode([]));
		break;
	}
	$xml = new DOMDocument;
	$xml->load($file_path);
	$tmplist = [];
	$tableevent = $xml->getElementsByTagName('event');

	foreach ($tableevent as $event) {
		if ($event) { $tmplist = [
		'colorlight' => parseEvent($event->getElementsByTagName('colors'), false, 'colorlight'),
		'colordark' => parseEvent($event->getElementsByTagName('colors'), false, 'colordark'),
		'description' => parseEvent($event->getElementsByTagName('description'), false, 'description'),
		'displaypriority' => intval(parseEvent($event->getElementsByTagName('details'), false, 'displaypriority')),
		'enddate' => intval(parseEvent($event, true, false)),
		'isseasonal' => getBoolean(intval(parseEvent($event->getElementsByTagName('details'), false, 'isseasonal'))),
		'name' => $event->getAttribute('name'),
		'startdate' => intval(parseEvent($event, true, true)),
		'specialevent' => intval(parseEvent($event->getElementsByTagName('details'), false, 'specialevent'))
			];
		$eventlist[] = $tmplist; } }
	die(json_encode(['eventlist' => $eventlist, 'lastupdatetimestamp' => time()]));
	break;
```

**- Gesior ws_login.php:**
( Again, if you want you can see the entire file https://pastebin.com/eicZRk56 but i advise you to use the OTBR ws_login.php !!)
**1- Add function (on ws_login.php or functions.php):**  (Gesior)
```PHP
/** Function event scheduler. */
function parseEvent($table1, $date, $table2, $bool){
if ($table1) {
	if ($date) {
		if ($table2) {
			$date = $table1->getAttribute('startdate');
			return date_create("{$date}")->format('U');
		} else {
			$date = $table1->getAttribute('enddate');
			return date_create("{$date}")->format('U');
		}
	} else {
		foreach($table1 as $attr) {
			if ($attr) {
				if ($bool) {
					if (intval($attr->getAttribute($table2)) > 0) {
						return true;
					}
						return false;
				}
				return $attr->getAttribute($table2);
			}
		}
	}
}
	return;
}
```
2- On ws_login.php case:  (Gesior)
```PHP

case 'eventschedule':
	$eventlist = array();
	$lastupdatetimestamp = time();
	$file_path = Website::getWebsiteConfig()->getValue('serverPath') . 'data/XML/events.xml';
	if (!Website::fileExists($file_path)) {
		die(json_encode([]));
		break;
	}
	$xml = new DOMDocument;
	$xml->load($file_path);
	$tableevent = $xml->getElementsByTagName('event');
	foreach ($tableevent as $event) {
		if ($event) {
		$tmplist = array();
		$tmplist['colorlight'] = parseEvent($event->getElementsByTagName('colors'), false, 'colorlight', false);
		$tmplist['colordark'] = parseEvent($event->getElementsByTagName('colors'), false, 'colordark', false);
		$tmplist['description'] = parseEvent($event->getElementsByTagName('description'), false, 'description', false);
		$tmplist['displaypriority'] = (intval(parseEvent($event->getElementsByTagName('details'), false, 'displaypriority', false)));
		$tmplist['enddate'] = (intval(parseEvent($event, true, false, false)));
		$tmplist['isseasonal'] = parseEvent($event->getElementsByTagName('details'), false, 'isseasonal', true);
		$tmplist['name'] = $event->getAttribute('name');
		$tmplist['startdate'] = (intval(parseEvent($event, true, true, false)));
		$tmplist['specialevent'] = (intval(parseEvent($event->getElementsByTagName('details'), false, 'specialevent', false)));
		$eventlist[] = $tmplist;
		}
	}
	die(json_encode(compact('eventlist', 'lastupdatetimestamp')));
	break;
```

### CODE REVIEW

**Comment by CyCu991** [comment]
For my server no working 👎 Used Gesior 
https://ibb.co/Vg1hyb6

**Comment by joao-blip** [comment]
@Znote possible conversion for your login

**Comment by MajestyOTBR** [comment]
Tested and worked with MyAAC.

**Comment by majestyotbr** [comment]
Tested, working. Thanks for your contribution!

**Comment by majestyotbr** [comment]
Updated login.php:
GesiorAAC: https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.4
MyAAC: https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.7

**Review by majestyotbr — APPROVED** [review]

**Comment by Znote** [comment]
This now works on latest Znote AAC. 
When loginWebService changes happen here, please let me know by referencing it in a [Znote AAC issue](https://github.com/Znote/ZnoteAAC/issues)

That way I can keep track of and patch Znote AAC according to the development here. 
If there are anything I have missed, create an issue and link to its merged PR.

**Pull request merged**
