### PR TITLE
Hibernal and lacewing moth mount item fix

### PR DESCRIPTION
**Pull request by yatozin**

### CODE REVIEW

**Comment by MajestyOTBR** [comment]
Please, remove `<action itemid="30840" script="others/mounts/mounts.lua" />` from actions.xml.

**Comment by MajestyOTBR** [comment]
Sorry, my mistake.

**Comment by yatozin** [comment]
> Please, remove `<action itemid="30840" script="others/mounts/mounts.lua" />` from actions.xml.

its needed for mole mount

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Pull request merged**
