### PR TITLE
fix: customize character crash caused by familiars

### PR DESCRIPTION
**Pull request by gpedro**
- right-click on your player > customize character
- you will get a crash

### CODE REVIEW

**Comment by Juanzin93** [comment]
tested, compiling got alot of warnings
image
and it didnt fix the issue, i go to my char in dawnport, change vocation to dawnport vocation, try to change outfits and crash with this error 
image

**Comment by dex-89** [comment]
Dawnport: First vocation select -> Second vocation select (change) -> Customize character = crash

**Comment by dex-89** [comment]
I checked Dawnport again today. Crash is only with **sorcerer**. Rest works ok

**Comment by dex-89** [comment]
Fixed

**Pull request closed without merging**
