### PR TITLE
Convert spells and runes to revscriptsys

### PR DESCRIPTION
**Pull request by beats-dh**
**All player spells and runes have been converted, the monsters spells are still in progress! All need revision.**

**With the contribution of @LeoTK4 @DeroW-FD @Glatharth @APenDel**

### **_Spells:_**

- [x] Attack
- [x] Conjuring
- [x] Healing
- [x] House
- [x] Monster
- [x] Party
- [x] Runes
- [x] Summon
- [x] Support

### **_Fixes:_**
- [x] #923 
- [x] #2506
- [x] #2507 
- [x] #2563

### CODE REVIEW

**Comment by Beats-Dh** [comment]
@ @

- [ ] 

1. 

- 

> `[](url)`

**Review by omeranha — APPROVED** [review]

**Comment by beats-dh** [comment]
Executable: https://ci.appveyor.com/project/opentibiabr/otservbr-global/builds/39577822/artifacts

**Review by omeranha — APPROVED** [review]
All working, well done!

**Review by majestyotbr — APPROVED** [review]

**Comment by xThauma** [comment]
Chivalrous challenge needs a fix. It should only prioritize ranged creatures instead of challenging only them. Expected work is like for example:
1. We have 6 monsters on map, 3 minotaur archers and 3 minotaurs.
2. Spell should challenge 3 minotaurs archers and 2 minotaurs
I wrote a Simple fix:
    for _, creature in pairs(creatures) do
        if creature:isMonster() then
            if creature:getType():isRewardBoss() then
                return -1
            elseif creature:getMaster() == nil and creature:getType():getTargetDistance() > 1 then
                table.insert(monsters, creature)
            elseif creature:getMaster() == nil then
                table.insert(meleeMonsters, creature)
            end
        end
    end

    local counter = 1
    local tempSize = #monsters
    if tempSize < 5 and #meleeMonsters > 0 then
        for i = tempSize, 5 do
            if meleeMonsters[counter] ~= nil then
                table.insert(monsters, meleeMonsters[counter])
                counter = counter + 1
            end
        end
    end

**Comment by gustavocs16** [comment]
as bombs (ex: fire bomb, energy bomb) e walls (ex: fire wall e energy wall)
ao atacar no bixo dele deve receber o dano (20) e ficar "infectado" pelo elemento
isso não está ocorrendo.

Quando ataca no bixo, ele não toma o hit e fica parado em cima sem se movimentar.

**Comment by majestyotbr** [comment]
Spells and Runes in revscriptsys working, monster spells working, /reload scripts and /reload monsters working.

**Review by majestyotbr — APPROVED** [review]

**Comment by ghost** [comment]
Not work house spells

**Comment by beats-dh** [comment]
> Not work house spells

I could not understand.

**Comment by ghost** [comment]
SD exhausted is not correct 2 sec and group cooldown 2 sec (now is 900). exori gran con and exori gran ico DMG is not correct RL Tibia.

**Review by dudantas — APPROVED** [review]
Very good, thanks!

**Pull request merged**
