### PR TITLE
Fix Quest Reward (Mintwallin Cyclops and Mad Mage Room)

### PR DESCRIPTION
**Pull request by vinioliveirasilva**
Fix Mintwallin Cyclops Quest Reward (new it's possible to get small diamond and daily respawn itens)
Fix Mad Mage Room Quest Reward (now it's possible to get  Key 3667)

### CODE REVIEW

**Comment by dudantas** [comment]
Hello, thanks for the contribution. We appreciate this.

However, could you cut out the part of the map that was changed and send it to us? We have changes in the map in progress and it is not possible to accept map pr at the moment, as it would conflict.

**Comment by vinioliveirasilva** [comment]
Sure, i going to remove the map from this PR e add some description that what had change.

**Comment by dudantas** [comment]
> Sure, i going to remove the map from this PR e add some description that what had change.

Thank you!
Grateful for understanding.

**Comment by vinioliveirasilva** [comment]
Map Changes:
Add a dead human (32576, 32216, 15) (id: 2317, aid: 2001, uid: 65212)
Edit chest (32591, 32097, 14) (id: 1740, aid: 2001, uid: 65211)
Edit chest (32590, 32097, 14)  -> add content ( strong health potion x1, strong health potion x1, hatchet, chain armor and chain helmet )

**Comment by dudantas** [comment]
The chest {x = 32592, y = 32097, z = 14} do not have aid/uid ?

**Comment by dudantas** [comment]
Thanks for the contribution! I put it on the map that I'm changing and I should go up soon.

**Pull request merged**
