### PR TITLE
feat: colored loot message

### PR DESCRIPTION
**Pull request by lBaah**
doesn't work on older client
missing creaturescript at scripts/creaturescripts yet

### CODE REVIEW

**Comment by gpedro** [comment]
LGTM. Should check the version before sending, no?

**Comment by Lycanzito** [comment]
it should be colored, right? '-' 
image

**Comment by mattyx14** [comment]
he say it: missing creaturescript at scripts/creaturescripts yet

**Comment by lBaah** [comment]
This is meant to use with OTBR not custom servers @Lycanzito .

@gpedro we should not support outdated client. This allows us to focus on the development of protocol 12 features.
Cipsoft has changed the way few things are rendered in the screen (12.15+) thus making outdated not compatible anymore, if we update the protocol more than 12.00. So we drop the support.

**Comment by lBaah** [comment]
I'll close this since it is going to be a 1.0 feature.

**Pull request closed without merging**
