### PR TITLE
Support to rates regen, spell cooldown and attack speeds

### PR DESCRIPTION
**Pull request by gtkatakura**
# Description

- Support to configure into `config.lua` new variables related to regens, spell cooldown and attack speed

```lua
rateHealthRegen = 1.0
rateHealthRegenSpeed = 1.0
rateManaRegen = 1.0
rateManaRegenSpeed = 1.0
rateSoulRegen = 1.0
rateSoulRegenSpeed = 1.0

rateSpellCooldown = 1.0
rateAttackSpeed = 1.0
rateOfflineTrainingSpeed = rateAttackSpeed
rateExerciseTrainingSpeed = rateAttackSpeed
```

### **Actual**

- We need to manually change health/mana gain on items.xml and vocations.xml.
- We need to manually change all cooldown values on spells.xml

### **Expected**

- Now we can just set the variables `rateHealthRegen/rateManaRegen`, so items and vocation will change the related regen mana/health attributes
- Now we can just set the variable `rateSpellCooldown` and all spells will be divided by the variable

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

#### rateHealthRegen, rateHealthRegenSpeed, rateManaRegen and rateManaRegenSpeed
  - [x] Eat food to see the mana/health regen of the vocation
  - [x] Use some item like a life ring to see the mana/health regen
  - [x] Use the bed, the mana/health factor must by applied
  
#### rateSoulRegen/rateSoulRegenSpeed
  - [x] Kill a monster and see if the soul regen factor is applied
  - [x] Use the bed, the soul factor must by applied
  
#### rateSpellCooldown
  - [x] Spawn spells to see the factor applied
  - [x] Spawn one buff spell (utura, utura gran, utori mas sio), the value configured should be applied over the regen ticks of the magic
  
#### rateOfflineTrainingSpeed
  - [x] Do offline training of some arm skill, the attack speed factor must use the rateOfflineTrainingSpeed

#### rateExerciseTrainingSpeed
  - [x] Use an exercise weapon , the attack speed factor must use the rateExerciseTrainingSpeed

**Test Configuration**:

  - Server Version: 12.64
  - Client: 12.64
  - Operating System: Windows/Ubuntu

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by beats-dh — CHANGES_REQUESTED** [review]
.

**Comment by gtkatakura** [comment]
@Beats-Dh `gainMana` and `gainHP` aren't related to values received when upping level?

**Comment by beats-dh** [comment]
> @Beats-Dh `gainMana` and `gainHP` aren't related to values received when upping level?

I made a mess where I'm sorry! I'll do a test tonight and if it's ok I'll review it.

**Comment by gtkatakura** [comment]
I am reading more about the codebase and seems that I can set this into ConditionRegeneration instead of the loading of items.xml and vocations.xml. Also, I am not sure if my code reflects into mana regen when using a bed or other cases. I am not sure about all the cases that trigger the mana regen/health regen.

I will make these changes, but I am very busy this week so I will do it at weekend.

**Comment by gtkatakura** [comment]
I took a break today and made the changes. Now when using bed the mana/health regen will apply the rate, also some scripted spells like `magic_wall.lua` and swift `foot.lua` which manually set the spell cooldown also receive the `rateSpellCooldown`.

**Comment by beats-dh** [comment]
@gtkatakura It would be nice for you to add some stuff related to monsters, I remember I used to have. Something like increasing all monster damage, healt, exp. it would be interesting!

**Comment by gtkatakura** [comment]
We have the variables `rateMonsterHealth`, `rateMonsterAttack` and `rateMonsterDefense`. I not using them, but reading the code seems that they are working. They are OK for you?

**Comment by andersonfaaria** [comment]
Can you make it float instead of int? In certain situations we would like to increase 20%,50% instead of always whole number multiplications

**Comment by mrhultin** [comment]
RateAttackSpeed is really odd name, rateAttack already mean attackspeed.

**Comment by gtkatakura** [comment]
@andersonfaaria I can stay with ints but the value represents a percentage. What do you think?

```lua
rateManaRegen=100 -- 100%
```

Or is better to be float to stay the same pattern (`multiplier`), because all other rates already work this way?

**Comment by andersonfaaria** [comment]
> @andersonfaaria I can stay with ints but the value represents a percentage. What do you think?
> 
> ```lua
> rateManaRegen=100 -- 100%
> ```
> 
> Or is better to be float to stay the same pattern (`multiplier`), because all other rates already work this way?

I'd prefer to keep the pattern by using float, other than that is looking good

**Review by andersonfaaria — CHANGES_REQUESTED** [review]
can you also update the variables in config.lua to float (1.0) instead of 1?

**Comment by gtkatakura** [comment]
@andersonfaaria done

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Tested and working.

**Review by dudantas — APPROVED** [review]

**Comment by dudantas** [comment]
It's ok for me, I even approved, can you just fix the check warnings? For example:

image

You can leave the default "// Starting with a capital letter"

**Comment by gtkatakura** [comment]
@dudantas I didn't added/change these comments, I only added the public/private keyword and reindent the code
maybe we should have one PR only running the cplint auto fix for these cases?

**Pull request merged**
