### PR TITLE
Warzones Fixes

### LINKED ISSUE #275: BUG: Several warzone 4/5/6 damaging each other and them self
#### Describe the bug
Several monsters can damage each other

#### How to Reproduce?
Start warzone 4/5/6

> Give us all details to reproduce the behavior:
> 1. Go to warzone 4/5/6
> 2. Start it
> 3. Monsters will damage each other

#### Screenshots
image

#### Environment
- OS: Windows
- OTServ Version: Latest
- Tibia Version: 12.62

### LINKED ISSUE #2414: BUG: Several warzone 4/5/6 damaging each other and them self
#### Describe the bug
Several monsters can damage each other

#### How to Reproduce?
Start warzone 4/5/6

> Give us all details to reproduce the behavior:
> 1. Go to warzone 4/5/6
> 2. Start it
> 3. Monsters will damage each other

#### Screenshots
image

#### Environment
- OS: Windows
- OTServ Version: Latest
- Tibia Version: 12.62

### PR DESCRIPTION
**Pull request by phacUFPE**
### Fixes:
- [x] Warzone 4
- [x] Warzone 5 
- [x] Warzone 6

Resolves #2414 and 1 Item of #726

### CODE REVIEW

**Comment by ghost** [comment]
I did some tests on Warzone in the cave of **Ravenous Lava Lurker** and realized that after the creature’s death, there’s no body

**Comment by phacUFPE** [comment]
> I did some tests on Warzone in the cave of **Ravenous Lava Lurker** and realized that after the creature’s death, there’s no body

yeah, ravenous lava lurker dont have a corpse like global.

**Comment by ghost** [comment]
> > I did some tests on Warzone in the cave of **Ravenous Lava Lurker** and realized that after the creature’s death, there’s no body
> 
> yeah, ravenous lava lurker dont have a corpse like global.

When killing a Ravenous Lava Lurker in the Global, a pile of cold lava remains like a corpse and referring to the Parcel, creatures cannot push or pass over the object.

image

**Review by adrianomengue — CHANGES_REQUESTED** [review]
@phacUFPE 

We have tested your PR. That's what we found.

**The count of the core**
Ember beast summons were summoned just once (when we entered in the boss room) and not every X time as supposed to be.
Snail slime aren't healing enough the boss. It should heal till 5k HP. 

**The Baron from Below**
It's working everything fine. There's just a small fix in fire damage. See the img below

image

Would be nice if you could check all the AID from machines. We found some without any AID.
image



By now, it's all we can tell. Gonna be waiting for your changes to test it again. Thanks.

Credit to: @leoddias who helped on test.

**Review by dudantas — APPROVED** [review]

**Review by Bipbop69 — APPROVED** [review]

**Review by andersonfaaria — APPROVED** [review]
I'm approving the changes but to be honest I don't know how this quest is expected to be working. Please be careful when testing.

**Pull request merged**
