### PR TITLE
Wrap System Fix in Sources

### LINKED ISSUE #245: Decoration Kit
Quando o char é removido da house por tempo, quando ele da !leavehouse ou vende a house para alguem, os itens de decoração que ele comprou na store permanecem na house, o resto vai para o inbox dele! No global o decoration kit segue para o mesmo local que os itens.

### LINKED ISSUE #340: [Items] Store tapestry can be wrapped inside the wall
When you buy a tapestry in the store and place it on the wall you can wrap it again and then you'll have a decoration kit inside a wall.

### LINKED ISSUE #798: Unwrap Itens + House Bugs (3 in 1 )
Esta dando para dar Unwrap, com o item dentro da inbox ou até mesmo dentro de uma Backpack.

image
image
image
image

Também esta sendo possível retirar os itens de dentro da casa
image
image

Também ao dar leavehouse, os itens da store ficam na casa.

image

### LINKED ISSUE #912: Carpet Improvement
Hi everyone! :-)

(Should be possible to see the "open carpet" in browse field");

With it, should be possible unwrap it under stairs, doors,etc.

image

### PR DESCRIPTION
**Pull request by hyresu**
Hi, I personally prefer to have the wrap system in src, so here goes the one I made.
Btw, I have to give credit to Costallat who, don't get me wrong, did a very good job, I also used the first 2 commits he made for house leave.

This patch will : 
- Make the normal kit items (ex: green cushioned chair) be sent to inbox after leave house.
- Make the store container items (ex: alchemistic cabinet) send the items inside of it before sending itself.
- Make the wrap items work around the custom attribute "unWrapId" instead of ActionId (credits to Costallat for the idea)
- Don't allow for kits being unwraped outside a house (right now it only checked if it was pz)
- Don't allow for store items being pushed outside a house
- Don't add the "wrap it in your house to create a construction kit" in STORE **UNWRAPPED** items
- Fix the tapestry hanged items don't be able to create the construction kit inside a wall.
Update:
- Fix to Browse Field on carpets (as global)
- Fix to not "Poff" effect on container store items.

I don't actually know if there's a file to keep arrays, but in house.cpp there is one I made, called constructionKits, which are the ones that don't have an attribute in xml.
If you know how // How to load the array from a LUA, try helping me with it ^^

Feel free to give feedback or bugs! Everything is appreciated

### CODE REVIEW

**Comment by Lycanzito** [comment]
Holy moly;

👍

**Comment by Lycanzito** [comment]
For some reason, it is not working for me.

**Comment by hyresu** [comment]
Test it now, it should be working (I made a fix in the Costallat commit and I didn't remember)
Also I included a fix for the tapestrys on wall (#340) Thanks @MajestyOTBR

**Comment by majestyotbr** [comment]
Thanks @hyresu!

**Comment by Lycanzito** [comment]
edited;

**Comment by Sargitarium** [comment]
Bem verificando os arquivos e em house.cpp creio que você deveria de alguma forma fazer a busca pelo lua, pois caso haja um update dos itens teria que ficar alterando na SRC
Me refiro aos itens abaixo relacionados...

`int constructionKits[58][2] = {
{3901, 1666}, {3902, 1670}, {3903, 1652}, {3904, 1674},
{3905, 1658}, {3906, 3813}, {3907, 3817}, {3908, 1619}, {3909, 12799}, {3910, 2105},
{3911, 1614}, {3912, 3806}, {3913, 3807}, {3914, 3809}, {3915, 1716}, {3916, 1724},
{3917, 1732}, {3918, 1775}, {3919, 1774}, {3920, 1750}, {3921, 3832}, {3922, 2095},
{3923, 2098}, {3924, 2064}, {3925, 2582}, {3926, 2117}, {3927, 1728}, {3928, 1442},
{3929, 1446}, {3930, 1447}, {3931, 2034}, {3932, 2604}, {3933, 2080}, {3934, 2084},
{3935, 3821}, {3936, 3811}, {3937, 2101}, {3938, 3812}, {5086, 5046}, {5087, 5055},
{5088, 5056}, {6114, 6111}, {6115, 6109}, {6372, 6356}, {6373, 6371}, {8692, 8688},
{9974, 9975}, {11124, 11125}, {11126, 11127}, {11133, 11129}, {11205, 11203}, {14328, 1616},
{14329, 1615}, {16075, 16020}, {16099, 16098}, {20254, 20295}, {20255, 20297}, {20257, 20299},
	};`

**Comment by hyresu** [comment]
@Sargitarium yes, as I said, I don't know if there's a file to keep arrays, I ended duping that array, and being able to load it from lua would be very useful, right now I don´t know how to, I've been programming ot source code for like 2-3 weeks ;;

**Comment by Lycanzito** [comment]
#912 
should be closed after this pdate carpets.lua

**Comment by majestyotbr** [comment]
Thanks for your contribution!

**Pull request merged**
