### PR TITLE
Feyrist respawn time

### PR DESCRIPTION
**Pull request by dex-89**
Day/Night spawn feyrist

### CODE REVIEW

**Comment by heberholanda** [comment]
Did you test it?

**Comment by dex-89** [comment]
No, i check only spawn
https://tibia.fandom.com/wiki/Feyrist_Meadows

it must be tested

**Review by heberholanda — APPROVED** [review]

**Review by heberholanda — APPROVED** [review]

**Review by heberholanda — APPROVED** [review]

**Review by heberholanda — APPROVED** [review]

**Comment by dex-89** [comment]
i think to do it via event (onspawn) but i don't get respawnType parameter, i don't know why?
self:getType():respawnType()

and self:getType():canSpawn(position) return always true (whether it's day or night)

**Comment by dex-89** [comment]
Spawn doesn't change. As I checked the spawn, I saw there was a problem with the light (LightChange). Morning, 8:00 in Tibia and light 250.

Light function is in game.cpp and game.h in sources

**Comment by debone** [comment]
Thank you for the contribution @dex-89! As you described, there are some malfunctioning code which I fixed in #1913. Along that, I have changed the way the flag is written on monster. Could you update your contribution please?

**Comment by dex-89** [comment]
> Thank you for the contribution @dex-89! As you described, there are some malfunctioning code which I fixed in #1913. Along that, I have changed the way the flag is written on monster. Could you update your contribution please?

Update complete. I'm not sure if it's correct, but it should be ok.

**Comment by debone** [comment]
Thank you @dex-89 for the quick fix, it's perfect. I changed the branch to the one we are working on the monsters, which later will be merged to develop.

**Pull request merged**
