### PR TITLE
Fix nil value on server save

### PR DESCRIPTION
**Pull request by Costallat**
Signed-off-by: Renato Foot Guimarães Costallat <costallat@hotmail.com>

### CODE REVIEW

**Comment by yatozin** [comment]
Lua Script Error: [Main Interface]
in a timer event called from:
(Unknown scriptfile)
data/globalevents/scripts/serversave.lua:21: attempt to perform arithmetic on local 'remaningTime' (a nil value)
stack traceback:
        [C]: in function '__sub'

**Comment by Costallat** [comment]
try now

**Comment by yatozin** [comment]
Lua Script Error: [Main Interface]
in a timer event called from:
(Unknown scriptfile)
data/globalevents/scripts/serversave.lua:18: attempt to perform arithmetic on local 'remaningTime' (a table value)
stack traceback:
        [C]: in function '__sub'
        data/globalevents/scripts/serversave.lua:18: in function <data/globalevents/scripts/serversave.lua:17>

> try now

**Comment by yatozin** [comment]
no errors appears to be working good now

**Comment by majestyotbr** [comment]
Thanks for the fix.

**Pull request merged**
