### PR TITLE
Prevent Black Knight to Double Spawn based on SpawnRadius

### PR DESCRIPTION
**Pull request by miezaF**

### CODE REVIEW

**Comment by newacc12** [comment]
@Flyckks I suppose this is to fix #461 right? Thanks for looking into it; however do you think this is the real fix? I pretty sure that this happens to other spawns as well (demons on the way to demon helmet is one example). I think we should somehow look into changing the source code to prevent this once for all. What do you think @MajestyOTBR ?

**Comment by majestyotbr** [comment]
I agree with you @newacc12.

**Comment by miezaF** [comment]
@newacc12 it should be applied to more places,  since The spawn should be based on Hunt radius, not monster pos radius.  So it become like 
monster pos = initial pos
radius = max dist to disappear or return to initial pos

**Comment by newacc12** [comment]
@Flyckks I am not sure I get what you mean. As far as I understand, the radius on RME is meant to be used as a place where you can place monsters inside the map. I believe we should not increase the size just so we can fix an error in our source code that makes it spawn duplicated monsters. The despawnradius on the config file is what determine if the monster will disappear or not.

Just as an example, you 'fixed' the Black Knight by increasing the radius but on the same room, if you walk to the south, the server will start spawning duplicated bonelords. I don't see how this solution will be feasible to implement in all the respawns that we have. It seems that finding a solution on the source code will be much easier/better than changing the radius of all creatures.

I will play with the source code if I find the time and try to submit a PR so we can evaluate. Thanks for your input.

**Comment by dudantas** [comment]
> @Flyckks I am not sure I get what you mean. As far as I understand, the radius on RME is meant to be used as a place where you can place monsters inside the map. I believe we should not increase the size just so we can fix an error in our source code that makes it spawn duplicated monsters. The despawnradius on the config file is what determine if the monster will disappear or not.
> 
> Just as an example, you 'fixed' the Black Knight by increasing the radius but on the same room, if you walk to the south, the server will start spawning duplicated bonelords. I don't see how this solution will be feasible to implement in all the respawns that we have. It seems that finding a solution on the source code will be much easier/better than changing the radius of all creatures.
> 
> I will play with the source code if I find the time and try to submit a PR so we can evaluate. Thanks for your input.

Thanks for the clarification.
In fact, you are absolutely right.
We should look for the root of the problem and not temporary solutions that will generate other bugs ...

**Pull request merged**
