### PR TITLE
[Custom] Free Quests system

### PR DESCRIPTION
**Pull request by dex-89**
List base: https://forums.otserv.com.br/index.php?/forums/topic/169565-otservbr-global-liberar-acessos-a-quests-e-cidades/

### CODE REVIEW

**Review by Costallat — APPROVED** [review]

**Comment by majestyotbr** [comment]
@dex-89 Nice, thank you! 👍

**Review by hyresu — APPROVED** [review]

**Comment by yatozin** [comment]
Lua Script Error: [Scripts Interface] 
/var/www/Anarchy/data/scripts/creaturescripts/customs/freequests.lua
...rchy/data/scripts/creaturescripts/customs/freequests.lua:330: attempt to index global 'playerLogin' (a nil value)
stack traceback:
	[C]: in function '__newindex'
	...rchy/data/scripts/creaturescripts/customs/freequests.lua:330: in main chunk
> freequests.lua [error]

**Comment by hyresu** [comment]
@yatozin test again, please

**Comment by yatozin** [comment]
> @yatozin test again, please

no error now but cant login :s

**Comment by yatozin** [comment]
is working now

**Comment by daanyx** [comment]
Exelente!

**Comment by cys9211** [comment]
Kawał dobrej roboty!

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
