### PR TITLE
Addition of Quiver's

### PR DESCRIPTION
**Pull request by cys9211**
All types of quiver's have been added to npc in all cities

[X] Ab'Dendriel	Irea
[X] Ankrahmun	Dario
[X] Carlin	Perac
[X] Darashia	Edoch
[X] Edron	Willard
[X] Farmine	Pompan
[X] Feyrist	Taegen
[X] Gray Beach	Rock In A Hard Place
[X] Issavi	Eliyas
[X] Kazordoon	Gnomerrow
[X] Kazordoon	Uzgod
[X] Krailos	Mugruu
[X] Liberty Bay	Cedrik
[X] Port Hope	Brengus
[X] Port Hope	Perod
[X] Rathleton	Silas
[X] Roshamuul	Asnarus
[X] Roshamuul	Maun
[X] Svargrond	Robert
[X] Thais	Galuna
[X] Venore	Xed
[X] Yalahar	Vincent

### CODE REVIEW

**Comment by hyresu** [comment]
I reviewed and instead of Perod think it must be Raffael, as Perod doesn't sell quivers

https://tibia.fandom.com/wiki/Red_Quiver

However I must thank you so much for this, I forgot in my pr and this contribution is excellent! Thank you very much

**Comment by majestyotbr** [comment]
Next time, remember to use a branch (based on develop) to update files and send pull requests.

**Comment by MajestyOTBR** [comment]
Perod does not sell quivers and Raffael is missing. 
https://tibia.fandom.com/wiki/Red_Quiver

**Comment by majestyotbr** [comment]
Perod does not sell quivers and Raffael is missing.

https://tibia.fandom.com/wiki/Quiver
https://tibia.fandom.com/wiki/Blue_Quiver
https://tibia.fandom.com/wiki/Red_Quiver

**Comment by daanyx** [comment]
Tenho trabalhado nos NPc's.
Estou preparando uma atualização completa dos NPC's de venda.
Em breve estarei preparando um PR.
Perod vende aljavas sim!
Captura de tela 2021-01-16 184634
Esta imagem é do tibia global.
Tenho usado muito o tibiopedia.pl eles estão com o conteúdo bem atualizado.
Mas sempre olhando os outros e vendo In Game também.
@hyresu @MajestyOTBR

**Comment by majestyotbr** [comment]
@daanyx 👍

**Pull request closed without merging**
