### PR TITLE
fix: prey final patch

### PR DESCRIPTION
**Pull request by westwol**
Tested myself and it's working as inteed.
Feel free to report any issue.,

### CODE REVIEW

**Comment by gerotib** [comment]
Works fine for me and also fixed crash while opening cyclopedia.

**Comment by gpedro** [comment]
clang was reported some error:
```
/home/travis/build/opentibiabr/OTServBR-Global/src/iologindata.cpp:255:52: error: 
418      use of overloaded operator '<<' is ambiguous (with operand types
419      'basic_ostream<char, std::char_traits<char> >' and 'PreyState_t')
420  ...query << player->getGUID() << ',' << num << ',' << PREY_STATE_SELECTION ...
```

**Review by liontts — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
Tested, working. Thanks for the fix.

**Comment by dudantas** [comment]
Thanks @westwol

**Pull request merged**
