### PR TITLE
Fix sending letters

### PR DESCRIPTION
**Pull request by hyresu**
Fix for #2248

### CODE REVIEW

**Review by dex-89 — APPROVED** [review]

**Comment by gpedro** [comment]
isn't better to fix it on Mailbox.cpp?

**Comment by hyresu** [comment]
> isn't better to fix it on Mailbox.cpp?

done

**Review by dex-89 — APPROVED** [review]
All works. Parcel, letter 👍

**Review by gpedro — APPROVED** [review]

**Review by CarlosAlexanderGonzalezGarcia — COMMENTED** [review]
on line 108 change time_t date;  for time_t date{};

**Comment by majestyotbr** [comment]
@gpedro

**Pull request merged**
