### PR TITLE
Highscores

### PR DESCRIPTION
**Pull request by dex-89**
**Compilation: no errors. For me it works 100% correcty.**

- [x] Administration must be removed from the list

**Very thanks for help: @HeberPcL @lgrossi**

**Players with the same number of points have a tie (same number)**

**Based at @SaiyansKing script**

2020-11-14_000600741_GOD_Hotkey
2020-11-14_000953303_GOD_Hotkey
2020-11-14_003555007_GOD1_Hotkey
2020-11-14_003541792_GOD1_Hotkey
2020-11-14_003447688_GOD1_Hotkey

### CODE REVIEW

**Comment by debone** [comment]
Thanks for your contribution @dex-89! There seems to be some reviewdog comments that would be nice to address (I think the line length ones you can safely ignore), and also some due credit to the original authors of this code ;) You are already getting the PR and the commits under your name, it'd be nice if we could at least see a mention. Ideally you could start cherrypicking the changes from the repos and just fixing the merge conflicts.

**Comment by dex-89** [comment]
> Thanks for your contribution @dex-89! There seems to be some reviewdog comments that would be nice to address (I think the line length ones you can safely ignore), and also some due credit to the original authors of this code ;) You are already getting the PR and the commits under your name, it'd be nice if we could at least see a mention. Ideally you could start cherrypicking the changes from the repos and just fixing the merge conflicts.

This script is ours. Based on the @SaiyansKing script, but its source did not compile here. There were mistakes. He add other library to his script, we didn't and work correctly.

And I myself have removed the administration from this script

But @SaiyansKing added in description

**Comment by majestyotbr** [comment]
Remember to merge with protocol 12.60.

**Comment by dex-89** [comment]
> Remember to merge with protocol 12.60.

No problem after marge 12.60 a make PR to remove it (if >=1260)

**Comment by MajestyOTBR** [comment]
> No problem after merge 12.60 i make a PR to remove it (if >=1260)
Ok.

**Comment by majestyotbr** [comment]
> No problem after marge 12.60 a make PR to remove it (if >=1260)

Ok.

**Review by majestyotbr — APPROVED** [review]

**Comment by Sajgon** [comment]
Hi @dex-89 , thanks for your contribution. Do you have the client side code for this? or how do I test it from server.

**Comment by dex-89** [comment]
> Hi @dex-89 , thanks for your contribution. Do you have the client side code for this? or how do I test it from server.

I used client version 12.51. It has highscores

**Pull request merged**
