### PR TITLE
Movable beds

### LINKED ISSUE #2402: MAP: The Counterspell rn is uneeded
#### What are the coordinates of the place where the issue with the map was found?
- X: 32092
- Y: 32578
- Z: 8

#### What kind of issue you found (respawns missing, details, large areas...)?
- there are some energy barriers that has to have actionid 4000 (u can see at \data\scripts\movements\quests\the_sharttered_isles\energy_barrier.lua)

https://gyazo.com/4e0bafe7bed1977c1d51a94da6913f96

There is a quest between chondur and this tiles that is already coded but u can bypass the barriers because still missing actionid4000 on them

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52):

### LINKED ISSUE #2442: Add NPC's to the map
The following NPC's need to be added to the map:

- H.L.
- Nicholas

They are already present and updated in the npcs folder.
I am unable to provide coordinates at this time.
Sorry!

### PR DESCRIPTION
**Pull request by dex-89**
**New Movable Beds System**

- [x] **DEPENDENCY: #2252** by @hyresu

**General progress:**
by @phacUFPE 

- [x] Wrap beds;
- [x] Change the bed use (click to sleep) only to the pillow part;
- [x] Fix Map loading more beds than actually have in the house;
- [x] Fix when moving beds it is counting as bed twice;
- [x] Edit RME to set max beds per house and clientId;
- [x] Fix crashing server when unwrapping outside house;
- [x] Fix crash on dummy unwrap;
- [x] Fix can sleep with pillow part to one direction and the foot part with another direction (example: pillow part to north and foot part to west);
- [x] Read limit beds from houses XML (map);
- [x] Fix game store. Player need to receive two items when buy one bed;
- [ ] Rework npc buyable items module;
- [ ] Add some beds to game store;
- [x] Remove all beds from global map and set limit max beds in house
### BEDS ON MAP:
- [X] Ab'Dendriel
- [X] Ankrahmun
- [X] Carlin
- [X] Darashia
- [X] Edron
- [x] Farmine
- [x] Gray Beach
- [x] Issavi
- [x] Kazordoon
- [x] Liberty Bay
- [x] Port Hope
- [x] Rathleton
- [x] Svargrond
- [x] Thais
- [x] Venore
- [x] Yalahar
### NPCS TO ADD BEDS
**PROGRESS**
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

### **FIX BUG ON SLEEP IN NEW BEDS**
**BEDS PROGRESS**
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 
- [x] 

**Others changes:**
- [x] Fixed Frodo tawern by @ElTeixe

### CODE REVIEW

**Comment by ElTeixe** [comment]
Seems you both getting progress!  Keep it up!


Please dont forget about store beds:

Grandiose bed:
image

Magnificent bed:
image

Ornate bed:
image

Vengothic bed:
image

Wrought bed:
image

Homely bed:
image

Verdant bed:
image

**Comment by phacUFPE** [comment]
> Seems you both getting progress! Keep it up!
> 
> Please dont forget about store beds:
> 
> Grandiose bed:
> image
> 
> Magnificent bed:
> image
> 
> Ornate bed:
> image
> 
> Vengothic bed:
> image
> 
> Wrought bed:
> image
> 
> Homely bed:
> image
> 
> Verdant bed:
> image

Thanks for the images and i'll not forget

@ElTeixe can you help me leaving the new beds id in the comment ? :)

**Comment by ElTeixe** [comment]
Sure!

> Grandiose bed:
> image
> - Vertical
> Empty Head: 40771
> Empty Foot: 40772
> Male Head: 40763
> Male Foot: 40764
> Female Head: 40767
> Female Foot: 40768
> - Horizontal
> Empty Head: 40773
> Empty Foot: 40774
> Male Head: 40765
> Male Foot: 40766
> Female Head: 40769
> Female Foot: 40770
> 
> Magnificent bed:
> image
> - Vertical
> Empty Head: 40694
> Empty Foot: 40695
> Male Head: 40686
> Male Foot: 40687
> Female Head: 40690
> Female Foot: 40691
> - Horizontal
> Empty Head: 40696
> Empty Foot: 40697
> Male Head: 40688
> Male Foot: 40689
> Female Head: 40692
> Female Foot: 40693
> 
> Ornate bed:
> image
> - Vertical
> Empty Head: 40706
> Empty Foot: 40707
> Male Head: 40698
> Male Foot: 40699
> Female Head: 40702
> Female Foot: 40703
> - Horizontal
> Empty Head: 40708
> Empty Foot: 40709
> Male Head: 40700
> Male Foot: 40701
> Female Head: 40704
> Female Foot: 40705
> 
> Vengothic bed:
> image
> - Vertical
> Empty Head: 40718
> Empty Foot: 40719
> Male Head: 40710
> Male Foot: 40711
> Female Head: 40714
> Female Foot: 40715
> - Horizontal
> Empty Head: 40720
> Empty Foot: 40721
> Male Head: 40712
> Male Foot: 40713
> Female Head: 40716
> Female Foot: 40717
> 
> Wrought bed:
> image
> - Vertical
> Empty Head: 40041
> Empty Foot: 40042
> Male Head: 40024
> Male Foot: 40025
> Female Head: 40028
> Female Foot: 40038
> - Horizontal
> Empty Head: 40043
> Empty Foot: 40044
> Male Head: 40026
> Male Foot: 40027
> Female Head: 40039
> Female Foot: 40040
> 
> Homely bed:
> image
> - Vertical
> Empty Head: 39155
> Empty Foot: 39156
> Male Head: 39147
> Male Foot: 39148
> Female Head: 39151
> Female Foot: 39152
> - Horizontal
> Empty Head: 39157
> Empty Foot: 39158
> Male Head: 39149
> Male Foot: 39150
> Female Head: 39153
> Female Foot: 39154
> 
> Verdant bed:
> image
> - Vertical
> Empty Head: 29332
> Empty Foot: 29333
> Male Head: 29324
> Male Foot: 29325
> Female Head: 29328
> Female Foot: 29329
> - Horizontal
> Empty Head: 29334
> Empty Foot: 29335
> Male Head: 29326
> Male Foot: 29327
> Female Head: 29330
> Female Foot: 29331

Added Verdant bed, thanks to @MajestyOTBR .

**Comment by daanyx** [comment]
These are the NPC's who must work selling the new mobile beds.

Ab'Dendriel - Ukea.
Carlin - Nydala.
Kazordoon - Iwar.
Thais - Gamon.
Venore - Allen.
Fibula - Eddy.
Senja - Vera.
Ankrahmun - Feizuhl.
Darashia - Hofech.
Edron - Edvard.
Liberty Bay - Peggy.
Svargrond - Janz.
Yalahar - Dorbin.
Cormaya - Yoem.
Rathleton - Nicholas.
Issavi - Inkaef.

https://www.tibiopedia.pl/

**Comment by daanyx** [comment]
Hello people!
Taking advantage of the work being done in items.xml.
Could these items be inserted? 
They must also be sold by the npc's! 
They are from a recent update as well.
I don't have much knowledge to do this type of insertion.
unknown

**Comment by phacUFPE** [comment]
> Hello people!
> Taking advantage of the work being done in items.xml could these items be inserted? They must also be sold by the npc's! They are from a recent update as well. I don't have much knowledge to do this type of insertion.
> unknown

theses items is creature products ?
can you leave the link of the wiki please ?

**Comment by daanyx** [comment]
> > Olá pessoas! 
> > Aproveitando o trabalho que está sendo feito no items.xml, esses itens podem ser inseridos? Eles também devem ser vendidos pelos npc's! Eles também são de uma atualização recente. Não tenho muito conhecimento para fazer esse tipo de inserção.
> > desconhecido
> 
> Esses itens são produtos de criaturas?
> você pode deixar o link do wiki por favor?
https://tibiopedia.pl/updates/12.30.9367

**Comment by daanyx** [comment]
#2392 
Salve!
Não são itens de criaturas!
Eu havia criado um inssue que trata sobre estes itens.

**Comment by daanyx** [comment]
image
image

**Review by Juanzin93 — COMMENTED** [review]
when adding to store its not showing image if you add the array on itemtype

**Comment by Bipbop69** [comment]
> when adding to store its not showing image if you add the array on itemtype
@dex-89 
I think I would have to use a photo on the icons I tested it was unsuccessful

**Comment by majestyotbr** [comment]
PR closed due to inactivity.

**Comment by omeranha** [comment]
I did not understand, rework npc buyable items module?

**Pull request closed without merging**
