### PR TITLE
Fixed issues with the Behemoth quest and Cormaya guildhouse

### LINKED ISSUE #482: Behemoth quest issues
**Describe the bug**
The behemoth quest in Edron is missing some details to be like in global Tibia.
1 - An orc corpse is missing at 33290, 31715, 12.
2 - Once you pull the lever at 33290, 31715, 12 you can't pull it back.

**To Reproduce**
1. Go to 33290, 31715, 12
2. Check that you are missing the orc corpse.
3. Check that once you pull the lever you can't pull it anymore.

**Expected behavior**
A orc corpse is hiding the lever and you can pull the lever multiple times.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
You can check the behavior here: https://www.youtube.com/watch?v=VOpoR4HI0nU and https://tibia.fandom.com/wiki/Behemoth_Quest

### PR DESCRIPTION
**Pull request by newacc12**
Should fix #482 and #478

### CODE REVIEW

**Comment by dudantas** [comment]
@newacc12 Didn't you change the spawn?

**Comment by dudantas** [comment]
@newacc12 I made a small mistake, I took your map to make a correction that a contributor requested and forgot to merge your PR before committing my map (which contained your changes) now conflicted, so I will close the PR (your changes are already in the base here https://github.com/opentibiabr/OTServBR-Global/commit/faca889d17873b3372e055dd695f1baf221d5f3c)
I'm sorry for the mistake. Closing. 
And thanks for the collaboration, next time I will have more attention.

**Comment by newacc12** [comment]
> @newacc12 Didn't you change the spawn?

No I didn't. I only changed stuff in the map itself.

**Comment by newacc12** [comment]
> @newacc12 I made a small mistake, I took your map to make a correction that a contributor requested and forgot to merge your PR before committing my map (which contained your changes) now conflicted, so I will close the PR (your changes are already in the base here [faca889](https://github.com/opentibiabr/OTServBR-Global/commit/faca889d17873b3372e055dd695f1baf221d5f3c))
> I'm sorry for the mistake. Closing.
> And thanks for the collaboration, next time I will have more attention.

@eduardodantas95 No problem and thanks for letting me know. As long as the changes are there I am happy :)

**Comment by dudantas** [comment]
> > @newacc12 I made a small mistake, I took your map to make a correction that a contributor requested and forgot to merge your PR before committing my map (which contained your changes) now conflicted, so I will close the PR (your changes are already in the base here [faca889](https://github.com/opentibiabr/OTServBR-Global/commit/faca889d17873b3372e055dd695f1baf221d5f3c))
> > I'm sorry for the mistake. Closing.
> > And thanks for the collaboration, next time I will have more attention.
> 
> @eduardodantas95 No problem and thanks for letting me know. As long as the changes are there I am happy :)

Thank you for understanding.
But, I will be careful not to happen again, it is good to see the PR's being approved with the credit of the due contributors.

**Pull request closed without merging**
