### PR TITLE
Features: Party list support

### PR DESCRIPTION
**Pull request by dex-89**
**Thanks:** @marcosvf132

Credits: @SaiyansKing

### CODE REVIEW

**Review by phacUFPE — APPROVED** [review]
Tested and works!

**Review by Bipbop69 — APPROVED** [review]

**Comment by gerotib** [comment]
If party member is not on screen and log out, he will stay on party list:
elo

**Comment by dex-89** [comment]
> If party member is not on screen and log out, he will stay on party list:
> elo

Probably its ok. I check this at global

**Review by majestyotbr — APPROVED** [review]

**Comment by phacUFPE** [comment]
> > If party member is not on screen and log out, he will stay on party list:
> > elo
> 
> Probably its ok. I check this at global

at global the character is removed from party list on logout. need to fix it
@dex-89

**Review by adrianomengue — APPROVED** [review]

**Review by Costallat — APPROVED** [review]

**Pull request merged**
