### PR TITLE
Fix inconsistencies at The Explorer Society Quest

### LINKED ISSUE #1276: Missing Purple butterflies for The Explorer Society Quest
**Is your feature request related to a problem? Please describe.**
There are no spawns for purple butterflies on the usual places. Cormaya Garden as an example only has spawns for Blue and Red butterflies, according to [The Explorer Society Quest - TibiaWiki](https://www.tibiawiki.com.br/wiki/The_Explorer_Society_Quest) there was supposed to be a spawn for it. There are other places that they should be spawning but none were found.

**Describe the solution you'd like**
Find the usual places and place a spawn point for them.

**Describe alternatives you've considered**
No alternatives, not that I can think of.

**Links**
[Butterly (Purple)](https://tibia.fandom.com/wiki/Butterfly_(Purple)) - Has the usual spawn points for them: Yalahar, Tiquanda, the Shattered Isles, Alatar Lake, Carlin, Ab'Dendriel and some other places.

**Additional context**
No additional context available.

### LINKED ISSUE #1533: Recompensas de Chest invertidas
**Describe the bug**

A recompensa de dois chests estão **invertidas**. Não sei se já foi reportado, mas here we go:

Chest: (32939, 31776, 9)  está dando Orc Powder (item da Explorer Society Quest)
Chest: (32967, 31719, 2) está dando Wolf Tooth Chain (Ceiron's), item do Druid Outfit Quest.

### PR DESCRIPTION
**Pull request by fernandomatos**
## Introduction
I've changed this pull request content and title to group all the inconsistencies that I'm discovering at **The Explorer Society Quest** to be more easy and simple to manage and discute. 

## Description
I'm going through all steps of The Explorer Society Quest and submitting commits with fixes of my findings. 

This is the reference that I'm using to check the expected behaviors:
https://tibia.fandom.com/wiki/The_Explorer_Society_Quest

## Case
Apparently there are a few issues preventing completing the quest and I'm trying to identify and fix them.

When this pull request gets merged it will resolve, among other things, these issues as well:
#1276  
#1533 

**Legend**: 
| ✔️         | ⚠️     | ✋              | 
|----------|-----    |-------------| 
| All good | Fix | Help needed |

### Missions for a Novice
- [X] ⚠️ Before you begin **[Fix 1]**
- [X] ✔️ Joining the Explorers
- [X] ✔️ The Ice Delivery
- [X] ⚠️ The Butterfly Hunt **[Fix 2]**
- [X] ✔️ The Plant Collection

### Missions for a Journeyman
- [X] ✔️ The Lizard Urn
- [X] ⚠️ The Bonelord Secret **[Fix 4]**
- [X] ⚠️ The Orc Powder **[Fix 3]** ✋
### Missions for a Relic Hunter
- [X] ⚠️ The Elven Poetry **[Fix 4]**
- [X] ✔️ The Memory Stone
- [X] ✔️ The Rune Writings
### Missions for an Explorer
- [X] ✔️ The Ectoplasm
- [X] ✔️ The Spectral Dress
- [X] ⚠️ The Spectral Stone **[Fix 4]**
- [X] ⚠️ The Astral Portals **[Fix 4]**
### Additional missions
- [X] ✔️ The Island of Dragons
- [X] ✔️ The Ice Music
- [X] ⚠️ The Undersea Kingdom **[Fix 4]**
- [X] 🗺️ The Frozen Trench (_missing content_)
- [X] ✔️ The Skull of Ratha
- [X] ✔️ The Giant Smith Hammer

## Fix 1

| Rank | Mission |
|------|---------|
| None | None |

### What's happening?

It's possible to buy a Crown Backpack or any other items of Explorer Society without having completed the quest.

If the player haven’t completed the the final step of **The Explorer Society Quest**, he should not trade with Angus or Mortimer according to Tibia Wiki:
https://tibia.fandom.com/wiki/The_Explorer_Society_Quest#The_Astral_Portals

### How am I fixing this issue?

Based on the other NPCs with similar purposes, I made a conditional loop to check if the storage `Storage.ExplorerSociety.TheAstralPortals` is different from 56. 

Which represents that Astral Portals Mission of The Explorer Society hasn't been completed and both, Angus and Mortimer, must not be answering for trade requests.

**Commit or pull request related:** 3507f3bf85c8765a5d2ae6997b809bc6e0a2c93c

## Fix 2

| Rank | Mission |
|------|---------|
| Joining the Explorers | The Butterfly Hunt|

### What's happening?
It's missing purple, blue and red butterflies spawns required for The Butterfly Hunt mission.

### How am I fixing this issue?
I'm adding a spawns for the missing butterflies in `data\world\otservbr-spawn.xm`.  Full explanation is in #2211. 

*This fix for this issue I made in a second PR because was before I grouping all my findings at this PR.*

**Commit or pull request related:** #2211, f856f543ed8f7cd8001a2840ab419b1d2e5a6130

## Fix 3

| Rank | Mission |
|------|---------|
| Journeyman | The Orc Powder|

### What's happening?

There is a expertise door instead a quest door at Explorer Society Orc Fortress Mission. 

### How am I fixing this issue?

I am not, I think this probably needs a OTBM fix. 

### 🗺️ OTBM fix needed
Help needed here ✋
`{x = 32967, y = 31720, z = 2}`

1. Needs to replace the door for a quest door, now it's using a expertise door of level 30.  

## Fix 4

| Rank | Mission |
|------|---------|
| All| All|

### What's happening?

There are several mission chests rewarding wrong items, a locked doors and actions updating missions storages with wrong values.

Because of these problems, it isn't possible to progress and complete The Explorer Society missions:

| Rank         | Mission             | Issue                                                        | Fixed? |
| ------------ | ------------------- | ------------------------------------------------------------ | ------ |
| **Journeyman**   | The Bonelord Secret | Chest isn't updating the correct storage, preventing it from proceeding with the mission. | ✔️    |
| **Journeyman**   | The Orc Powder      | Chest rewarding the wrong item and mission door opening to anyone, preventing it from proceeding with the mission. | ✔️    |
| **Relic Hunter** | The Elven Poetry    | Chest isn't updating the correct storage, preventing it from proceeding with the mission. | ✔️   |
| **Explorer**     | The Spectral Stone  | Mission door isn't opening and the Spectral Stone isn't being possible to use in Nortporth, preventing it from proceeding with the mission. | ✔️    |
| **Explorer**     | Astral Portals      | Mission door isn't opening and astral Portal tiles aren't working, preventing it from proceeding with the mission. | ✔️    |
| **Additional**     | The Undersea Kingdom      | Mission door isn't opening, preventing it from proceeding with the mission. | ✔️|
| **Additional**     | The Ice Music      | Mission door isn't opening and Lurik isn't updating the correct storage after The Ice Music mission, preventing it from proceeding with the mission. | ✔️|

### How am I fixing this issue?

First I was trying to identify and fix the *Action ID* and *Unique ID* problems. But then @gpedro gave me a heads up to check the new system of tables.

This three commits have my first approach: dbb6737d548492a8a3c36fb111bf634b5aae90b4, 44e0036ab82246ec2aa51b81ecd6d8fc5186472b, 8e1b46355f7999700ee16222418b2339e3fb984c

After, knowing about the tables system, I made a full rewriting of the Explorer Society that overwrites them.

**Commit or pull request related:** 3acbaaf4508b9cc37f3bff9c5b2000d9b9a6d5e8, 91a9985f22b7a632b1ebf0cd65cd860ffbe49ae9, a8fee0393290768bfa7975f2bfcf0386f5eec250, cd198c6106b41189c302a4972e3e0f96c1be333e, 309c655a038712dd64fb184b789316936d838c95

## Final thoughts

I'm following the quest and I will keep this PR posted with my findings and commits of fixes that I'm capable of solving by myself. The others findings that I will need help to solve, I will keep them here too. 

Like I said in my last PR #2190, I'm getting used to the project structure, understanding the mechanics you thought and learning with the commits of you all.

Thank you!

### CODE REVIEW

**Comment by fernandomatos** [comment]
I've changed this pull request content and title to group all the inconsistencies that I'm discovering at **The Explorer Society Quest** to be more easy and simple to manage and discute.

At this moment I have some commits that's needs to be reviewed and one fixe that I need help, because probably it's a .OTBM fixe 🗺️ .

All tracking of fixes and findings, I will do at the first post of this PR.

**Comment by gpedro** [comment]
about wrong action ids or unique ids, we have moved all these things to the tables.
if you want to add or change, please check this file first.

https://github.com/opentibiabr/otservbr-global/blob/develop/data/startup/tables/tile.lua


we moved to make it easier to contribute without  touching the map

**Comment by fernandomatos** [comment]
Thank you for the heads up @gpedro !

That's awesome that we have such thing like these tables now, means that probably I can fix all actions/uniques id/storages bugs of Explorer Society by myself now.

I read and understood the tables files, I will use them to refactor the Explorer Society scripts.

**Comment by fernandomatos** [comment]
My last commit (3acbaaf4508b9cc37f3bff9c5b2000d9b9a6d5e8) recreates The Explorer Society using tables and fixes some bugs in the quest and in the NPCs related, that was preventing missions progress.

* Fixes of storages and start/end mission values in the `core/quest.lua`
* Adds **TheElvenPoetry** storage missing in the `core/storages.lua`
* Fixes conditional statements in the Angus and Mortimer's files
* Adds Explorer Society unique mission chests in the `tables/chest.lua`
* Adds Explorer Society unique mission Items in the `tables/items.lua`
* Adds a single file `findings.lua` to handle with findings missions
* Removes Explorer Society old unique ID references from `quest_system2.lua`

**Comment by fernandomatos** [comment]
Today I've finished to fix the missions of all ranks from Explorer Society Quest 🥳 

Now I'm going to do the same with the additional missions. The first post of this PR has all the information about my work in progress.

**Comment by fernandomatos** [comment]
Well, this was an incredible journey!

I hope everybody can have fun now doing The Explorer Society on their servers. Can’t wait to tell my friends that we can go to the Explorer Society Quest now.  

I made my best to understand everything that was going on over there and learn about the best LUA practices used in the files by you.

I learned a lot with this experience, with all the existing code in the project and reading the Discord discussions. I will be glad to hear any kind of feedback for my improvement in the next ones.

Fun fact: I decided to try to fix Explorer Society when I tried to go to Calassa to get a gold fish for the Rashid's Travelling Trader Quest. One of the first missions needed to be able to go to Calassa was broken and that was the beginning of this whole adventure.  

Thank you for reviewing my pull request!

**Comment by dex-89** [comment]
Fix conflicting files, please

**Comment by fernandomatos** [comment]
> Fix conflicting files, please

Fixed conflicts, also the pull request #2211 is now merged here too.

image

**Comment by dex-89** [comment]
> > Fix conflicting files, please
> 
> Fixed conflicts, also the pull request #2211 is now merged here too.
> 
> image

Great work. In my spare time, I will check the entire quest and add a review

**Review by dudantas — APPROVED** [review]
Very good!

**Comment by fernandomatos** [comment]
> Very good!

Thank you for reviewing my pull request @dudantas

**Review by dex-89 — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
