### PR TITLE
Added exercise wands to NPC's.

### PR DESCRIPTION
**Pull request by daanyx**
- Reorganization of codes:

- For better viewing.

- Facilitation of future updates.

Correction of some NPC's clothes:
- Baltim
- Tarun
- Armenius

Other fixes:
- Siflind (reference in the .lua file)
Update the value of potions / runes. 
https://www.tibia.com/forum/?action=announcement&announcementid=91&boardid=89516
#2314 #2145 
@dex-89 @hyresu

### CODE REVIEW

**Review by dex-89 — APPROVED** [review]
I'm in shock. Amazing job. Many thanks for your contribution

**Comment by daanyx** [comment]
> I'm in shock. Amazing job. Many thanks for your contribution

Obrigado! É uma grande alegria poder colaborar.

**Comment by dex-89** [comment]
> > I'm in shock. Amazing job. Many thanks for your contribution
> 
> Obrigado! É uma grande alegria poder colaborar.

I think that you have other "hidden talents"?

**Review by henriquesameshima — APPROVED** [review]
Muito obrigado pela adição dos novos itens e principalmente pela correção dos preços.

**Review by Bipbop69 — APPROVED** [review]

**Review by paulorob-dev — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
