### PR TITLE
Create golem.lua

### PR DESCRIPTION
**Pull request by cys9211**

### CODE REVIEW

**Comment by cys9211** [comment]
Combine #1626  with #1627

**Comment by oualid6496** [comment]
Does it work like that on real to?

**Comment by cys9211** [comment]
> Does it work like that on real to?

In the real is a Reward from Shadows of Yalahar Quest.

Unfortunately, this mission is not and will not be in the project because it is unnecessary

**Comment by oualid6496** [comment]
> > Does it work like that on real to?
> 
> In the real is a Reward from Shadows of Yalahar Quest.
> 
> Unfortunately, this mission is not and will not be in the project because it is unnecessary

Says who? I thougt it was supposed to look as much as rl as possible.

**Comment by cys9211** [comment]
> > > Does it work like that on real to?
> > 
> > In the real is a Reward from Shadows of Yalahar Quest.
> > 
> > Unfortunately, this mission is not and will not be in the project because it is unnecessary
> 
> Says who? I thougt it was supposed to look as much as rl as possible.



I just added the script, the rest was already on the map

**Comment by oualid6496** [comment]
I think it's better to remove it from the map instead of making the script for it

**Comment by majestyotbr** [comment]
#726 Quests that need to be developed or revised.

Unfortunately, the script is not good. If you want to contribute, follow the pattern of the scripts of the project and do in one pull request.

**Pull request closed without merging**
