### PR TITLE
fix: farmine boat and falcon castle portals, resolves #113

### LINKED ISSUE #113: Falcon Castle - portals not working
1) Falcon castle should be accessible after clicking the small boat on farmine. 

08:16 You see a small boat.
Item ID: 3587, Action ID: 64007
Position: 33328, 31350, 7
falcon1

2) On the way back its also not working.

08:17 You see a paddle.
Item ID: 3600, Action ID: 57601
Position: 33344, 31348, 7
falcon2

3) And another one already on the respawn not working. 

08:19 You see electric sparks.
Item ID: 5069, Action ID: 57602
Position: 33309, 31325, 8
falcon3

### PR DESCRIPTION
**Pull request by gpedro**

### CODE REVIEW

**Comment by gpedro** [comment]
@eduardodantas95 
```
17:34 You see a mystic flame.
You feel drawn to the mesmerizing light.
Item ID: 1397
Position: 33305, 31347, 8
```

we needs actionid here!

**Comment by gpedro** [comment]
@Szulcek can you test, please?

**Comment by dudantas** [comment]
@gpedro put action id 3255
tomorrow I upload the map, but you can do the script

**Comment by gpedro** [comment]
done. please test before the merge.

**Comment by gpedro** [comment]
I will make another PR because this merge is so complex to me :D

**Pull request closed without merging**
