### PR TITLE
Updated sample players values

### PR DESCRIPTION
**Pull request by ElTeixe**
Added starting magic level and skills to 'Rook Sample' player to match Official.

- Magic level 2 + 23.19%
- Club, axe, sword and distance skills level 12 + 77.5%

Updated 'GOD' player default outfit to Game Master one, corrected health from 150 to 155, added exp to level 2, set town to thais.

### CODE REVIEW

**Comment by Costallat** [comment]
@ElTeixe you need to update the migrations too, to update those information for who already has a server.

**Comment by dudantas** [comment]
After adding in migration, it will be approved.

**Comment by ElTeixe** [comment]
> @ElTeixe you need to update the migrations too, to update those information for who already has a server.

Oh I didnt noticed. Thank you to point it, I'll try implement it too when I finish on what Im working at this moment.

**Comment by dudantas** [comment]
> > @ElTeixe you need to update the migrations too, to update those information for who already has a server.
> 
> Oh I didnt noticed. Thank you to point it, I'll try implement it too when I finish on what Im working at this moment.

Need help? I can assist you. The number 0 migration https://github.com/opentibiabr/otservbr-global/blob/3a2cbcc9eaf68af677057becbae8d22c30fe8173/data/migrations/0.lua#L4
It has the same thing as the schema, you just need to modify it there too

**Comment by ElTeixe** [comment]
> > > @ElTeixe you need to update the migrations too, to update those information for who already has a server.
> > 
> > 
> > Oh I didnt noticed. Thank you to point it, I'll try implement it too when I finish on what Im working at this moment.
> 
> Need help? I can assist you. The number 0 migration
> 
> https://github.com/opentibiabr/otservbr-global/blob/3a2cbcc9eaf68af677057becbae8d22c30fe8173/data/migrations/0.lua#L4
> 
> 
> It has the same thing as the schema, you just need to modify it there too

I havent checked it yet to be honest hahaha (Im finishing dawnport stuffs), but seems fast to correct, I'll try do it now then.

Thanks for point how to, avoids me to investigate!

**Comment by ElTeixe** [comment]
@dudantas 

I added it to migrations, but I only added the changing values for 'Rook Sample' and 'GOD' others have not changed. Its right or I must add them to the other sample players too?

**Comment by dex-89** [comment]
> @dudantas
> 
> I added it to migrations, but I only added the changing values for 'Rook Sample' and 'GOD' others have not changed. Its right or I must add them to the other sample players too?

Dont use migration file: 0.lua... only **next**...

**Comment by ElTeixe** [comment]
> > @dudantas
> > I added it to migrations, but I only added the changing values for 'Rook Sample' and 'GOD' others have not changed. Its right or I must add them to the other sample players too?
> 
> Dont use migration file: 0.lua... only **next**...

What you mean? Im a bit confused now lol

**Comment by dudantas** [comment]
> What you mean? Im a bit confused now lol

Migrations is for when someone with an outdated database (like an otadmin) can update their database without having to install the 0 schema, migration runs when opening the distro.

**Comment by ElTeixe** [comment]
@dudantas Makes sense, but was asking about @dex-89 reply:

> @dex-89 
> Dont use migration file: 0.lua... only **next**...

So, is wrong? What I should do then? Thats why I said Im confused XD

**Comment by Costallat** [comment]
@ElTeixe you have to create a new migrations, not change the existing one, or people who have a server will not run those migrations as they already run on the first server start

**Comment by dudantas** [comment]
> @ElTeixe you have to create a new migrations, not change the existing one, or people who have a server will not run those migrations as they already run on the first server start

Thanks, Foot, that's exactly it, I was wrong.

You need to create a new migration with your changes and return the 0 to what it was.

**Comment by ElTeixe** [comment]
@Costallat, @dudantas, @dex-89 

Oh I got it now, I got confused by the reference to migrations/0.lua file, but was a reference not where I need to add them. Im sorry, I'll try correct it now.

**Comment by ElTeixe** [comment]
I think its done now, I forgot update my branch before the final fix and I made a mistake again. Im sorry, I feel like a noob now lol

**Review by dex-89 — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

**Review by dudantas — APPROVED** [review]

**Pull request merged**
