### PR TITLE
Close.

### PR DESCRIPTION
**Pull request by YohanAugusto**
Close.

### CODE REVIEW

**Review by omarcopires — APPROVED** [review]

**Comment by gpedro** [comment]
i, personally, prefer otland/forgottenserver#2965 solution

**Comment by lBaah** [comment]
It would be great as @gpedro said. Therefore it you can just clean the string at protocolgame, before we sent it to house. That don't seem to be very optimal.
Please reconsider your code, or please make sure to tell us what are you doing with the code you just wrote.

**Comment by YohanAugusto** [comment]
I didn't write the code (i didn't buy it), it’s just a temporary solution. It’s up to you accept or not. I just want to share this for those who have problem with this (that’s the idea, right?), feel free to close it or make it better.

When i have time, i can try to work on something better! (Again: I didnt write de code)

I know ppl who earn money from server’s problems that wont be happy with that PR. A lot of people are angry because of it. For me, doesn't matter since i don't have a server.

**Review by MillhioreBT — COMMENTED** [review]
Is this currently happening? I tried to reproduce this and I was not successful, someone who explains the steps to me well ...

**Pull request closed without merging**
